### ISSUE TITLE
nbands_istate: This parameter may be changed to select the i-th band to calculate.

### ISSUE THREAD

**Issue by sgyang345** [deepmodeling/abacus-develop#2924]
### Background

In some cases, people want to know the charge density distribution of deeper energy levels,such as the twisted systems.

However, these systems are usually large, and the calculation of the partial charge density of multiple bands will greatly consume storage space.

### Describe the solution you'd like

It is suggested to add a setting: one can directly select the specific band index for get_pcha or get_wf.

### Task list for Issue attackers

- [x] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team and stakeholders on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
@sgyang345 
In LCAO calculations, the storage of ABACUS mainly depends on the charge density (grid number), instead of eigenstates since LCAO is a rather small basis. The memory demand of fully charge density is as same as a partial one. Therefore, this suggestion is not helpful for memory and time cost. Of course, for PW calculations, it is a totally different story since PW is a big basis. Would you mean PW calculations?

**Comment by WHUweiqingzhou** [comment]
see also Issue #3572
