### ISSUE TITLE
Fails to perform HSE docalculation For AlN with supercell of 64 atoms

### ISSUE THREAD

**Issue by QG-phy** [deepmodeling/abacus-develop#2934]
### Describe the bug

I tried to run ABACUS on the Bohrium platform using machines c32_m246_cpu and c64_m512_cpu for the AlN system with 64 atoms. it always reported an error message with: 

<img width="1021" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/98570179/48cdb02c-07b9-4a58-a201-a59fe6b281fe">

" 
Initial plane wave basis and FFT box
 ---------------------------------------------------------
 DONE(0.344638   SEC) : INIT PLANEWAVE
 -------------------------------------------
 SELF-CONSISTENT : 
 -------------------------------------------
 START CHARGE      : atomic
Abort(738840578) on node 0 (rank 0 in comm 0): Fatal error in internal_Isend: Invalid count, error stack:
internal_Isend(14962): MPI_Isend(buf=0x14e9b39bf010, count=-1872491208, MPI_CHAR, 0, 0, MPI_COMM_WORLD, request=0x31c108c0) failed
internal_Isend(14906): Negative count, value is -1872491208
"

BTW, the HSE calculations succeed for a small unit cell of AlN with 2 atoms only and a Si system with a bigger cell of  64 atoms.

Here I attach my calculation settings for your convenience. 

### Expected behavior

please find out the reason why it fails and fix it !!!

### To Reproduce

[aln_64_hse.tar.gz](https://github.com/deepmodeling/abacus-develop/files/12577069/aln_64_hse.tar.gz)

### Environment

image:
registry.dp.tech/deepmodeling/abacus-intel:latest

run command:
    "command": "OMP_NUM_THREADS=16 mpirun -np 1  abacus",

machine:
    "platform": "ali",
    "job_type": "container",
    "machine_type": "c64_m512_cpu",

the machine_type I have tried c32_m128_cpu  c32_m256_cpu and c64_m512_cpu. all failed!!!

### Task list for Issue attackers

- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [x] Steps to reproduce.
- [x] Expected behavior.
- [x] Error message.
- [x] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by PeizeLin** [comment]
The parameter `count` of `MPI_Isend()` is a variable of `int`.
For large systems, if the amount of data transmitted exceeds the upper limit of `int`, an error will occur.
The version of MPI>=4.0 provides another function `MPI_Isend_c()` replacing `MPI_Isend()` to fixe this error officially.

Unfortunately, the latest version of IntelMPI and OpenMPI only supports MPI 3.1.
So here are the suggestion:
1. [recommended] Change your MPI to the latest version of MPICH, which supports MPI 4.0.
2. Use more processes to reduce communication per process, i.e., `mpirun -np more`.
3. Waits for the update of LibRI. Perhaps LibRI will use another more complex alternative method to solve this problem in the future, but not now.
4. Waits for the update of IntelMPI and OpenMPI.

**Comment by PeizeLin** [comment]
The update of LibComm on 2023.11.01 has resolved this upper limit of `int`.

**Comment by hongriTianqi** [comment]
Good practice as it provides information on how to perform HSE calculation correctly.
