### ISSUE TITLE
We need remain the abacus codes in Dockerfile

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#2936]
### Details

We can remain the abacus codes in Dockefile, and so we can checkout to another branch to do some testing on that branch and avoid the download of abacus codes.

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers

- [X] Identify the specific section of the documentation with the issue.
- [X] Investigate the issue and determine the root cause.
- [X] Research best practices and potential solutions for the identified issue.
- [X] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by caic99** [comment]
@pxlxingliang I wonder why should we avoid the download of abacus codes?

**Comment by pxlxingliang** [comment]
> @pxlxingliang I wonder why should we avoid the download of abacus codes?

In testing, the downloading will waste some time, and the download may be failed from github.

**Comment by pxlxingliang** [comment]
@caic99 Besides, why do not remain the codes in the current Dockerfile?
