### ISSUE TITLE
How to do structure relaxation calculation using FIRE method

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#2949]
### Details

I want to do structure relaxation calculation using FIRE method. First, I reference the [documentation](https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#relax-method) and set the parameters like 

> calculation    relax
md_type           fire
...

But it appears to run with the default CG method. Then I change the parameters to

> calculation    [md](https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#md-type)
md_type           fire
...

It terminates with an error

>  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 temperature of MD calculation should be set!
 CHECK IN FILE : OUT.test/warning.log
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

So what is the proper use of the FIRE method for structure relaxation calculations? 

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers

- [X] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by YuLiu98** [comment]
FIRE is a relax method based on MD, so all the parameters that an MD run needs must be supplied as follows:
```
calculation md
md_type  fire
md_step  100
md_tfirst  300
md_dt     1.0
...
```

You can refer to the document in Chinese: [https://mcresearch.github.io/abacus-user-guide/abacus-md.html](https://mcresearch.github.io/abacus-user-guide/abacus-md.html)

**Comment by hongriTianqi** [comment]
[LiuXiaohui123321](https://github.com/LiuXiaohui123321) I believe the replies from @YuLiu98 have solved your issue?

**Comment by LiuXiaohui123321** [comment]
> FIRE is a relax method based on MD, so all the parameters that an MD run needs must be supplied as follows:
> 
> ```
> calculation md
> md_type  fire
> md_step  100
> md_tfirst  300
> md_dt     1.0
> ...
> ```
> 
> You can refer to the document in Chinese: https://mcresearch.github.io/abacus-user-guide/abacus-md.html

Thanks a lot! It works. Another question: Do I have to add _md_tfirst_ and _md_dt_ parameters when using the FIRE method? Will they actually be used in the FIRE algorithm? @dyzheng

**Comment by LiuXiaohui123321** [comment]
> [LiuXiaohui123321](https://github.com/LiuXiaohui123321) I believe the replies from @YuLiu98 have solved your issue?

Yes, thanks! And I have another question about input parameters of FIRE method, which maybe related to the algorithm itself. I have asked Daye. Thank you!

**Comment by dyzheng** [comment]
> > FIRE is a relax method based on MD, so all the parameters that an MD run needs must be supplied as follows:
> > ```
> > calculation md
> > md_type  fire
> > md_step  100
> > md_tfirst  300
> > md_dt     1.0
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can refer to the document in Chinese: https://mcresearch.github.io/abacus-user-guide/abacus-md.html
> 
> Thanks a lot! It works. Another question: Do I have to add _md_tfirst_ and _md_dt_ parameters when using the FIRE method? Will they actually be used in the FIRE algorithm? @dyzheng

Yes, these two parameters will be used, md_tfirst is used for initializing atomic velocities and md_dt is used for verlet algorithm to move atoms.

**Comment by LiuXiaohui123321** [comment]
> > > FIRE is a relax method based on MD, so all the parameters that an MD run needs must be supplied as follows:
> > > ```
> > > calculation md
> > > md_type  fire
> > > md_step  100
> > > md_tfirst  300
> > > md_dt     1.0
> > > ...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You can refer to the document in Chinese: https://mcresearch.github.io/abacus-user-guide/abacus-md.html
> > 
> > 
> > Thanks a lot! It works. Another question: Do I have to add _md_tfirst_ and _md_dt_ parameters when using the FIRE method? Will they actually be used in the FIRE algorithm? @dyzheng
> 
> Yes, these two parameters will be used, md_tfirst is used for initializing atomic velocities and md_dt is used for verlet algorithm to move atoms.

I see. Thank you!

**Comment by QuantumMisaka** [comment]
> FIRE is a relax method based on MD, so all the parameters that an MD run needs must be supplied as follows:
> 
> ```
> calculation md
> md_type  fire
> md_step  100
> md_tfirst  300
> md_dt     1.0
> ...
> ```
> 
> You can refer to the document in Chinese: https://mcresearch.github.io/abacus-user-guide/abacus-md.html

is `md_step`  parameter should be `md_nstep` now?

Also, is a complete tutorial for how to use FIRE method needed ?

**Comment by YuLiu98** [comment]
> > FIRE is a relax method based on MD, so all the parameters that an MD run needs must be supplied as follows:
> > ```
> > calculation md
> > md_type  fire
> > md_step  100
> > md_tfirst  300
> > md_dt     1.0
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can refer to the document in Chinese: https://mcresearch.github.io/abacus-user-guide/abacus-md.html
> 
> is `md_step` parameter should be `md_nstep` now?
> 
> Also, is a complete tutorial for how to use FIRE method needed ?

Yes, the parameter is `md_nstep` now.

Actually, there are no extra parameters for FIRE, so just use it as a normal MD method.
