### ISSUE TITLE
Unify numerical type template in PW calculation

### ISSUE THREAD

**Issue by denghuilu** [deepmodeling/abacus-develop#2951]
### Background

The usage of template parameters in ABACUS is relatively confusing. Here are a few examples:

- `complex<FPTYPE>` is used uniformly in PW code, that is, `FPYTPE` cannot take `complex<double>`;

- There is `complex<T>` in the DiagoBPCG written by @denghuilu, so `T` here cannot be `complex<double>` too;

- However: `T` in `HamiltonLCAO<T>` can be `complex<double>`; 

- And In the new `ESolver_LR` module, `FPTYPE` can also be `complex<double>`... 

### Describe the solution you'd like

In the PW calculation, we employ a unified numerical type template represented by 'T' instead of 'FPTYPE' to denote the calculation's numerical type. This 'T' template is designed to accommodate various data types, including 'std::complex<double>' and others.

### Task list for Issue attackers

- [x] Review and understand the proposed feature and its importance.
- [x] Research on the existing solutions and relevant research articles/resources.
- [x] Discuss with the team to evaluate the feasibility of implementing the feature.
- [x] Create a design document outlining the proposed solution and implementation details.
- [x] Get feedback from the team on the design document.
- [x] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by maki49** [comment]
#### What's the problem from my point of view
The usage of `std::complex<T>` everywhere in PW classes restricts the value of `T` in **base classes** to `float/double` , then both `std::complex<T> ops` and `T opsd` appears in **base class** `Hamilt`, so my new added `ESolver_LR`(for #2460 )fails to unify 2 types of operators as long as I use a `Hamilt*` pointer. 

#### What we will do
- @denghuilu will unify `std::complex<T>` into `T` in base and PW classes
- I will unify `opsd` and `psid` into `ops` and `psi` in base and LCAO classes
