### ISSUE TITLE
Print-out magnetism on atom in STRU_ION_D

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#2955]
### Background

When do spin-polarized calculation with magnetism moment guess, the print-out STRU_ION_D will continue to use the guessed magnetism moment, like:
```shell
ATOMIC_SPECIES
H 1.008 H_ONCV_PBE-1.0.upf upf201
C 12.011 C_ONCV_PBE-1.0.upf upf201
O 15.999 O_ONCV_PBE-1.0.upf upf201
Fe 55.845 Fe_ONCV_PBE-1.0.upf upf201

NUMERICAL_ORBITAL
H_gga_6au_100Ry_2s1p.orb
C_gga_7au_100Ry_2s2p1d.orb
O_gga_7au_100Ry_2s2p1d.orb
Fe_gga_8au_100Ry_4s2p2d1f.orb

LATTICE_CONSTANT
1.8897

LATTICE_VECTORS
    9.9798000000     0.0000000000     0.0000000000 #latvec1
   -0.7639580600    12.6617739300     0.0000000000 #latvec2
    0.0000000000     0.0000000000    19.6404000000 #latvec3

ATOMIC_POSITIONS
Direct

H #label
0 #magnetism
2 #number of atoms
    0.9748780890     0.1765557100     0.3928722820 m  1  1  1  mag   0.0
    0.4798338234     0.1763985619     0.4629391021 m  1  1  1  mag   0.0

C #label
0 #magnetism
37 #number of atoms
    0.0294436027     0.6901723374     0.0094617744 m  0  0  0  mag   0.0
    0.5294436027     0.6901723374     0.0094617744 m  0  0  0  mag   0.0
    0.2536654714     0.0891953642     0.0207979810 m  0  0  0  mag   0.0
    0.7536654714     0.0891953642     0.0207979810 m  0  0  0  mag   0.0
    ...
    0.2332043797     0.7689587001     0.1027031036 m  1  1  1  mag   0.0
    0.7330569920     0.7691542619     0.1030661532 m  1  1  1  mag   0.0
    0.0619544139     0.1762780158     0.1187911301 m  1  1  1  mag   0.0
    0.5618229984     0.1759934131     0.1187314558 m  1  1  1  mag   0.0
    0.9687512581     0.5692784047     0.1702548192 m  1  1  1  mag   0.0
    ...

O #label
0 #magnetism
1 #number of atoms
    0.6338877916     0.7800071177     0.4736449767 m  1  1  1  mag   0.0

Fe #label
2 #magnetism
80 #number of atoms
    0.1318042832     0.8125748305     0.0257891906 m  0  0  0  mag   0.0
    0.6318042832     0.8125748305     0.0257891906 m  0  0  0  mag   0.0
    0.2521515510     0.4194369418     0.0307366515 m  0  0  0  mag   0.0
    0.7521515510     0.4194369418     0.0307366515 m  0  0  0  mag   0.0
    0.1895552354     0.6185430252     0.0307951701 m  0  0  0  mag   0.0
   ...
    0.1416491516     0.8926446719     0.1374274725 m  1  1  1  mag   0.0
    0.6403682775     0.8918841492     0.1374725097 m  1  1  1  mag   0.0
    0.3597773083     0.4426604192     0.1405159957 m  1  1  1  mag   0.0
    0.8585233525     0.4421886978     0.1396457305 m  1  1  1  mag   0.0
    ...
```

And magnetism on atom of each ion step will be print-out in mulliken.txt like:
```shell
119                 Zeta of Fe                        Spin 1                        Spin 2                           Sum                          Diff
s                        0                          0.7565                         0.747                         1.504                      0.009538
  sum over m                                        0.7565                         0.747                              1.504                 0.009538
s                        1                          0.4924                        0.4613                        0.9537                       0.03104
  sum over m                                        0.4924                        0.4613                             0.9537                  0.03104
s                        2                         0.01175                       0.00828                       0.02003                      0.003471
  sum over m                                       0.01175                       0.00828                            0.02003                 0.003471
s                        3                       -0.001105                    -0.0006553                      -0.00176                    -0.0004495
  sum over m                                     -0.001105                    -0.0006553                           -0.00176               -0.0004495
  sum over m+zeta                                     1.26                         1.216                              2.475                   0.0436
...
Total Charge on atom:  Fe               15.76
Total Magnetism on atom:  Fe               2.394

```

One can get magnetism information by `grep Magnetism mulliken.txt | tail -n $NATOM`
But, if one directly use STRU_ION_D relaxation result to do next step like static calculation or NEB calculation, 
The calculated magnetism is hard to add one by one or by writing other scripts.

### Describe the solution you'd like

Print-out magnetism on atom in STRU_ION_D, specifically, add calculated magnetism result to the magnetism guess of each atom in  `mag   0.0` section , instead of use the initial guess

### Task list for Issue attackers

- [X] Review and understand the proposed feature and its importance.
- [X] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
@QuantumMisaka,
this issue has been solve by PR #3565
