### ISSUE TITLE
The HSE band-gap has a large difference to the experiment value

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#2956]
### Details

I have tested several semi-conductor systems by HSE, but the calculated band-gap has a large difference (large to 0.7-1.0 eV) to the HSE value in literature (10.1063/1.2085170) and experiment value. 

![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/2b43b773-53db-454c-870f-739bdc11c92d)

Detail calculations can be found in:  
https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.30-393b7b

### Task list for Issue attackers

- [x] Reproduce the performance issue on a similar system or environment.
- [x] Identify the specific section of the code causing the performance issue.
- [x] Investigate the issue and determine the root cause.
- [x] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by pxlxingliang** [comment]
The similar tests have been made by @PeizeLin in 10.1021/acs.jpclett.0c00481, the maximum difference of band gap calculated by ABACUS and other software (QE/VASP/AIMS) is about 0.5 eV. After compare the results from @PeizeLin, we found two mainly reasons, one is the implement of new two-center integrate at recently (2023-9-8), and the other one is that the structures are not exactly same. The structure used in my test are downloaded from material project, and have not do the relax, this may also lead to the error of band gap.
Next, I will calculate the band gap of structures from 10.1021/acs.jpclett.0c00481 by latest abacus codes and VASP.

**Comment by hongriTianqi** [comment]
@dyzheng do you have more comments?

**Comment by hongriTianqi** [comment]
@pxlxingliang Please update

**Comment by pxlxingliang** [comment]
Using the structures from 10.1021/acs.jpclett.0c00481, I calculated the band gap employing ABACUS HSE. Taking the average value of qe/vasp/fhi-aims as a reference, the band gap of ABACUS exhibits a variation of less than 20% for most materials. However, for InAs/InSb, ABACUS fails to provide accurate results, which may be related to the pseudopotential.

![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/6bb38827-a57e-47ad-8d39-3b19b0c2ddf8)

Detail of calculation can be found in [here](https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fsched-abacustest-sc-test-08bb50).

**Comment by dyzheng** [comment]
@kirk0830 the cases marked in red from table above should be taken into consideration.

**Comment by kirk0830** [comment]
update: https://ucoyxk075n.feishu.cn/docx/Azm0dl81JoL50jxMl1dcHJsknif

**Comment by kirk0830** [comment]
Has been solved, use PSLibrary 0.3.1 norm-conserving pseudopotential for In, combined with SG15-1.0 for N, P, As and Sb element can get partially reasonable result:


![Image](https://github.com/deepmodeling/abacus-develop/assets/67682086/a69be46b-0a71-4dda-bf92-3f5c17b837f6)

**Comment by hongriTianqi** [comment]
This issue has solve issue in a systematic way. So tagged with good practice.
