### ISSUE TITLE
`GlobalV::NLOCAL` is forever to be 9 multiplies number of atoms in PW calculation

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#2967]
### Details

I am checking code correctness of upcoming new psi initializer, while checking dimension of initialized psi, I find the GlobalV::NLOCAL is, (1+3+5)*natom, it is because when it is pw calculation, the maxial angular momentum number is supposed to be 2, therefore adding degeneracies of s, p and d, it is 9.
In global_variables.cpp this variable is, created for numbering number of local basis, but for now it may lose at least half of its functionality. 

Suggest give it the value of UnitCell::natomwfc or 0.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers

- [X] Understand the problem or question described by the user.
- [X] Check if the issue is a known problem or has been addressed in the documentation.
- [X] Test the issue or problem on a similar system or environment, if possible.
- [X] Identify the root cause or provide clarification on the user's question.
- [X] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
I have understood what the `GlobalV::NLOCAL` indicates in PW calculation, it is, sum of (2l + 1) for l from 0 to lmaxmax multiplied by number of atoms, the following lines are meaningless:
https://github.com/deepmodeling/abacus-develop/blob/8942b4776c99c2a3982467a365cda7ddf670fb1c/source/module_cell/read_atoms.cpp#L474-L477
This is because the lmaxmax will be 2 if not set:
https://github.com/deepmodeling/abacus-develop/blob/8942b4776c99c2a3982467a365cda7ddf670fb1c/source/module_cell/unitcell.cpp#L1307-L1316
https://github.com/deepmodeling/abacus-develop/blob/8942b4776c99c2a3982467a365cda7ddf670fb1c/source/module_io/input_conv.cpp#L305
https://github.com/deepmodeling/abacus-develop/blob/8942b4776c99c2a3982467a365cda7ddf670fb1c/source/module_io/input.cpp#L217
.
For PW calculation, the `l_nchi` is always 1, therefore the `GlobalV::NLOCAL` is sum of Ylm over all atoms.
Then `GlobalV::NLOCAL` will be used for allocating `<OVERLAP_Q>` and `<OVERLAP_Sq>`. The former will have dimension `GlobalV::NBANDS * GlobalV::NLOCAL * ne`, in which ne is the number of spherical bessel functions at present rcut (`bessel_nao_rcut`) and ecut (`ecutwfc`). Note that  `<OVERLAP_Q>` is overlap mo_jy, should in principle have dimension nbands * njY. Thus the dimension here means nbands * nYlm * nj = nbands * njy.
