### ISSUE TITLE
Feature/refactor: Re-enable the `basis_type lcao_in_pw` feature in recent version

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#2973]
### Background

I will try to enable the deprecated functionality `basis_type lcao_in_pw`, for cross validation with `basis_type lcao` calculation.
A short description of `lcao_in_pw`:
It contains following procedures:
1. expand numerical atomic orbitals on planewave, i.e., get Fourier transform of numerical atomic orbitals (naos) or say, project naos onto planewave basis, denoted as `wanf2`.
2. Diagonalize the Hamiltonian matrix in representation of naos, while for each nao, the operator actually acts on pw basis, which means `OperatorPW` derived class will be the one to use instead of `OperatorLCAO`, get eigenvector matrix.
3. Extract first nband(s) eigenvector and impose on `wanf2`, get one so called `psi`.
What is different with `basis_type pw` is the way of diagonalization:
`pw`: indirectly diagonalize nbasis * nbasis Hamiltonian matrix, coefficients of planewave basis will change flexibly
`lcao_in_pw`: directly diagonalize nlocal * nlocal Hamiltonian matrix, coefficients of planewave basis are somehow unchanged but linear re-combination will occur across bands

### Describe the solution you'd like

Only occupied bands will affect energy, in most cases observables will have little difference compared with `basis_type lcao` calculation.
I will find an appropiate place to insert codes.

### Task list for Issue attackers

- [X] Review and understand the proposed feature and its importance.
- [X] Research on the existing solutions and relevant research articles/resources.
- [X] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by hongriTianqi** [comment]
This is linked with #3057

**Comment by kirk0830** [comment]
PR #3057 has supported basic lcao in pw feature, while the nscf is still not supported yet. This issue is temporarily closed and will be reopen up to future demands
