### ISSUE TITLE
Request: Flexibly detect and read wavefunction file as init guess

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#2975]
### Background

In VASP, if WAVECAR file exists ,VASP can automatically read WAVECAR file as guess for wave-function
In ABACUS LCAO calculation ,one can set `out_wfc_lcao 1` and `init_wfc filename` to read wave-function calculation result, but one cannoe let ABACUS automatically read existing `wfc` files , or set `init_wfc file` and switch to atomic guess if this `wfc` files is not exists

This will be very good for ASE-ABACUS calculation like geometry optimization and NEB calculation

### Describe the solution you'd like

One of these solution will do good
1. ABACUS can detect a name of wavefunction file, and automatically read it
2. when `init_wfc` setting to `file`, ABACUS can read wavefunction from `file`, and, if `file` not exist, switch back to atomic guess of wave function

### Task list for Issue attackers

- [X] Review and understand the proposed feature and its importance.
- [X] Research on the existing solutions and relevant research articles/resources.
- [x] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by hongriTianqi** [comment]
This is in the same topic as #1235

**Comment by QuantumMisaka** [comment]
> This is in the same topic as #1235

Not the same at all, #1235 Targets is for reading `nscf` calculation, this issue is for ASE or other software which use ABACUS as calculator.

Also, I notice that ABACUS will read charge files first if have charge file? could ABACUS read charge AND wavefunction files for guess?

Also, is it possible for ABACUS to have initial guess partly read from file and partly by `atomic` or other initialization method ?

**Comment by QuantumMisaka** [comment]
The Best way to solve this problem is to switch back to default initial wavefunction guess when setting `init_wfc file` in INPUT but wavefunction file NOT exists. But ABACUS will shutdown calculation when  setting `init_wfc file` and file not exist. 

This change should be simple.
