### ISSUE TITLE
fail to build the unit tests 

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2984]
### Describe the Testing Issue

I am using intel oneapi toolchain, and I could build abacus3.3.4 normally, 
but when I tried to build the unit test on my pc, but I met some error like :
```
[ 17%] Linking CXX executable Container_Kernels_UTs
icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
icpc: command line warning #10148: option '-Wno-tautological-constant-compare' not supported
CMakeFiles/Container_Kernels_UTs.dir/blas_op_test.cpp.o:(.data._ZTIN9container2op10BlasOpTestISt5tupleIJfNS_10DEVICE_CPUEEEEE[_ZTIN9container2op10BlasOpTestISt5tupleIJfNS_10DEVICE_CPUEEEEE]+0x10): undefined reference to `typeinfo for testing::Test'
CMakeFiles/Container_Kernels_UTs.dir/blas_op_test.cpp.o:(.data._ZTIN9container2op10BlasOpTestISt5tupleIJdNS_10DEVICE_CPUEEEEE[_ZTIN9container2op10BlasOpTestISt5tupleIJdNS_10DEVICE_CPUEEEEE]+0x10): undefined reference to `typeinfo for testing::Test'
CMakeFiles/Container_Kernels_UTs.dir/blas_op_test.cpp.o:(.data._ZTIN9container2op10BlasOpTestISt5tupleIJSt7complexIfENS_10DEVICE_CPUEEEEE[_ZTIN9container2op10BlasOpTestISt5tupleIJSt7complexIfENS_10DEVICE_CPUEEEEE]+0x10): undefined reference to `typeinfo for testing::Test'
CMakeFiles/Container_Kernels_UTs.dir/blas_op_test.cpp.o:(.data._ZTIN9container2op10BlasOpTestISt5tupleIJSt7complexIdENS_10DEVICE_CPUEEEEE[_ZTIN9container2op10BlasOpTestISt5tupleIJSt7complexIdENS_10DEVICE_CPUEEEEE]+0x10): undefined reference to `typeinfo for testing::Test'
CMakeFiles/Container_Kernels_UTs.dir/lapack_op_test.cpp.o:(.data._ZTIN9container2op12LapackOpTestISt5tupleIJfNS_10DEVICE_CPUEEEEE[_ZTIN9container2op12LapackOpTestISt5tupleIJfNS_10DEVICE_CPUEEEEE]+0x10): undefined reference to `typeinfo for testing::Test'
CMakeFiles/Container_Kernels_UTs.dir/lapack_op_test.cpp.o:(.data._ZTIN9container2op12LapackOpTestISt5tupleIJdNS_10DEVICE_CPUEEEEE[_ZTIN9container2op12LapackOpTestISt5tupleIJdNS_10DEVICE_CPUEEEEE]+0x10): more undefined references to `typeinfo for testing::Test' follow
source/module_base/module_container/ATen/kernels/test/CMakeFiles/Container_Kernels_UTs.dir/build.make:310: recipe for target 'source/module_base/module_container/ATen/kernels/test/Container_Kernels_UTs' failed
make[2]: *** [source/module_base/module_container/ATen/kernels/test/Container_Kernels_UTs] Error 1
CMakeFiles/Makefile2:2859: recipe for target 'source/module_base/module_container/ATen/kernels/test/CMakeFiles/Container_Kernels_UTs.dir/all' failed
make[1]: *** [source/module_base/module_container/ATen/kernels/test/CMakeFiles/Container_Kernels_UTs.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
```
[build-unit-test-failure.log](https://github.com/deepmodeling/abacus-develop/files/12668662/build-unit-test-failure.log)

### Task list for Issue attackers

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [X] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by QuantumMisaka** [comment]
Hi @Satinelamp 
I have tried toolchain and add `-DBUILD_TEST=1` in build stage, the compilation can be done normally. 
I need more information about your ABACUS version, your PC OS and hardware and so on.
Also, the problem seems to be in `blas` and `lapack`, is this related to your intel-MKL version?

**Comment by Satinelamp** [comment]
ABACUS 3.3.4
Intel oneAPI: l_BaseKit_p_2021.4.0.3422_offline.sh  l_HPCKit_p_2021.4.0.3347_offline.sh

(base) alma@DESKTOP-8EH3B7O:~$ uname -a
Linux DESKTOP-8EH3B7O 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
(base) alma@DESKTOP-8EH3B7O:~$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
stepping        : 10
microcode       : 0xffffffff
cpu MHz         : 2591.998
cache size      : 12288 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 21
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves flush_l1d arch_capabilities
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds mmio_stale_data retbleed
bogomips        : 5183.99
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

**Comment by QuantumMisaka** [comment]
@Satinelamp Were you build ABACUS in WSL2 environments? the CPU seems like a PC

**Comment by Satinelamp** [comment]
@QuantumMisaka Yes

**Comment by hongriTianqi** [comment]
@Satinelamp Does this issue still exits?

**Comment by QuantumMisaka** [comment]
@Satinelamp  In my WSL2 on Windows10 on AMD-3950X platform, simply add `DBUILD_TEST=1` is doing well. I think the problem lies in your intel-OneAPI installation. Would you like to try
1. `rm -rf /path/to/abacus_repo/build_abacus` and build again by using toolchain
2. build again by gcc-toolchain
3. try to build abacus 3.4.0
4. re-install intel-OneAPI and re-build abacus

**Comment by Satinelamp** [comment]
The reason is missing `googletest` library in WSL, using `sudo apt install googletest` would solve this issue.
