### ISSUE TITLE
Bug: undefined behavior may be trigger when initializing charge

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#2993]
### Describe the bug

please see:
source/module_elecstate/module_charge/charge_init.cpp: line 205
If pseudopotential used does not have noncolinear correction, garbage values will be in `vg` and will be copied into `rhog_core` array and FFT to `rho_core` array, is it right? If so, the value will depend on compilation environment.

### Expected behavior

At least zero `vg` out if nlcc is not present

### Task list for Issue attackers

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [X] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
the whole function will first find if there really exists element with nlcc, if not, will return, else continue. Therefore the undefined behavior is avoided not by zero-out but use "one part" to skip "another part".
