### ISSUE TITLE
output charge density at a specified timepoint during tddft simulation

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2996]
### Background

I'd like to output the charge density at t=0s t=10fs t= 50fs, during the molecular dynamics simulation or TDDFT simulations.
but currently setting `out_chg = 1` could only output charge density at the last step of MD simulation. 

### Describe the solution you'd like

provide options to output charge density at a specified time point

### Task list for Issue attackers

- [X] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [X] Develop the feature following the agreed design.
- [X] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by lyb9812** [comment]
This function is not supported in md/tddft now. But you can use "restart" temporarily. For example, run  a 10 fs md/tddft calculation and obtain the charge density at t=10fs , then use "restart" to do a 40 fs md/tddft  calculation.
