### ISSUE TITLE
Wrong result and low efficiency of integrated test 108_PW_RE_NEW with SG15 pseudopotential

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3042]
### Describe the bug

test report here: https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.40-e290cc
When I was trying to validate change of refactored codes, I find this bug.
Three kinds of pseudopotentials are used:
dojo: scalar relativistic, norm-conserving, from pseudojo, version 0.5
oncv: SG15, provided in tests/PP_ORB
pd04: original set pseudopotential

### Task list for Issue attackers

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [X] Steps to reproduce.
- [X] Expected behavior.
- [X] Error message.
- [X] Environment details.
- [x] Additional context.
- [x] Assign a priority level (low, medium, high, urgent).
- [x] Assign the issue to a team member.
- [x] Label the issue with relevant tags.
- [x] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by kirk0830** [comment]
I have tested qe with similar parameters, find SG15 pseudopotential also yields crazy results and confusing performance:
[oncv.log](https://github.com/deepmodeling/abacus-develop/files/12755794/oncv.log)
[pd04.log](https://github.com/deepmodeling/abacus-develop/files/12755795/pd04.log)
[dojo.log](https://github.com/deepmodeling/abacus-develop/files/12755796/dojo.log)
May be better inform other users of avoiding using SG15 pseudopotential for at least Al
