### ISSUE TITLE
Request for support Quasiatomic orbitals (QO) analysis in ABACUS

### ISSUE THREAD

**Issue by QG-phy** [deepmodeling/abacus-develop#3063]
### Background

Quasiatomic orbitals （QO）is a method to produce minimal-basis TB Hamiltonian from ab initio calculations. Compared to Wannier, the basis in QO is quite close to atomic orbitals which will still approximately host the symmetry of atomic orbitals. 

The most important property of QO is that it retains all electronic structure information below a certain energy threshold while possessing both **quasi-angular momentum quantum number** and reasonably good localization, which fulfills the true spirit of the LCAO of Slater and Koster.

### Describe the solution you'd like

support the QO  method.

### Task list for Issue attackers

- [x] Review and understand the proposed feature and its importance.
- [x] Research on the existing solutions and relevant research articles/resources.
- [x] Discuss with the team to evaluate the feasibility of implementing the feature.
- [x] Create a design document outlining the proposed solution and implementation details.
- [x] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
issue #3062 will fix this.
