### ISSUE TITLE
URGENT: Inconsistent stress and force calculated by ABACUS and QE, resulting different even unreasonable structures

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3070]
### Describe the bug

Combining with previous issues #2974 #3002 , a high-throughput calculation reports maybe-unreliable result produced by ABACUS's cell relax function:
![img_v2_1df2ec85-3699-4f65-905f-f8d353c065ag](https://github.com/deepmodeling/abacus-develop/assets/67682086/21e4faac-3e35-4f8b-aa90-f53cda55d721)
x: ratio between final and initial volume of cell
y: ratio between the maxial volume during relaxation and initial volume of cell
One of examples, the alloy Li-Rh, its cell-relax calculation is tested for illustration. Starting structure is shown in following:
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/b4f96e36-24ec-4238-bfff-82853bd0111e)
For the first estimations of stress tensors and forces calculated by QE and ABACUS, they are:
QE:
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/b55f9644-2d38-4467-bd83-b374c8413be2)
ABACUS:
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/94065e78-9df5-4fdf-a4c9-7b88ae6c4e07)
, seems ABACUS deviates too much.
Input scripts and outputs are provided below, for this is a fundamental function, I suggest solve it ASAP.

### Expected behavior

At least keep consistencies on stress and forces calculation results on identical structure between ABACUS and QE.

### To Reproduce

Keeping identical pseudpotential files used, disabled DFT-D3 correction, ABACUS input script:
[abacustest-vcrelax-LiRh.zip](https://github.com/deepmodeling/abacus-develop/files/12923977/abacustest-vcrelax-LiRh.zip)
QE:
[qetest-vcrelax-LiRh.zip](https://github.com/deepmodeling/abacus-develop/files/12923955/qetest-vcrelax-LiRh.zip)

### Environment

Any

### Task list for Issue attackers

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [X] Steps to reproduce.
- [X] Expected behavior.
- [X] Error message.
- [X] Environment details.
- [X] Additional context.
- [X] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [x] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
When you mentioned that "stress and force inconsistent", it suggested the energy is consistent. 
But the energy is not consistent between ABACUS and QE : "ABACUS: -718.943 Ry ; QE:  -718.182 Ry".
Please check the reason of energy inconsistent first.

**Comment by dyzheng** [comment]
I tested the case with k-points 2*2*2 to accelerate the calculation.
Energy of ABACUS is -718.137 Ry with setting "symmetry 0" and  -718.895 Ry with setting "symmetry 1".
Energy of QE is -718.137 Ry with/without setting "nosym = .FALSE.".

**Comment by dyzheng** [comment]
> I tested the case with k-points 2_2_2 to accelerate the calculation. Energy of ABACUS is -718.137 Ry with setting "symmetry 0" and -718.895 Ry with setting "symmetry 1". Energy of QE is -718.137 Ry with/without setting "nosym = .FALSE.".

Result of ABACUS is correct before #1904 , and turn to error ever since. 
@maki49 can you help for this Issue?

**Comment by maki49** [comment]
> Result of ABACUS is correct before #1904 , and turn to error ever since. @maki49 can you help for this Issue?

I've reproduced your result. It's the same problem as #2608: If charge density symmetrization is done in real space as default, the results are wrong; if it's done in reciprocal space, the results are right. 
In QE,  only **reciprocal space** charge density symmetrization is supported. 

Now I have no better idea to fix the real-space symmetrization, my current suggestion is to do the charge density symmetrization in reciprocal space in any case like what QE does. (#3081 )

 (Notice: I have never changed the real-space symmetrization algorithm, the right result before #1904 is because the symmetry analysis is incomplete.)

**Comment by dyzheng** [comment]
Thank for your reply, will the symmetry algorithm in ABACUS be completely consistent with QE after #3081? @maki49

**Comment by maki49** [comment]
> Thank for your reply, will the symmetry algorithm in ABACUS be completely consistent with QE after #3081? @maki49

Not really.
The "symmetry analysis" algorithm is consistent with VASP, sometimes finding more symmetry operations (leading to fewer IBZ-k-points) than QE. 
The “charge density symmetrization” algorithm is consistent with QE then, while VASP supports real-space symmetrization for pure point groups.

**Comment by pxlxingliang** [comment]
I plane to build a test suite for symmetry and use the energy/force/stress of symmetry=0 as the reference. Will check the energy difference (ED), maximum absolute difference of force (MADF), and maximum absolute difference of stress (MADS). How should I set the criteria? @maki49 @dyzheng  
How about:
ED: < 1e-8 eV
MADF: < 1e-6 eV/A (the valid digits output in the log are 8 digits)
MADS: < 1e-4 kbar (the valid digits output in the log are 6 digits)

![image](https://github.com/deepmodeling/abacus-develop/assets/91927439/6a6e9977-cc9e-4f81-9b4f-6a4d518cda09)

**Comment by maki49** [comment]
> I plane to build a test suite for symmetry and use the energy/force/stress of symmetry=0 as the reference. Will check the energy difference (ED), maximum absolute difference of force (MADF), and maximum absolute difference of stress (MADS). How should I set the criteria? @maki49 @dyzheng How about: ED: < 1e-8 eV MADF: < 1e-6 eV/A (the valid digits output in the log are 8 digits) MADS: < 1e-4 kbar (the valid digits output in the log are 6 digits)

It's normal that symmetry=0 and 1 give slightly different energy (sometimes1e-3 Ry) due to the charge density symmetrization, and it may depends on `ecutwfc` and `scf_thr`. Here are some results I've tested before: https://xmywuqhxb0.feishu.cn/docx/MAAadv569onfU0xtbc5cEFwjnRh?from=from_copylink

**Comment by kirk0830** [comment]
Status update: this issue now is assigned to @Cstandardlib now.
