### ISSUE TITLE
Confusing population results calculated on di-Sulfur (S2) system

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3073]
### Describe the bug

only switch off smearing, total number of electrons are turned out to be different in `running_scf.log` file  
with smearing:  
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/a3a650b5-f6a8-40c5-9aa0-e4be7258dedb)
without smearing:  
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/3fd4f689-1ae1-46e7-ad72-9418bc7bbaa0)

### To Reproduce

[disulfur.zip](https://github.com/deepmodeling/abacus-develop/files/12927514/disulfur.zip)

### Task list for Issue attackers

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [X] Steps to reproduce.
- [X] Expected behavior.
- [X] Error message.
- [X] Environment details.
- [X] Additional context.
- [x] Assign a priority level (low, medium, high, urgent).
- [x] Assign the issue to a team member.
- [x] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by Qianruipku** [comment]
Smearing can not be turned off. In fact, you are using "fixed" smearing.
[https://abacus.deepmodeling.com/en/latest/advanced/input_files/input-main.html#smearing-method](url)
![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/bd454f7e-924b-41f5-90a2-d0f835dab757)
"Fixed" smearing is only available for non-conductors.
QE:
![image](https://github.com/deepmodeling/abacus-develop/assets/76200646/16709340-f502-4a91-a64a-c651425059b5)

**Comment by Qianruipku** [comment]
Wrong number of electrons is a bug

**Comment by hongriTianqi** [comment]
Has this issue not been solved @Qianruipku
