### ISSUE TITLE
Interface testing with other third-party software is required

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3117]
### Describe the Testing Issue

Currently, some software already supports post-processing of ABACUS. In the development process of ABACUS, we need some automated testing to detect whether these interfaces are available.
The test examples are needed to set the automated testing in abacustest (https://labs.dp.tech/projects/abacustest/).
These tests will be automated running on each Wednesday, and the results will be reported on https://deepmodeling-activity.github.io/abacus-test.github.io/index.html?pname=performance.
Including the interface to (https://abacus.deepmodeling.com/en/latest/advanced/interface/index.html):
- [ ] deepks
- [x] dpgen/dpdata
- [ ] deepH
- [ ] Hefei-NAMD
- [x] Phonopy
- [x] Wannier90
- [x] ASE
- [ ] PYATB
- [ ] ShengBTE
- [ ] CANDELA

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by pxlxingliang** [comment]
To prepare a test for one interface, we need the below steps:
1. prepare a bohrium image, which has installed the interface, and can run the interface successfully.
2. prepare a bash script run.sh for running interface tests and determining whether the results after testing are correct.

@dyzheng @mohanchen would you help to contact the related interface developer to prepare the image and scripts?
