### ISSUE TITLE
Q: Confusing Largest Gradient output

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#3147]
### Details

Example:

[MgO_cell-relax.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13247742/MgO_cell-relax.tar.gz)

If one wants to acquire max force for this cell-relax example from the print-out, one can
```
(ase-abacus) [2201110432@wm2-login01 bfgs]$ grep GRAD abacus.out 
 LARGEST GRAD (eV/A)  : 8.620e+00
 LARGEST GRAD (eV/A)  : 5.343e+00
 LARGEST GRAD (eV/A)  : 2.629e+00
 LARGEST GRAD (eV/A)  : 7.056e-01
 LARGEST GRAD (eV/A)  : 4.415e-01
 LARGEST GRAD (eV/A)  : 2.256e-01
 LARGEST GRAD (eV/A)  : 5.560e-02
 LARGEST GRAD (eV/A)  : 3.316e-02
 LARGEST GRAD (eV/A)  : 3.335e-02
 LARGEST GRAD (eV/A)  : 3.335e-02
 LARGEST GRAD (eV/A)  : 3.431e-02
 LARGEST GRAD (eV/A)  : 3.981e-02
 LARGEST GRAD (eV/A)  : 4.570e-02
 LARGEST GRAD (eV/A)  : 3.262e-02
 LARGEST GRAD (eV/A)  : 4.475e-02
```

However, In `running_cell-relax.log` of BFGS
```
(ase-abacus) [2201110432@wm2-login01 MgO_cell-relax]$ grep gradient bfgs/OUT.ABACUS/running_cell-relax.log 
 Largest gradient is (eV/A) = 0.0331644
 Largest gradient is (eV/A) = 0.0333478
 Largest gradient is (eV/A) = 0.0333494
 Largest gradient is (eV/A) = 0.0343104
 Largest gradient is (eV/A) = 0.0398053
 Largest gradient is (eV/A) = 0.0456952
 Largest gradient is (eV/A) = 0.0326184
 Largest gradient is (eV/A) = 0.0447477
 Largest gradient is = 2.69685
```

In `running_cell-relax.log` of CG:
```
(ase-abacus) [2201110432@wm2-login01 MgO_cell-relax]$ grep gradient cg/OUT.ABACUS/running_cell-relax.log 
 Largest gradient in stress is 284.632
 Largest gradient in stress is 211.508
 Largest gradient in stress is 207.759
 Largest gradient in stress is 103.667
 Largest gradient in stress is 105.018
 Largest gradient in stress is 40.2788
 Largest gradient in stress is 45.4695
 Largest gradient in stress is 28.8599
 Largest gradient in stress is 31.1511
 Largest gradient in stress is 8.33624
 Largest gradient in stress is 9.10066
 Largest gradient in stress is 2.85364
```
It cost myself a lot of time to realize that the `Largest gradient` in `running_cell-relax.log` of BFGS is on force for each finished relax job, but not for each ion step. And the last output is on stress for finished cell-relax job. While the `Largest gradient` in `running_cell-relax.log` of CG is on stress for each finished relax job. 

The Largest Gradient output is very confusing and need to be unified. 

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [X] Understand the problem or question described by the user.
- [X] Check if the issue is a known problem or has been addressed in the documentation.
- [X] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by QuantumMisaka** [comment]
Also, Largest Gradient is directly using the value of calculation result, but the proper way is to use the modulo, which is correspondent to real force and virial. This problem is also mentioned in https://github.com/deepmodeling/abacus-develop/issues/3111
