### ISSUE TITLE
Abnormal energies in y direction  for an isotropic magnetic system in non collinear calculation

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3154]
### Describe the bug

The system is just an Fe atom in a big box. When performing non collinear calculation, the energies when magnetic moments points to y direction are different from that in x and z directions.

### x direction results:
<img width="649" alt="x" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/ad82a3cb-8cfc-4a29-acac-15e22847c51f">

### y direction results
<img width="649" alt="y" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/a74d44d4-a9bb-48b2-b086-f302e5d82a75">

### z direction results
<img width="649" alt="z" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/279f933b-6aef-462b-8511-360fbb70b278">

### Expected behavior

The results on y direction should be exactly the same as in x and z directions. Only one scf step were run for each direction.

### To Reproduce
[nc.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13257957/nc.tar.gz)

### Task list for Issue attackers (only for developers)

- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [x] Steps to reproduce.
- [x] Expected behavior.
- [x] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [x] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [x] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
This is fixed in #3163.

### Y direction results:
<img width="601" alt="截屏2023-11-06 16 11 09" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/bd176890-d9d8-4677-9f6a-e47a9279f5f2">

**Comment by hongriTianqi** [comment]
This issue designs simple benchmark test cases to debug, so is good practice.
