### ISSUE TITLE
New tools in container module HContainer

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#3161]
### Background

There are three new features should be implemented in HContainer module for  future development:
1. HContainer can use existed array as its data memory rather than allocate them by itself, I name this mode as "wrapper" and will implement related code in module_hcontainer. (At the same time, In BaseMatrix, the "memory_type" and "ldc" is designed in order to expand the data storage and access formats supported by the module. But in actual implementation of Hamiltonian module, this design is useless but only costs. It will be replaced by wrapper mode.)
2. Tool for outputting data in HContainer has been implemented for no MPI case, the MPI case will be implemented later. 
3. Tool for reading data in HContainer has been implemented for no MPI case, the MPI case will be implemented later.

### Describe the solution you'd like

The related document is https://dptechnology.feishu.cn/docx/KSPvdYGmPoktgwxHdRhcVdpwnig .

The related PR will be raised soon.

### Task list only for developers

- [X] Notice possible changes of behavior
- [X] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [X] Review and understand the proposed feature and its importance.
- [X] Research on the existing solutions and relevant research articles/resources.
- [X] Discuss with the team to evaluate the feasibility of implementing the feature.
- [X] Create a design document outlining the proposed solution and implementation details.
- [X] Get feedback from the team on the design document.
- [X] Develop the feature following the agreed design.
- [X] Write unit tests and integration tests for the feature.
- [X] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.
