### ISSUE TITLE
Abnormal energies in z direction for an isotropic magnetic system in non collinear calculation with soc

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3170]
### Describe the bug

The system is BCC Fe. I performed NC+SOC calculation with starting mag moments in x, y, and z directions. The results come as:
```
ground_stateX/OUT.ABACUS/running_scf.log: !FINAL_ETOT_IS -6817.996537401447 eV
ground_stateY/OUT.ABACUS/running_scf.log: !FINAL_ETOT_IS -6817.996537402879 eV
ground_stateZ/OUT.ABACUS/running_scf.log: !FINAL_ETOT_IS -6817.996142674576 eV
```
the magnetimc moment results:
```
ground_stateX/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (3.62, 0, 0)
ground_stateX/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (3.62, 0, 0)
ground_stateY/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (0, 3.62, 0)
ground_stateY/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (0, 3.62, 0)
ground_stateZ/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (0, 0, 3.621)
ground_stateZ/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (0, 0, 3.621)
```

### Expected behavior

The results on different directions are assumed to be exactly the same for this isotropic magnetic system.

### To Reproduce

[issue_soc.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13277938/issue_soc.tar.gz)

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [X] Steps to reproduce.
- [X] Expected behavior.
- [X] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [x] Assign a priority level (low, medium, high, urgent).
- [x] Assign the issue to a team member.
- [x] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
### details of energy terms

<img width="555" alt="ff" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/892e6bda-178e-4a28-97d5-23248a727e62">

**Comment by hongriTianqi** [comment]
By using exactly the same inputs, but set `lspinorb false`, the results are isotropic:
```
ground_stateX/OUT.ABACUS/running_scf.log: !FINAL_ETOT_IS -6817.853714332487 eV
ground_stateY/OUT.ABACUS/running_scf.log: !FINAL_ETOT_IS -6817.853714333552 eV
ground_stateZ/OUT.ABACUS/running_scf.log: !FINAL_ETOT_IS -6817.853714333698 eV
``` 
Mag results:
```
ground_stateX/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (3.625, 0, 0)
ground_stateX/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (3.625, 0, 0)
ground_stateY/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (0, 3.625, 0)
ground_stateY/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (0, 3.625, 0)
ground_stateZ/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (0, 0, 3.625)
ground_stateZ/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (0, 0, 3.625)
```

**Comment by hongriTianqi** [comment]
[results.zip](https://github.com/deepmodeling/abacus-develop/files/13278402/results.zip)

**Comment by hongriTianqi** [comment]
I think this issue is related to #2290.

**Comment by hongriTianqi** [comment]
This will be fixed by a pr, the results becomes:
```
ground_stateX/OUT.ABACUS/running_scf.log: !FINAL_ETOT_IS -6817.996537401447 eV
ground_stateY/OUT.ABACUS/running_scf.log: !FINAL_ETOT_IS -6817.996537402879 eV
ground_stateZ/OUT.ABACUS/running_scf.log: !FINAL_ETOT_IS -6817.996537402360 eV
```
The cause of this issue is inside `source/module_elecstate/module_charge/charge_mixing.cpp`
```
  for (int is = 0; is < GlobalV::NSPIN; ++is)
    {
        if (is == 0 || is == 3 || !GlobalV::DOMAG_Z)
        {
            double* rho123_is = rho123.data() + is * nrxx;
#ifdef _OPENMP
#pragma omp parallel for schedule(static, 512)
#endif
            for(int ir = 0 ; ir < nrxx ; ++ir)
            {
                chr->rho_save[is][ir] = rho123_is[ir];
            }
        }
    }
```

for x, y directions, `GlobalV::DOMAG_Z` is false, but for z direction `GlobalV::DOMAG_Z` is true, which results in inconsistency of rho_save between z and xy directions. Then the E_descf is different between scf steps.

**Comment by hongriTianqi** [comment]
The magnetic moments also become exactly the same in NC + SOC computation:
```
ground_stateX/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (3.62, 0, 0)
ground_stateX/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (3.62, 0, 0)
ground_stateY/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (0, 3.62, 0)
ground_stateY/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (0, 3.62, 0)
ground_stateZ/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (0, 0, 3.62)
ground_stateZ/OUT.ABACUS/mulliken.txt:Total Magnetism on atom:  Fe                   (0, 0, 3.62)
```

**Comment by hongriTianqi** [comment]
This issue designs simple benchmark test cases to debug, so is good practice.
