### ISSUE TITLE
Fix some compilation warnings with Intel compilers

### ISSUE THREAD

**Issue by denghuilu** [deepmodeling/abacus-develop#3174]
### Describe the Code Quality Issue

Solve some warnings related to intel compilers

### Task list for Issue attackers (only for developers)

- [X] Identify the specific code file or section with the code quality issue.
- [X] Investigate the issue and determine the root cause.
- [X] Research best practices and potential solutions for the identified issue.
- [X] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by denghuilu** [comment]
While compiling [wf_atomic.cpp](https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_hamilt_pw/hamilt_pwdft/wf_atomic.cpp) with icpx:
![cf0b1d83-804e-4608-8747-a89eeb624af6](https://github.com/deepmodeling/abacus-develop/assets/21070560/29402f69-25dc-44d9-80e8-3dc3bc23e614)
