### ISSUE TITLE
Problems met in constraining magnetic moments in non-collinear calculation with soc

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3183]
### Describe the bug

The calculation is ok when one wants to constrain magnetic moment values in x, y, and z directions.
<img width="812" alt="gg (1)" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/24c8d16d-0291-47f9-b080-ac86fff07ae1">

Problem happens when constraining magnetic moment values in an arbitrary direction:
<img width="1630" alt="ff" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/55be6e40-9ec6-4ecf-863a-05c5b597a38f">

There are two problems:
- several calculations were not converged.
- with the converged two cases, the ground state energy and magnetic moments are inconsistent with that in x,y,z directions.

### Expected behavior

The performance should be exactly the same when one wants to constrain magnetic moments in arbitrary direction compared to x,y,z directions.

### To Reproduce

[repeat.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13306283/repeat.tar.gz)
[arbitraryDirection.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13306286/arbitraryDirection.tar.gz)

### Task list for Issue attackers (only for developers)

- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [x] Steps to reproduce.
- [x] Expected behavior.
- [x] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [x] Assign a priority level (low, medium, high, urgent).
- [x] Assign the issue to a team member.
- [x] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
This is related to soc problem as mentioned in #2290

**Comment by hongriTianqi** [comment]
This is also related to ISSUE #3130

**Comment by hongriTianqi** [comment]
To update, new tests are made with the following parameters:
```
smearing_method gauss
smearing_sigma  0.0037
mixing_angle   1.0
mixing_beta 0.2
mixing_beta_mag 1.0
```

for x direction constraining: https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.112-29ddba

4/7 get converged results.


for arbitrary constraining: https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.110-189769

4/7 get converged results.

Another test for the arbitrary direction constraining:
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.110-379878

2/7 get converged results.
with input paramters of:
```
smearing_method gauss
smearing_sigma  0.0037
mixing_beta     0.1
mixing_ndim     15
```
