### ISSUE TITLE
Build conda abacus with openmp support

### ISSUE THREAD

**Issue by Fadelis98** [deepmodeling/abacus-develop#3201]
### Details

The conda version of abacus now using the openblas that do not support openmp parallel, this can be easily improved by using the openmp branch of conda-forge/libopenblas. See https://github.com/conda-forge/openblas-feedstock/issues/79

In brief, replace the requirement of default libopenblas by libopenblas=*=*openmp* in conda profile.

### Task list for Issue attackers (only for developers)

- [X] Reproduce the performance issue on a similar system or environment.
- [X] Identify the specific section of the code causing the performance issue.
- [X] Investigate the issue and determine the root cause.
- [X] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [X] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by caic99** [comment]
@Fadelis98 Thanks! Contribution to [conda recipe](https://github.com/conda-forge/abacus-feedstock/blob/main/recipe/meta.yaml) is welcomed.

**Comment by njzjz** [comment]
The current recipe has not forced one to use either pthread or openmp version of openblas. Users can install what they like and there should be no conflict.

**Comment by Fadelis98** [comment]
> The current recipe has not forced one to use either pthread or openmp version of openblas. Users can install what they like and there should be no conflict.

Sry I'm not so familiar with pthread. The problem here is that if the openmp version of openblas is not installed, the openmp parallel of abacus cannot be used as well.

If I run `OMP_NUM_THREADS=x mpirun -np y abacus` with x>1, openblas raise warning repeatedly:
```
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
```

**Comment by caic99** [comment]
> > The current recipe has not forced one to use either pthread or openmp version of openblas. Users can install what they like and there should be no conflict.
> 
> Sry I'm not so familiar with pthread. The problem here is that if the openmp version of openblas is not installed, the openmp parallel of abacus cannot be used as well.
> 
> If I run `OMP_NUM_THREADS=x mpirun -np y abacus` with x>1, openblas raise warning repeatedly:
> 
> ```
> OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
> ```

The default install variation for OpenBLAS is `pthreads`.

**Comment by Fadelis98** [comment]
> > > The current recipe has not forced one to use either pthread or openmp version of openblas. Users can install what they like and there should be no conflict.
> > 
> > 
> > Sry I'm not so familiar with pthread. The problem here is that if the openmp version of openblas is not installed, the openmp parallel of abacus cannot be used as well.
> > If I run `OMP_NUM_THREADS=x mpirun -np y abacus` with x>1, openblas raise warning repeatedly:
> > ```
> > OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
> > ```
> 
> The default install variation for OpenBLAS is `pthreads`.

I am a little bit confused. Do you mean that abacus only use openmp in openblas, and the other part of the programme will not be limited if openmp is diabled?

**Comment by njzjz** [comment]
The default OpenBLAS variant is controlled by the `conda-forge/libopenblas` recipe, not by us.

The warning happens when OpenBLAS is used within an OpenMP loop. In this situation, the thread of OpenBLAS should be set to 1 either by using the environment variable or implicitly calling `openblas_set_num_threads(1)` in the application, per https://github.com/OpenMathLib/OpenBLAS/blob/develop/USAGE.md#how-can-i-use-openblas-in-multi-threaded-applications.

**Comment by caic99** [comment]
To avoid this, one can install `blas=*=mkl` or `libopenblas=*=openmp`.

**Comment by denghuilu** [comment]
This issue has now been resolved and I am closing it. If there is a need for further discussion or if related issues arise in the future, please feel free to reopen this issue.
