### ISSUE TITLE
Differences in memory consumption between version 3.4.0 & 3.4.2

### ISSUE THREAD

**Issue by zhangzju** [deepmodeling/abacus-develop#3206]
### Details

Details
Hi developers, I observed significant differences in memory consumption when performing the same calculations using different versions of abacus in similar environments.

Specifically, when I use version 3.4.0 of abacus, the memory consumption of all calculation processes is relatively stable and not high. When the number of processes is 32 (equal to the number of CPU cores), the average memory consumption is around 1.2GB. However, when I run the desired calculation with version 3.4.2 of abacus, this value keeps increasing and reaches around 3GB at generation 13. Finally, around generation 23, the process exits abnormally due to insufficient RSS. Related pics are as follows:

Detail version
Normal Commit: https://github.com/abacusmodeling/abacus-develop/commit/923b69739f3abc8c921996ae6ff987d26925e393 (Wed Oct 4 08:03:06 2023 +0800)
Abnormal Commit: https://github.com/abacusmodeling/abacus-develop/commit/7670bb097202a43c3fc2c799a08098ebaf912f5a (Mon Nov 13 14:24:03 2023 +0800)

Result in 3.4.0
![image](https://user-images.githubusercontent.com/10091715/282689725-6f6dd1d7-3735-4260-bee1-879791aaa9cc.png)

RSS in 3.4.0:
![image](https://user-images.githubusercontent.com/10091715/282689777-402dd202-f429-4ddc-851d-71ee9844cea6.png)

Result in 3.4.2:
![image](https://user-images.githubusercontent.com/10091715/282689812-3de773a4-de90-4210-8e13-11606fd8fa3f.png)

RSS in 3.4.2:
![image](https://user-images.githubusercontent.com/10091715/282689855-7c9fb3f9-d75e-4693-ba4d-760ce88853f9.png)

Enviroment information(32c 128g):
![image](https://user-images.githubusercontent.com/10091715/282689901-90d13bfc-6c4c-4d9d-841b-d615fb943e90.png)
![image](https://user-images.githubusercontent.com/10091715/282689951-88e710c5-d149-46ed-a1b1-49e97b787a99.png)

### Task list for Issue attackers (only for developers)

- [X] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [X] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [X] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by caic99** [comment]
@zhangzju Many thanks!
@sunml99 Would you provide the input files of this test case?

**Comment by caic99** [comment]
@hongriTianqi FYI: this issue is encountered by @sunml99 on Bohrium cloud platform. OOM happenes more usual than the earlier version. Our collaborator from Volce Engine @zhangzju helped to reproduce the error and test among releases.

**Comment by zhangzju** [comment]
here is my reproduce step:
[test.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13348601/test.tar.gz)

1. unzip test input file.
tar zxvf test.tar.gz -C /tmp/test
2. go to test dir and run with abacus.
cd /tmp/test/ && ulimit -s unlimited && mpirun -np 32 [abacus]

**Comment by hongriTianqi** [comment]
@zhangzju @sunml99 
This case is successful now with the latest intel image (abacus-intel:latest), below log:
```
                              ABACUS v3.4.3

               Atomic-orbital Based Ab-initio Computation at UStc                    

                     Website: http://abacus.ustc.edu.cn/                             
               Documentation: https://abacus.deepmodeling.com/                       
                  Repository: https://github.com/abacusmodeling/abacus-develop       
                              https://github.com/deepmodeling/abacus-develop         
                      Commit: baccbe3 (Fri Nov 17 22:22:05 2023 +0800)

 Tue Nov 21 17:03:39 2023
 MAKE THE DIR         : OUT.ABACUS/
 RUNNING WITH DEVICE  : CPU / Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 Warning: the number of valence electrons in pseudopotential > 10 for Pt: [Xe] 4f14 5d9 6s1
 Pseudopotentials with additional electrons can yield (more) accurate outcomes, but may be less efficient.
 If you're confident that your chosen pseudopotential is appropriate, you can safely ignore this warning.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

 UNIFORM GRID DIM        : 375 * 180 * 180
 UNIFORM GRID DIM(BIG)   : 75 * 45 * 45
 DONE(0.289529   SEC) : SETUP UNITCELL
 DONE(0.395614   SEC) : SYMMETRY
 DONE(0.491893   SEC) : INIT K-POINTS
 ---------------------------------------------------------
 Self-consistent calculations for electrons
 ---------------------------------------------------------
 SPIN    KPOINTS         PROCESSORS  NBASE       
 1       4               16          3653        
 ---------------------------------------------------------
 Use Systematically Improvable Atomic bases
 ---------------------------------------------------------
 ELEMENT ORBITALS        NBASE       NATOM       XC          
 Pt      4s2p2d1f-7au    27          100         
 H       2s1p-6au        5           97          
 O       2s2p1d-7au      13          36          
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 DONE(0.582922   SEC) : INIT PLANEWAVE
 -------------------------------------------
 SELF-CONSISTENT : 
 -------------------------------------------
 START CHARGE      : atomic
 DONE(10.3867    SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GE1    -3.461734e+05  0.000000e+00   6.171e-02  2.893e+01  
 GE2    -3.337279e+05  1.244552e+04   3.388e-01  2.294e+01  
 GE3    -3.492001e+05  -1.547220e+04  4.333e-01  2.299e+01  
 GE4    -3.500685e+05  -8.684070e+02  2.910e-01  2.291e+01  
 GE5    -3.510739e+05  -1.005355e+03  3.095e-01  2.288e+01  
 GE6    -3.515349e+05  -4.610621e+02  3.602e-01  2.292e+01  
 GE7    -3.515025e+05  3.244726e+01   3.741e-01  2.297e+01  
 GE8    -3.502130e+05  1.289451e+03   3.838e-01  2.294e+01  
 GE9    -3.492059e+05  1.007176e+03   3.320e-01  2.296e+01  
 GE10   -3.488811e+05  3.247201e+02   2.632e-01  2.296e+01  
 GE11   -3.490081e+05  -1.270015e+02  2.380e-01  2.299e+01  
 GE12   -3.492406e+05  -2.324203e+02  2.496e-01  2.301e+01  
 GE13   -3.479780e+05  1.262582e+03   2.659e-01  2.299e+01  
 GE14   -3.478410e+05  1.370196e+02   1.809e-01  2.298e+01  
 GE15   -3.475639e+05  2.770131e+02   1.516e-01  2.299e+01  
 GE16   -3.472183e+05  3.456881e+02   1.192e-01  2.301e+01  
 GE17   -3.474526e+05  -2.343890e+02  8.956e-02  2.299e+01  
 GE18   -3.474898e+05  -3.718937e+01  9.255e-02  2.301e+01  
 GE19   -3.474903e+05  -4.229241e-01  9.290e-02  2.304e+01  
 GE20   -3.474779e+05  1.239075e+01   9.283e-02  2.307e+01  
 GE21   -3.474764e+05  1.479289e+00   8.937e-02  2.301e+01  
 GE22   -3.479360e+05  -4.596046e+02  8.851e-02  2.303e+01  
 GE23   -3.482843e+05  -3.482968e+02  2.489e-01  2.304e+01  
 GE24   -3.483793e+05  -9.496153e+01  1.857e-01  2.300e+01  
 GE25   -3.482923e+05  8.690549e+01   1.657e-01  2.305e+01  
 GE26   -3.478953e+05  3.970388e+02   1.662e-01  2.301e+01  
 GE27   -3.479338e+05  -3.845673e+01  1.396e-01  2.302e+01  
 GE28   -3.476511e+05  2.826749e+02   1.351e-01  2.298e+01  
 GE29   -3.477224e+05  -7.135659e+01  1.150e-01  2.302e+01  
 GE30   -3.476664e+05  5.602840e+01   1.119e-01  2.298e+01  
 GE31   -3.476024e+05  6.402166e+01   1.041e-01  2.303e+01  
 GE32   -3.474053e+05  1.970891e+02   1.021e-01  2.302e+01  
 GE33   -3.471504e+05  2.548576e+02   8.160e-02  2.302e+01  
 GE34   -3.469501e+05  2.003288e+02   1.176e-01  2.299e+01  
 GE35   -3.473610e+05  -4.108730e+02  6.726e-02  2.295e+01  
 GE36   -3.474089e+05  -4.795021e+01  5.870e-02  2.297e+01  
 GE37   -3.459993e+05  1.409689e+03   1.736e-01  2.298e+01  
 GE38   -3.473443e+05  -1.345073e+03  5.339e-02  2.299e+01  
 GE39   -3.473434e+05  8.882915e-01   5.154e-02  2.297e+01  
 GE40   -3.473427e+05  7.090073e-01   5.282e-02  2.302e+01  
 GE41   -3.473632e+05  -2.045682e+01  5.955e-02  2.299e+01  
 GE42   -3.473769e+05  -1.375377e+01  5.727e-02  2.299e+01  
 GE43   -3.473820e+05  -5.057697e+00  5.804e-02  2.300e+01  
 GE44   -3.473508e+05  3.121499e+01   6.001e-02  2.302e+01  
 GE45   -3.473309e+05  1.983300e+01   4.823e-02  2.305e+01  
 GE46   -3.473229e+05  8.013943e+00   3.839e-02  2.305e+01  
 GE47   -3.473870e+05  -6.409113e+01  4.014e-02  2.302e+01  
 GE48   -3.473920e+05  -5.017069e+00  5.958e-02  2.298e+01  
 GE49   -3.474348e+05  -4.276593e+01  5.459e-02  2.296e+01  
 GE50   -3.473826e+05  5.219836e+01   6.497e-02  2.303e+01  
 GE51   -3.473896e+05  -6.952725e+00  5.478e-02  2.302e+01  
 GE52   -3.474052e+05  -1.562362e+01  5.520e-02  2.305e+01  
 GE53   -3.473174e+05  8.779968e+01   5.738e-02  2.308e+01  
 GE54   -3.472144e+05  1.029857e+02   4.113e-02  2.310e+01  
 GE55   -3.472598e+05  -4.541720e+01  4.086e-02  2.306e+01  
 GE56   -3.473159e+05  -5.610275e+01  3.040e-02  2.307e+01  
 GE57   -3.469100e+05  4.058786e+02   4.265e-02  2.310e+01  
 GE58   -3.468947e+05  1.539130e+01   9.707e-02  2.311e+01  
 GE59   -3.473065e+05  -4.118954e+02  2.927e-02  2.307e+01  
 GE60   -3.473074e+05  -8.141060e-01  2.631e-02  2.308e+01  
 GE61   -3.473159e+05  -8.563660e+00  2.457e-02  2.313e+01  
 GE62   -3.473140e+05  1.918208e+00   2.991e-02  2.306e+01  
 GE63   -3.473052e+05  8.818926e+00   2.469e-02  2.309e+01  
 GE64   -3.473104e+05  -5.170324e+00  1.628e-02  2.307e+01  
 GE65   -3.473119e+05  -1.556715e+00  1.496e-02  2.309e+01  
 GE66   -3.473120e+05  -5.815481e-02  1.469e-02  2.308e+01  
 GE67   -3.473094e+05  2.573003e+00   1.443e-02  2.312e+01  
 GE68   -3.473114e+05  -2.010238e+00  1.320e-02  2.309e+01  
 GE69   -3.473111e+05  3.175387e-01   1.276e-02  2.309e+01  
 GE70   -3.473102e+05  9.148593e-01   1.198e-02  2.307e+01  
 GE71   -3.473100e+05  1.799374e-01   1.082e-02  2.314e+01  
 GE72   -3.473078e+05  2.225491e+00   8.860e-03  2.308e+01  
 GE73   -3.473080e+05  -2.153064e-01  1.164e-02  2.308e+01  
 GE74   -3.473078e+05  2.288443e-01   9.933e-03  2.308e+01  
 GE75   -3.473088e+05  -9.944947e-01  7.099e-03  2.309e+01  
 GE76   -3.473087e+05  8.364847e-02   7.614e-03  2.307e+01  
 GE77   -3.473038e+05  4.857332e+00   6.784e-03  2.308e+01  
 GE78   -3.473040e+05  -1.667305e-01  7.253e-03  2.308e+01  
 GE79   -3.473036e+05  4.207686e-01   9.171e-03  2.308e+01  
 GE80   -3.473026e+05  9.511238e-01   7.863e-03  2.309e+01  
 GE81   -3.473006e+05  1.987143e+00   7.396e-03  2.312e+01  
 GE82   -3.473010e+05  -4.294875e-01  4.437e-03  2.307e+01  
 GE83   -3.473008e+05  2.533313e-01   3.742e-03  2.307e+01  
 GE84   -3.473006e+05  1.758362e-01   2.734e-03  2.312e+01  
 GE85   -3.472999e+05  6.766435e-01   3.120e-03  2.310e+01  
 GE86   -3.473003e+05  -3.362512e-01  3.552e-03  2.308e+01  
 GE87   -3.473002e+05  1.044580e-01   2.807e-03  2.314e+01  
 GE88   -3.473003e+05  -1.309710e-01  3.318e-03  2.308e+01  
 GE89   -3.473003e+05  5.113751e-03   2.938e-03  2.309e+01  
 GE90   -3.473005e+05  -1.841271e-01  2.856e-03  2.306e+01  
 GE91   -3.473008e+05  -3.564991e-01  4.140e-03  2.310e+01  
 GE92   -3.473008e+05  6.325655e-02   4.733e-03  2.312e+01  
 GE93   -3.472999e+05  8.872343e-01   4.783e-03  2.314e+01  
 GE94   -3.473003e+05  -3.755370e-01  2.404e-03  2.308e+01  
 GE95   -3.473003e+05  -7.396028e-02  2.701e-03  2.311e+01  
 GE96   -3.473007e+05  -3.129645e-01  3.306e-03  2.309e+01  
 GE97   -3.473008e+05  -1.784194e-01  5.274e-03  2.310e+01  
 GE98   -3.473007e+05  1.269968e-01   5.084e-03  2.308e+01  
 GE99   -3.473008e+05  -1.056579e-01  4.655e-03  2.308e+01  
 GE100  -3.473001e+05  6.647274e-01   4.888e-03  2.311e+01  
 GE101  -3.473000e+05  1.361681e-01   2.783e-03  2.308e+01  
 GE102  -3.473001e+05  -1.204788e-01  1.439e-03  2.310e+01  
 GE103  -3.473002e+05  -8.289595e-02  1.574e-03  2.308e+01  
 GE104  -3.472999e+05  3.320759e-01   2.253e-03  2.311e+01  
 GE105  -3.473000e+05  -1.517865e-01  8.027e-04  2.313e+01  
 GE106  -3.473000e+05  4.718780e-03   6.514e-04  2.311e+01  
 GE107  -3.473000e+05  2.484068e-04   3.736e-04  2.308e+01  
 GE108  -3.473000e+05  1.555444e-03   3.211e-04  2.309e+01  
 GE109  -3.473000e+05  6.153736e-04   2.439e-04  2.309e+01  
 GE110  -3.473000e+05  1.367553e-03   1.959e-04  2.312e+01  
 GE111  -3.473000e+05  -2.782054e-04  1.968e-04  2.312e+01  
 GE112  -3.473000e+05  2.254756e-04   1.642e-04  2.307e+01  
 GE113  -3.473000e+05  6.909034e-04   1.420e-04  2.310e+01  
 GE114  -3.473000e+05  2.238593e-04   1.330e-04  2.306e+01  
 GE115  -3.473000e+05  -6.882032e-05  1.266e-04  2.309e+01  
 GE116  -3.473000e+05  1.183646e-04   1.167e-04  2.309e+01  
 GE117  -3.473000e+05  1.426873e-04   9.305e-05  2.320e+01  
 GE118  -3.473000e+05  1.259965e-04   7.954e-05  2.314e+01  
 GE119  -3.473000e+05  2.280691e-04   7.172e-05  2.309e+01  
 GE120  -3.473000e+05  -7.934665e-05  6.788e-05  2.315e+01  
 GE121  -3.473000e+05  -6.912903e-05  1.031e-04  2.313e+01  
 GE122  -3.473000e+05  -1.136984e-04  7.513e-05  2.310e+01  
 GE123  -3.473000e+05  1.558391e-05   7.238e-05  2.311e+01  
 GE124  -3.473000e+05  5.546871e-04   6.299e-05  2.309e+01  
 GE125  -3.473000e+05  -2.974339e-05  7.774e-05  2.310e+01  
 GE126  -3.473000e+05  -1.460708e-04  5.203e-05  2.308e+01  
 GE127  -3.473000e+05  -2.326445e-05  3.718e-05  2.308e+01  
 GE128  -3.473000e+05  -5.785208e-05  2.592e-05  2.310e+01  
 GE129  -3.473000e+05  -5.307337e-05  2.238e-05  2.308e+01  
 GE130  -3.473000e+05  -4.483539e-05  1.442e-05  2.312e+01  
 GE131  -3.473000e+05  -2.666832e-05  1.505e-05  2.310e+01  
 GE132  -3.473000e+05  -4.442209e-05  1.184e-05  2.309e+01  
 GE133  -3.473000e+05  -5.032800e-05  1.035e-05  2.312e+01  
 GE134  -3.473000e+05  -1.481438e-05  6.978e-06  2.312e+01  
 GE135  -3.473000e+05  -1.136684e-05  6.335e-06  2.310e+01  
 GE136  -3.473000e+05  -1.372974e-05  4.533e-06  2.311e+01  
 GE137  -3.473000e+05  -1.249667e-05  3.472e-06  2.310e+01  
 GE138  -3.473000e+05  -1.719732e-05  3.206e-06  2.307e+01  
 GE139  -3.473000e+05  -6.810622e-06  2.305e-06  2.310e+01  
 GE140  -3.473000e+05  -5.265813e-06  2.023e-06  2.311e+01  
 GE141  -3.473000e+05  -7.961730e-06  1.387e-06  2.307e+01  
 GE142  -3.473000e+05  -5.571508e-06  1.248e-06  2.309e+01  
 GE143  -3.473000e+05  -3.303000e-06  9.291e-07  2.312e+01  
 GE144  -3.473000e+05  -1.625539e-06  9.177e-07  2.310e+01  
 GE145  -3.473000e+05  -2.205399e-06  6.800e-07  2.311e+01  
 GE146  -3.473000e+05  -3.434416e-06  7.323e-07  2.311e+01  
 GE147  -3.473000e+05  -3.709868e-06  4.363e-07  2.325e+01  
TIME STATISTICS
------------------------------------------------------------------------------------
     CLASS_NAME                 NAME            TIME(Sec)  CALLS   AVG(Sec) PER(%)
------------------------------------------------------------------------------------
                     total                      3454.24         11 314.02   100.00
Driver               reading                      0.03           1   0.03     0.00
Input                Init                         0.02           1   0.02     0.00
Input_Conv           Convert                      0.00           1   0.00     0.00
Driver               driver_line                3454.22          1 3454.22  100.00
UnitCell             check_tau                    0.00           1   0.00     0.00
PW_Basis_Sup         setuptransform               0.06           1   0.06     0.00
PW_Basis_Sup         distributeg                  0.06           1   0.06     0.00
mymath               heapsort                     0.05       11885   0.00     0.00
Symmetry             analy_sys                    0.00           1   0.00     0.00
PW_Basis_K           setuptransform               0.05           1   0.05     0.00
PW_Basis_K           distributeg                  0.05           1   0.05     0.00
PW_Basis             setup_struc_factor           1.93           1   1.93     0.06
ORB_control          read_orb_first               0.16           1   0.16     0.00
LCAO_Orbitals        Read_Orbitals                0.16           1   0.16     0.00
NOrbital_Lm          extra_uniform                0.10          17   0.01     0.00
Mathzone_Add1        SplineD2                     0.00          17   0.00     0.00
Mathzone_Add1        Cubic_Spline_Interpolation   0.00          17   0.00     0.00
Mathzone_Add1        Uni_Deriv_Phi                0.09          17   0.01     0.00
Sphbes               Spherical_Bessel             0.06       14070   0.00     0.00
ppcell_vl            init_vloc                    1.79           1   1.79     0.05
Ions                 opt_ions                   3449.36          1 3449.36   99.86
ESolver_KS_LCAO      Run                        3406.65          1 3406.65   98.62
ESolver_KS_LCAO      beforescf                    5.63           1   5.63     0.16
Vdwd3                cal_energy                   0.33           1   0.33     0.01
ESolver_KS_LCAO      beforesolver                 0.62           1   0.62     0.02
ESolver_KS_LCAO      set_matrix_grid              0.40           1   0.40     0.01
atom_arrange         search                       0.04           1   0.04     0.00
Grid_Technique       init                         0.09           1   0.09     0.00
Grid_BigCell         grid_expansion_index         0.02           2   0.01     0.00
Record_adj           for_2d                       0.26           1   0.26     0.01
Grid_Driver          Find_atom                    0.18       27101   0.00     0.01
LCAO_Hamilt          grid_prepare                 0.00           1   0.00     0.00
Veff                 initialize_HR                0.00           1   0.00     0.00
OverlapNew           initialize_SR                0.00           1   0.00     0.00
EkineticNew          initialize_HR                0.00           1   0.00     0.00
NonlocalNew          initialize_HR                0.01           1   0.01     0.00
Charge               set_rho_core                 0.00           1   0.00     0.00
Charge               atomic_rho                   1.91           1   1.91     0.06
PW_Basis_Sup         recip2real                  42.78        1037   0.04     1.24
PW_Basis_Sup         gathers_scatterp            19.84        1037   0.02     0.57
Potential            init_pot                     0.83           1   0.83     0.02
Potential            update_from_charge         110.01         148   0.74     3.18
Potential            cal_fixed_v                  0.07           1   0.07     0.00
PotLocal             cal_fixed_v                  0.05           1   0.05     0.00
Gatefield            add_gatefield                0.01           1   0.01     0.00
Potential            cal_v_eff                  109.67         148   0.74     3.17
H_Hartree_pw         v_hartree                   13.53         149   0.09     0.39
PW_Basis_Sup         real2recip                  40.65        1185   0.03     1.18
PW_Basis_Sup         gatherp_scatters            17.52        1185   0.01     0.51
PotXC                cal_v_eff                   92.07         148   0.62     2.67
XC_Functional        v_xc                        91.65         148   0.62     2.65
Efield               add_efield                   2.50         149   0.02     0.07
Potential            interpolate_vrs              0.28         148   0.00     0.01
Symmetry             rhog_symmetry              235.56         148   1.59     6.82
Symmetry             group fft grids            133.13         148   0.90     3.85
H_Ewald_pw           compute_ewald                0.05           1   0.05     0.00
HSolverLCAO          solve                      2987.63        147  20.32    86.49
HamiltLCAO           updateHk                   485.19         588   0.83    14.05
OperatorLCAO         init                       480.36        1764   0.27    13.91
Veff                 contributeHR               470.88         147   3.20    13.63
Gint_interface       cal_gint                   883.90         295   3.00    25.59
Gint_interface       cal_gint_vlocal            428.41         147   2.91    12.40
Gint_Tools           cal_psir_ylm               208.80     2266152   0.00     6.04
Gint_k               transfer_pvpR               42.47         147   0.29     1.23
OverlapNew           calculate_SR                 0.89           1   0.89     0.03
OverlapNew           contributeHk                 3.94         588   0.01     0.11
EkineticNew          contributeHR                 0.88         147   0.01     0.03
EkineticNew          calculate_HR                 0.88           1   0.88     0.03
NonlocalNew          contributeHR                 2.99         147   0.02     0.09
NonlocalNew          calculate_HR                 2.37           1   2.37     0.07
OperatorLCAO         contributeHk                 3.58         588   0.01     0.10
HSolverLCAO          hamiltSolvePsiK            1806.00        588   3.07    52.28
DiagoElpa            elpa_solve                 1801.39        588   3.06    52.15
ElecStateLCAO        psiToRho                   696.44         147   4.74    20.16
elecstate            cal_dm                     169.31         148   1.14     4.90
psiMulPsiMpi         pdgemm                     168.00         592   0.28     4.86
DensityMatrix        cal_DMR                      3.50         148   0.02     0.10
 Local_Orbital_wfc   wfc_2d_to_grid              44.71         592   0.08     1.29
Gint                 transfer_DMR                12.97         147   0.09     0.38
Gint_interface       cal_gint_rho               441.85         147   3.01    12.79
Charge_Mixing        get_drho                     0.27         147   0.00     0.01
Charge               mix_rho                     23.92         146   0.16     0.69
Charge               Pulay_mixing                 4.84         146   0.03     0.14
Potential            write_elecstat_pot           4.90           1   4.90     0.14
Force_Stress_LCAO    getForceStress              42.71           1  42.71     1.24
Forces               cal_force_loc                1.92           1   1.92     0.06
Forces               cal_force_ew                 1.83           1   1.83     0.05
Forces               cal_force_cc                 0.00           1   0.00     0.00
Forces               cal_force_scc                3.94           1   3.94     0.11
Force_LCAO_k         ftable_k                    34.14           1  34.14     0.99
Force_LCAO_k         allocate_k                   8.99           1   8.99     0.26
LCAO_gen_fixedH      b_NL_mu_new                  6.19           1   6.19     0.18
Force_LCAO_k         cal_foverlap_k               3.78           1   3.78     0.11
Force_LCAO_k         cal_edm_2d                   3.74           1   3.74     0.11
Force_LCAO_k         cal_ftvnl_dphi_k             0.01           1   0.01     0.00
Force_LCAO_k         cal_fvl_dphi_k              13.64           1  13.64     0.39
Gint_interface       cal_gint_force              13.64           1  13.64     0.39
Gint_Tools           cal_dpsir_ylm                7.72        7708   0.00     0.22
Force_LCAO_k         cal_fvnl_dbeta_k_new         5.08           1   5.08     0.15
Vdwd3                cal_force                    0.86           1   0.86     0.02
ModuleIO             write_istate_info            0.02           1   0.02     0.00
------------------------------------------------------------------------------------

 ----------------------------------------------------------

 START  Time  : Tue Nov 21 17:03:39 2023
 FINISH Time  : Tue Nov 21 18:01:13 2023
 TOTAL  Time  : 3454
 SEE INFORMATION IN : OUT.ABACUS/

```
