### ISSUE TITLE
The imaginary of DMR are needed.

### ISSUE THREAD

**Issue by ESROAMER** [deepmodeling/abacus-develop#3210]
### Background

I'm working on tddft development, in which the calculation of time-dependent current is very important. And to calculate the time-dependent current, the imaginary of density matrix are needed. At the moment, DMR is stored as a double type, so there's no imaginary part to use.

### Describe the solution you'd like

I hope the imaginary of DMR can be stored when `GlobalV::ESOLVER_TYPE == "tddft"`, that would be convient for tddft current calculation.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [x] Review and understand the proposed feature and its importance.
- [x] Research on the existing solutions and relevant research articles/resources.
- [x] Discuss with the team to evaluate the feasibility of implementing the feature.
- [x] Create a design document outlining the proposed solution and implementation details.
- [x] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
OK, I will develop a new function member to return a HContainer* DMR, in which store the imaginary of DMR.

**Comment by WHUweiqingzhou** [comment]
@ESROAMER 
Hi, are you still interested in the imaginary of DMR? Please inform us.

**Comment by ESROAMER** [comment]
> @ESROAMER Hi, are you still interested in the imaginary of DMR? Please inform us.

Yes, the imaginary of DMR is still needed. Sorry I didn't reply you in time. I just saw your comment.

**Comment by ESROAMER** [comment]
Never mind, I decide to change the implement.
