### ISSUE TITLE
Segmentation fault while running with the GPU code

### ISSUE THREAD

**Issue by denghuilu** [deepmodeling/abacus-develop#3211]
### Describe the bug

Error:
<img width="1536" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/21070560/9b402fb0-9647-42f6-b642-21c8b267d741">
 INPUT:
 
<img width="466" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/21070560/d3c1fb21-28a0-4462-845c-987ac2f1dc02">

### To Reproduce

Compile the CUDA-version of ABACUS and Run the abacus-develop/examples/scf/pw_Si2 with the above INPUT.

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [X] Steps to reproduce.
- [X] Expected behavior.
- [X] Error message.
- [X] Environment details.
- [X] Additional context.
- [X] Assign a priority level (low, medium, high, urgent).
- [X] Assign the issue to a team member.
- [X] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).
