### ISSUE TITLE
Calculating atomic force in noncolliear and/or SOC case are needed

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#3233]
### Background

Calculating atomic force in noncolliear and/or SOC case are needed in calculation of DeepSpin.

### Describe the solution you'd like

Implement atomic force calculation in noncolliear and/or SOC calculations.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [x] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by hongriTianqi** [comment]
This is related to #3130

**Comment by hongriTianqi** [comment]
Todos:

- [x] add test links on Force and Stress finite difference tests.
- [x] add case test for the functionality of new codes.

**Comment by hongriTianqi** [comment]
Finite difference test for noncollinear force with soc: 

BCC Fe with mag in (111) direction:

https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.108-538675

Finite difference test for stress:
(1) collinear calculation: 
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.109-acc605
(2) noncollinear with soc_lambda = 0:
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.109-eb2364
(3) noncollinear with soc_lambda = 1:
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.109-3236a6 (all difference < 1 kBar)
