### ISSUE TITLE
Integrated tests pose warnings

### ISSUE THREAD

**Issue by Zhuxuegang2022** [deepmodeling/abacus-develop#3242]
### Describe the Testing Issue

[warningtot2023_11_22_13_58.txt](https://github.com/deepmodeling/abacus-develop/files/13434964/warningtot2023_11_22_13_58.txt)
relate to the issues of #2844  "On November 21, 2023, I collected all available PRs on GitHub, categorized them as the warningtot2023_11_22_13_58.txt, and identified certain warnings that may require contributors to address.
______
The first case is as follows: 
PR #2998  by @Qianruipku  has introduced some new warnings, although they appeared and disappeared before the latest introduction.
```
...
PR 3008 
PR 2998 2023-10-09T07:20:18.4148669Z 1: [WARNING   ]  totalstressref cal=1409.56340100 ref=1409.54391900 deviation=-0.01948200
...up to now appear
```
- [x] 101_PW_15_pseudopots_LibxcLDA
- [x] 103_PW_15_CS_CF
- [x] 103_PW_15_CS_CF_bspline
- [x] 103_PW_OU_CS_CF
- [x] 107_PW_outWfcPw
- [x] 107_PW_outWfcR
- [ ] 108_PW_RE
- [x] 108_PW_RE_MG
- [ ] 109_PW_CR_fix_ac
- [ ] 109_PW_CR_fix_b
- [ ] 109_PW_CR_fix_bc
- [ ] 109_PW_CR_fix_c
- [ ] 109_PW_CR_moveatoms
- [x] 110_PW_SY
- [x] 112_PW_dipole
- [x] 112_PW_efield
- [x] 113_PW_gatefield
- [x] 115_PW_sol_H2O
- [x] 120_PW_KP_MD_MSST
- [x] 120_PW_KP_MD_MSST_level2
- [ ] 120_PW_KP_MD_NPT
- [ ] 120_PW_KP_MD_NVT
- [ ] 170_PW_MD_1O
- [ ] 170_PW_MD_2O
- [x] 201_NO_KP_DJ_CF_CS_GaAs
- [x] 204_NO_KP_AFM
- [x] 270_NO_MD_1O
______
The second case is as follows:
PR #3178 @wenfei-li has introduced a new warnings as 
```
...
PR 3176 
PR 3178 2023-11-09T06:28:13.2550640Z 1: [WARNING   ]  etotref cal=-200.93490284 ref=-200.93404758 deviation=0.00085526
...up to now
```
- [ ] 101_PW_15_paw
______
The third case is as follows:
PR #3122 @YuLiu98  has introduced a new warnings as 
```
...
PR 3139 
PR 3122 2023-11-03T04:12:42.2978862Z 1: [WARNING   ]  totalstressref cal=763.26430700 ref=763.25719100 deviation=-0.00711600
PR 3144 
PR 3145 2023-11-03T14:42:51.5758164Z 1: [WARNING   ]  totalstressref cal=763.26434700 ref=763.25719100 deviation=-0.00715600
...up to now
```
- [ ] 101_PW_upf201_uspp_NaCl
______
The fourth case is as follows:
PR #3175 @pxlxingliang has introduced some new warnings：but these warnings had appeared before and disappeared at some point.
```
...
PR 3172 
PR 3175 2023-11-08T07:02:03.8821639Z 1: [WARNING   ]  totalforceref cal=5.19522000 ref=5.19483200 deviation=-0.00038800
PR 3134 
PR 3177 2023-11-09T01:40:44.4158332Z 1: [WARNING   ]  totalforceref cal=5.19522000 ref=5.19483200 deviation=-0.00038800
...up to now
```
- [ ] 102_PW_BPCG
- [x] 184_PW_BNDKPAR_SDFT_ALL
- [x] 184_PW_BNDKPAR_SDFT_MALL
______
The fifth case is as follows:
PR #3081 by @maki49  has introduced some new warnings as:
```
...
PR 3105 
PR 3081 2023-10-25T17:22:09.7680675Z 1: [WARNING   ]  etotref cal=-145.79150761 ref=-145.79681340 deviation=-0.00530579
PR 3108 
PR 3109 2023-10-26T09:27:52.6434574Z 1: [WARNING   ]  etotref cal=-145.79150761 ref=-145.79681340 deviation=-0.00530579
...appear up to now
```
- [x] 207_NO_KP_OHS_SPIN4
- [x] 207_NO_KP_OTdH
- [x] 213_NO_mulliken
______
The sixth case is as follows:
PR #3133 @WHUweiqingzhou The warning may refresh the ref.data to eliminate the warning.
```
...
PR 3127 
PR 3133 2023-11-02T03:49:49.1430259Z 1: [WARNING   ]  totalstressref cal=4160.38232200 ref=4160.36613500 deviation=-0.01618700
...appear up to now
```
- [ ] 281_NO_KP_HSE
- [ ] 286_NO_KP_CR_HSE
- [ ] 803_PW_LT_bcc
- [ ] 810_PW_LT_fco
- [x] 812_PW_LT_sm
______
The last case is as follows: Some warnings appear consistently because GitHub only supports data for up to three months. The warning may refresh the ref.data to eliminate the warning.
- [ ] 109_PW_CR
- [ ] 109_PW_CR_fix_a
- [ ] 109_PW_CR_fix_ab
- [ ] 109_PW_CR_fix_abc
- [x] 116_PW_scan_Si2
- [ ] 116_PW_scan_Si2_nspin2
- [ ] 150_PW_15_CR_VDW3
- [x] 601_NO_TDDFT_CO
- [x] 801_PW_LT_sc
- [ ] 802_PW_LT_fcc
- [ ] 807_PW_LT_bct

update state by @hongriTianqi according to https://github.com/deepmodeling/abacus-develop/actions/runs/7318359302/job/19934906652 at 2023-12-25
 

### Additional Context

[Aotogetwarn.txt](https://github.com/deepmodeling/abacus-develop/files/13435834/Aotogetwarn.txt)
the bash script that I have used to collect the warnings, in order to use it one need download some of the related PR test with zip file and run the bash in the linux shell. 

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by Zhuxuegang2022** [comment]
update the new warning massage in 2023.12.17
______
1. First case is as follows:
PR #3226  by @WHUweiqingzhou  has introduced some new warnings
```
...
PR 3222 
PR 3226 2023-11-22T13:38:01.2405169Z 1: [WARNING   ]  totalforceref cal=1618.32500000 ref=1618.32250400 deviation=-0.00249600
...up to now appear
```
the related test is:
- [ ] 101_PW_Coulomb
- [x] 101_PW_upf201_uspp_Fe
- [ ] 103_PW_15_CF_CS_S1_smallg
- [ ] 103_PW_15_CF_CS_S2_smallg 
- [ ] 103_PW_CF_CS_S1_smallg
- [ ] 103_PW_CF_CS_S2_smallg
- [ ] 108_PW_RE_MB
- [ ] 108_PW_RE_NEW
- [ ] 108_PW_RE_PINT_RKS
- [ ] 111_PW_S2_elec_add
- [ ] 111_PW_S2_elec_minus
- [ ] 111_PW_elec_add
- [ ] 111_PW_elec_minus
- [ ] 180_PW_SDFT_10S_M
- [ ] 180_PW_SDFT_10S_P
- [ ] 181_PW_SDFT_5D10S
- [ ] 182_PW_SDFT_ALL
- [ ] 183_PW_MD_SDFT_10S
- [ ] 183_PW_MD_SDFT_5D10S
- [ ] 183_PW_MD_SDFT_ALL
- [ ] 184_PW_BNDPAR_SDFT_10S
- [ ] 184_PW_BNDPAR_SDFT_5D10S
- [ ] 184_PW_KPAR_SDFT_ALL
- [ ] 185_PW_SDFT_10D10S_METHD2
- [ ] 185_PW_SDFT_10S_METHD2
- [ ] 211_NO_elec_add
- [ ] 250_NO_KP_CR_VDW2
- [ ] 250_NO_KP_CR_VDW3
- [ ] 250_NO_KP_CR_VDW3ABC
- [ ] 250_NO_KP_CR_VDW3BJ
- [ ] 385_NO_GO_RE_S1_HSE
- [ ] 386_NO_GO_MD_S1_HSE
- [ ] 806_PW_LT_st
______
2. The second case is as follows:
PR #3337 @WHUweiqingzhou had introduce some new waring, but its dissappear in RP #3345 add by @dyzheng , howerver appear for PR #3306 by @wenfei-li . I think it may be need @WHUweiqingzhou to see it at first. 
```
...
PR 3330 
PR 3337 2023-12-15T03:55:56.2703475Z 1: [WARNING   ]  etotref cal=-211.82181944 ref=-211.81909772 deviation=0.00272172
PR 3345 
PR 3306 2023-12-15T06:47:12.5508878Z 1: [WARNING   ]  etotref cal=-211.82181944 ref=-211.81909772 deviation=0.00272172
```
the related test is:
- [ ] 109_PW_CR_fix_ac
- [ ] 109_PW_CR_fix_b
- [ ] 109_PW_CR_fix_bc
- [ ] 109_PW_CR_fix_c
- [ ] 109_PW_CR_moveatoms
- [ ] 120_PW_KP_MD_NPT
- [ ] 120_PW_KP_MD_NVT
- [ ] 133_PW_DJ_PK
- [ ] 170_PW_MD_1O
- [ ] 170_PW_MD_2O
- [ ] 208_NO_KP_CF_RE
- [ ] 208_NO_KP_CS_CR
- [ ] 220_NO_KP_MD_NVT
- [ ] 104_PW_NC_magnetic(this test is related but dissappear at 3306)
______
3. the thrid case is :
PR #3247  by @maki49 has introduce a waring of 
```
...
PR 3256 
PR 3247 2023-12-01T03:15:47.3153304Z 1: [WARNING   ]  etotref cal=-2.29195538 ref=-2.67060500 deviation=-0.37864962
```
the related test is:
- [x] 704_LJ_CR
______
4. the forth case is :
there have two tests dissapperar warning, for three time testing, but other case it have the waring all time,  I think it is not soveled by before 
```
PR 3250 2023-11-25T04:25:16.8538095Z 1: [WARNING   ]  etotref cal=-204.07301586 ref=-204.11317477 deviation=-0.04015891
PR 3263 
PR 3261 
PR 3258 2023-11-27T16:47:22.9130308Z 1: [WARNING   ]  totalforceref cal=16.66210400 ref=16.66011000 deviation=-0.00199400
PR 3269 
PR 3270 2023-11-29T05:31:52.0497120Z 1: [WARNING   ]  totalforceref cal=16.66210400 ref=16.66011000 deviation=-0.00199400
```
- [ ] 116_PW_scan_Si2_nspin2
- [ ] 116_PW_scan_Si2
______
5. Good news are that some warning have being dissapper,
 It seems fix by @Qianruipku  and @WHUweiqingzhou and other developer 
- [x] 101_PW_15_pseudopots_LibxcLDA
- [x] 103_PW_15_CS_CF
- [x] 103_PW_15_CS_CF_bspline
- [x] 103_PW_OU_CS_CF
- [x] 107_PW_outWfcPw
- [x]  107_PW_outWfcR
- [x] 108_PW_RE_MG
- [x] 110_PW_SY
- [x] 112_PW_dipole
- [x] 112_PW_efield
- [x] 113_PW_gatefield
- [x] 115_PW_sol_H2O
- [x] 120_PW_KP_MD_MSST
- [x] 120_PW_KP_MD_MSST_level2
- [x] 127_PW_15_PK_AF
- [x] 104_PW_FM_magnetic
- [x] 201_NO_KP_DJ_CF_CS_GaAs
- [x] 204_NO_KP_AFM
- [x] 204_NO_KP_NC_deltaspin
- [x] 204_NO_KP_S2_deltaspin
- [x]  382_NO_GO_S2_HSE
- [x] 270_NO_MD_1O
- [x] 601_NO_TDDFT_CO
- [x] 812_PW_LT_sm
- [x] 801_PW_LT_sc

**Comment by Zhuxuegang2022** [comment]
[warningtot2023_12_17_20_17.txt](https://github.com/deepmodeling/abacus-develop/files/13696136/warningtot2023_12_17_20_17.txt)
Add the warning that collect from 2023-11.22---2023.12.17

**Comment by WHUweiqingzhou** [comment]
The new warnings are introduced by PR #3133, #3226, #3337 is due to the change of default value:
1. PR #3133 change default value of `mixing_gg0` from 0.0 to 1.0.
2. PR #3226 remove `autoset()`, and set `mixing_beta=0.8` for nspin=1; `mixing_beta=0.4` for nspin=2.
3. PR #3337 change default value of `smearing_method` from `fixed` into `gauss`, and `smearing_sigma` from 0.01 to 0.015.

**Comment by pxlxingliang** [comment]
The warnings of 102_PW_BPCG are not related the PR #3175. I have used the codes of pre commit (98b3cedfc (Wed Nov 8 12:01:14 2023 +0800)) and the warning is still occurred.

The warnings of 184_PW_BNDKPAR_SDFT_ALL/184_PW_BNDKPAR_SDFT_MALL are occurred after PR #3175, but this PR is just modify the symmetry_prec from 1e-5 to 1e-6, which should give higher precision results. 
commit: https://github.com/deepmodeling/abacus-develop/pull/3369 modify the reference of 184_PW_BNDKPAR_SDFT_ALL/184_PW_BNDKPAR_SDFT_MALL.

**Comment by Zhuxuegang2022** [comment]
[warningtot2023_12_17_20_17.txt](https://github.com/deepmodeling/abacus-develop/files/13777467/warningtot2023_12_17_20_17.txt)
date from 2023:12:17 to 2023:12:27, it seems no new warning introduced
and the case of 104_PW_NC_magnetic may should pay attention

**Comment by mohanchen** [comment]
Since no further updates, I will close this issue.
