### ISSUE TITLE
Certain tests could not get passed with gcc-13

### ISSUE THREAD

**Issue by yizeyi18** [deepmodeling/abacus-develop#3245]
### Describe the Testing Issue

ALL tests including an "ASSERT_DEATH" or "EXPECT_DEATH", as listed below , failed due to "failed to die". 
<details><summary>The failed tests are:</summary>

          1 - integrated_test (Failed)
         17 - base_matrix (Failed)
         18 - base_complexarray (Failed)
         19 - base_complexmatrix (Failed)
         20 - base_integral (Failed)
         28 - base_math_bspline (Failed)
         31 - base_container (Failed)
         45 - clebsch_gordan_coeff_test (Failed)
        208 - ORB_table_alpha_test (Failed)
        265 - lattice_change_cg_test (Failed)
        266 - bfgs_basic_test (Failed)
        270 - ions_move_cg_test (Failed)
        271 - ions_move_sd_test (Failed)

</details>

Fail infomation looks like:
```
[ RUN      ] IonsMoveSDTest.TestAllocateWithZeroDimension
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_relax/relax_old/test/ions_move_sd_test.cpp:52: Failure
Death test: im_sd.allocate()
    Result: failed to die.
 Error msg:
[  DEATH   ]
```

### Additional Context

Looking at the subroutines these tests test within release v3.4.3, they all have compiler hints like "assert( nr==m.nr );" indicate that the ill-conditioned situation in the failed tests would not appear. Are these tests outdated, or gcc-13 is not safe enough to compile ABACUS?
AOCC and Clang are tested as below. They also fails at these tests.
Other compiler like OneAPI or older gcc is not tested. 

### Task list for Issue attackers (only for developers)

- [X] Understand the testing issue described by the developer.
- [X] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by yizeyi18** [comment]
UPDATE:
AOCC fails at all tests above and have one additional test failed. 
The addition test is:

        189 - HSolver_bpcg (Failed)

Error message is:
```
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hsolver/test/diago_bpcg_test.cpp:144: Failure
The difference between en[i] and e_lapack[i] is 0.060286112699984074, which exceeds threshold, where
en[i] evaluates to -13.713089716124387,
e_lapack[i] evaluates to -13.773375828824371, and
threshold evaluates to 0.050000000000000003.
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hsolver/test/diago_bpcg_test.cpp:144: Failure
The difference between en[i] and e_lapack[i] is 0.11478792531574911, which exceeds threshold, where
en[i] evaluates to -13.610809789933469,
e_lapack[i] evaluates to -13.725597715249219, and
threshold evaluates to 0.050000000000000003.
[  FAILED  ] VerifyCG/DiagoBPCGTest.RandomHamilt/3, where GetParam() = 64-byte object <28-00 00-00 E8-03 00-00 08-00 00-00 2C-01 00-00 EF-00 00-00 00-00 00-00 8D-ED B5-A0 F7-C6 B0-3E 20-25 4F-5C 10-15 00-00 01-B9 32-0E FC-7F 00-00 9A-99 99-99 99-99 A9-3F 01-00 00-00 00-00 00-00> (7702 ms)
[----------] 4 tests from VerifyCG/DiagoBPCGTest (14250 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 2 test suites ran. (16531 ms total)
[  PASSED  ] 5 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] VerifyCG/DiagoBPCGTest.RandomHamilt/3, where GetParam() = 64-byte object <28-00 00-00 E8-03 00-00 08-00 00-00 2C-01 00-00 EF-00 00-00 00-00 00-00 8D-ED B5-A0 F7-C6 B0-3E 20-25 4F-5C 10-15 00-00 01-B9 32-0E FC-7F 00-00 9A-99 99-99 99-99 A9-3F 01-00 00-00 00-00 00-00>
```

**Comment by yizeyi18** [comment]
UPDATE: 
Clang-17.0.4 fails at all tests failed same as AOCC-4.1, with similar error message.
One only differance form aocc is that clang would link to libstdc++.so without absolute path infomation, that would cause segmentation fault if not linked to system libstdc++: one situation may encounter when user compiles clang with a compiler installed MANUALLY and the clang would default to link to the libstdc++ from the manually installed compiler. That could get fixed, though needs root privilege, by ldconfig /path/to/linked/libstdc++. 
This difference seems come from clang and may get fixed in their later updates, maybe?

**Comment by yizeyi18** [comment]
UPDATE:
Clang-18.1.1 fails at more tests, including all tests with HF calculation.
test log:
[LastTest.log](https://github.com/deepmodeling/abacus-develop/files/14730932/LastTest.log)
<details><summary>Failed Tests</summary>
<p>

```bash
          1 - integrated_test (Failed)
          6 - base_atom_in (Failed)
          8 - base_timer (Failed)
          9 - base_tool_quit (Failed)
         10 - base_tool_check (Failed)
         11 - base_memory (Failed)
         13 - base_vector3 (Failed)
         15 - base_intarray (Failed)
         16 - base_realarray (Failed)
         17 - base_matrix (Failed)
         18 - base_complexarray (Failed)
         19 - base_complexmatrix (Failed)
         20 - base_integral (Failed)
         21 - base_sph_bessel_recursive (Failed)
         23 - base_math_sphbes (Failed)
         26 - base_math_polyint (Failed)
         28 - base_math_bspline (Failed)
         30 - base_mymath (Failed)
         31 - base_container (Failed)
         36 - base_ylm (Failed)
         37 - base_abfs-vector3_order (Failed)
         38 - base_global_file (Failed)
         39 - base_tool_title (Failed)
         40 - base_element_basis_index (Failed)
         41 - base_tool_threading (Failed)
         44 - formatter_test (Failed)
         47 - perf_sphbes (Failed)
         58 - cell_neighbor_sltk_adjacent_set (Failed)
         59 - cell_neighbor_sltk_atom (Failed)
         92 - potentials_base (Failed)
        109 - XCTest_PBE (Failed)
        110 - XCTest_PBEsol (Failed)
        111 - XCTest_BP (Failed)
        112 - XCTest_revPBE (Failed)
        113 - XCTest_WC (Failed)
        114 - XCTest_BLYP (Failed)
        115 - XCTest_OLYP (Failed)
        116 - XCTest_HCTH (Failed)
        117 - XCTest_PWLDA (Failed)
        118 - XCTest_PZ (Failed)
        119 - XCTest_SLATER1 (Failed)
        120 - XCTest_SLATER_RXC (Failed)
        121 - XCTest_PW (Failed)
        122 - XCTest_LYP (Failed)
        123 - XCTest_VWN (Failed)
        124 - XCTest_WIGNER (Failed)
        125 - XCTest_HL (Failed)
        126 - XCTest_GL (Failed)
        127 - XCTest_PW91 (Failed)
        128 - XCTest_OPTX (Failed)
        129 - XCTest_WCX (Failed)
        130 - XCTest_PBE0 (Failed)
        131 - XCTest_PBE_LibXC (Failed)
        132 - XCTest_HSE (Failed)
        133 - XCTest_SCAN0 (Failed)
        134 - XCTest_KSDT (Failed)
        135 - XCTest_KT2 (Failed)
        136 - XCTest_R2SCAN (Failed)
        137 - XCTest_LB07 (Failed)
        138 - XCTest_BMK (Failed)
        139 - XCTest_HF (Failed)
        140 - XCTest_PZ_SPN (Failed)
        141 - XCTest_PBE_SPN (Failed)
        142 - XCTest_BP_SPN (Failed)
        143 - XCTest_revPBE_SPN (Failed)
        144 - XCTest_SLATER1_SPN (Failed)
        145 - XCTest_SLATER_RXC_SPN (Failed)
        146 - XCTest_P86_SPN (Failed)
        147 - XCTest_PBE0_SPN (Failed)
        148 - XCTest_PBEsol_SPN (Failed)
        149 - XCTest_PBE_SPN_LibXC (Failed)
        150 - XCTest_PZ_SPN_LibXC (Failed)
        158 - ewald_dnrm2 (Failed)
        191 - HSolver_bpcg (Failed)
        210 - ORB_table_alpha_test (Failed)
        247 - binstream_test (Failed)
        256 - io_parse_args (Failed)
        271 - relax_new_line_search (Failed)
        275 - lattice_change_cg_test (Failed)
        276 - bfgs_basic_test (Failed)
        280 - ions_move_cg_test (Failed)
        281 - ions_move_sd_test (Failed)
```

</p>
</details> 
cmake commands:

[new-llvm.log](https://github.com/deepmodeling/abacus-develop/files/14730954/new-llvm.log)
<details><summary>cmake command line and output</summary>
<p>

```bash
yizeyi18@DESKTOP-5UK5DD4:~/soft/abacus-develop$ source ./new-llvm.log
-- The CXX compiler identification is Clang 18.1.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/llvm-18.1.1-drljntsopzn25bawfjf4iu4phe5a7p5m/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.34.1")
-- Found git: attempting to get commit info...
-- Current commit hash: 48eba329e
-- Last commit date: Sat Mar 23 15:19:46 2024 +0800
-- Found Cereal: /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/cereal-1.3.2-f5ql2tyaquxgtmwiomjevk46l54436xf/include
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Found ELPA: /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/elpa-2023.05.001-pw5jd2bbdwjchld4cgeyghe7yf2twarg/lib/libelpa_openmp.so
-- Performing Test ELPA_VERSION_SATISFIES
-- Performing Test ELPA_VERSION_SATISFIES - Success
-- Found MPI_CXX: /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/openmpi-4.1.5-5nthj2erc4qvro6znlnn7f25gk3s4464/lib/libmpi.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenMP_CXX: -fopenmp=libomp
-- Found OpenMP: TRUE
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- Found FFTW3: /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/fftw-3.3.10-yvepezskwyqhawiqzawiqdzkfgij6wjs/lib/libfftw3_omp.so
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/openblas-0.3.23-wgxa4exqunpso4neiyghujciw3latemx/lib/libopenblas.so
-- Looking for cheev_
-- Looking for cheev_ - found
-- Found LAPACK: /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/openblas-0.3.23-wgxa4exqunpso4neiyghujciw3latemx/lib/libopenblas.so;-lm;-ldl
-- Found ScaLAPACK: /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/netlib-scalapack-2.2.0-5szvra6zk62lhyfkrrcatrjfxadzupvi/lib/libscalapack.so
-- Checking for one of the modules 'libxc'
-- Found Libxc: /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/libxc-6.2.2-xqbit2clckxfcmea5iqotn5xvqhonr4z/lib/libxc.so
-- Found Libxc: version 6.2.2
-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yizeyi18/soft/abacus-develop/build
```

</p>
</details> 
One thing interest is, abacus the program and most of tests was linked with correct rpath, but some still lacks rpath, causing runtime glibc version issue. This may got fixed through cmake settings.
<details><summary>cmake generated link.txt of module_base/test/base_atom_in</summary>
<p>

`
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/llvm-18.1.1-drljntsopzn25bawfjf4iu4phe5a7p5m/bin/clang++  -fopenmp=libomp -O3 -DNDEBUG /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/llvm-18.1.1-drljntsopzn25bawfjf4iu4phe5a7p5m/lib/libomp.so /lib/x86_64-linux-gnu/libpthread.a CMakeFiles/base_atom_in.dir/atom_in_test.cpp.o -o base_atom_in  -Wl,-rpath,/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/googletest-1.14.0-dmjoutwl7hp4cfffutchgcdsk5bkkzke/lib:/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/llvm-18.1.1-drljntsopzn25bawfjf4iu4phe5a7p5m/lib:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/googletest-1.14.0-dmjoutwl7hp4cfffutchgcdsk5bkkzke/lib/libgtest_main.so.1.14.0 /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/googletest-1.14.0-dmjoutwl7hp4cfffutchgcdsk5bkkzke/lib/libgmock_main.so.1.14.0 /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/benchmark-1.8.3-kytgvj2og6rdwozpa5hq5pdcu5u2ep3f/lib/libbenchmark.a /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/googletest-1.14.0-dmjoutwl7hp4cfffutchgcdsk5bkkzke/lib/libgmock.so.1.14.0 /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/googletest-1.14.0-dmjoutwl7hp4cfffutchgcdsk5bkkzke/lib/libgtest.so.1.14.0 -lrt /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/llvm-18.1.1-drljntsopzn25bawfjf4iu4phe5a7p5m/lib/libomp.so /lib/x86_64-linux-gnu/libpthread.a
`

</p>
</details> 
<details><summary>cmake generated link.txt of module_hamilt_general/module_xc/test/XCTest_PBE0: notice key paths like $GCC_PREFIX/lib64 included.</summary>
<p>

`
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/llvm-18.1.1-drljntsopzn25bawfjf4iu4phe5a7p5m/bin/clang++  -fopenmp=libomp -O3 -DNDEBUG /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/llvm-18.1.1-drljntsopzn25bawfjf4iu4phe5a7p5m/lib/libomp.so /lib/x86_64-linux-gnu/libpthread.a -Wl,-rpath,/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-15.0.7/gcc-13.2.0-hqxorkupts6u727x5ktb2kmwsdpvm2x6/lib/gcc/x86_64-pc-linux-gnu/13.2.0 -Wl,-rpath,/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-15.0.7/gcc-13.2.0-hqxorkupts6u727x5ktb2kmwsdpvm2x6/lib64 -Wl,-rpath -Wl,/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/openmpi-4.1.5-5nthj2erc4qvro6znlnn7f25gk3s4464/lib -Wl,-rpath -Wl,/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/hwloc-2.9.1-sg627sl7dqdhflizzzdezxsryhk53hcy/lib -Wl,-rpath -Wl,/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/libevent-2.1.12-snzahvlnnqlt6mdupg2qyzgytwkjrlif/lib -Wl,-rpath -Wl,/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/pmix-4.2.4-oaj4xlzdu2hlseeqrdixh44fu7nlvfpc/lib -L/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/hwloc-2.9.1-sg627sl7dqdhflizzzdezxsryhk53hcy/lib -L/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/libevent-2.1.12-snzahvlnnqlt6mdupg2qyzgytwkjrlif/lib -L/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/pmix-4.2.4-oaj4xlzdu2hlseeqrdixh44fu7nlvfpc/lib CMakeFiles/XCTest_PBE0.dir/test_xc.cpp.o CMakeFiles/XCTest_PBE0.dir/__/xc_functional.cpp.o CMakeFiles/XCTest_PBE0.dir/__/xc_functional_wrapper_xc.cpp.o CMakeFiles/XCTest_PBE0.dir/__/xc_functional_wrapper_gcxc.cpp.o CMakeFiles/XCTest_PBE0.dir/__/xc_funct_corr_gga.cpp.o CMakeFiles/XCTest_PBE0.dir/__/xc_funct_corr_lda.cpp.o CMakeFiles/XCTest_PBE0.dir/__/xc_funct_exch_gga.cpp.o CMakeFiles/XCTest_PBE0.dir/__/xc_funct_exch_lda.cpp.o CMakeFiles/XCTest_PBE0.dir/__/xc_funct_hcth.cpp.o -o XCTest_PBE0  -Wl,-rpath,/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/libxc-6.2.2-xqbit2clckxfcmea5iqotn5xvqhonr4z/lib:/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/googletest-1.14.0-dmjoutwl7hp4cfffutchgcdsk5bkkzke/lib:/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/openmpi-4.1.5-5nthj2erc4qvro6znlnn7f25gk3s4464/lib:/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/llvm-18.1.1-drljntsopzn25bawfjf4iu4phe5a7p5m/lib:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/libxc-6.2.2-xqbit2clckxfcmea5iqotn5xvqhonr4z/lib/libxc.so /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/googletest-1.14.0-dmjoutwl7hp4cfffutchgcdsk5bkkzke/lib/libgtest_main.so.1.14.0 /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/googletest-1.14.0-dmjoutwl7hp4cfffutchgcdsk5bkkzke/lib/libgmock_main.so.1.14.0 /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/benchmark-1.8.3-kytgvj2og6rdwozpa5hq5pdcu5u2ep3f/lib/libbenchmark.a /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/openmpi-4.1.5-5nthj2erc4qvro6znlnn7f25gk3s4464/lib/libmpi.so /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/googletest-1.14.0-dmjoutwl7hp4cfffutchgcdsk5bkkzke/lib/libgmock.so.1.14.0 /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/clang-18.1.1/googletest-1.14.0-dmjoutwl7hp4cfffutchgcdsk5bkkzke/lib/libgtest.so.1.14.0 -lrt /home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-13.2.0/llvm-18.1.1-drljntsopzn25bawfjf4iu4phe5a7p5m/lib/libomp.so /lib/x86_64-linux-gnu/libpthread.a
`
</p>
</details>

**Comment by caic99** [comment]
> -fopenmp=libomp -O3 -DNDEBUG

@yizeyi18 Using `-DNDEBUG` suppresses all assertions. You could remove that statement and try again.

**Comment by yizeyi18** [comment]
@caic99 `-DNDEBUG` is generated by `cmake` for all release build. Should I reconfigure the package with `-DCMAKE_BUILD_TYPE=Debug` (instead of `-DCMAKE_BUILD_TYPE=Release` or `-DCMAKE_BUILD_TYPE=RelWithDebInfo`)?

**Comment by caic99** [comment]
@yizeyi18 Sure!

**Comment by yizeyi18** [comment]
@caic99 I tried both `-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-O3 -g"` and `-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g"`, both yields error in unit test. The no `-O3` one still hangs at test 154 `HSolver_bpcg`(for over 20 min), log of `-O3` one are listed below:


 - Screen output of the test  
[test.log](https://github.com/user-attachments/files/17054663/test.log)
 - Full log and log of fails
[LastTest.log](https://github.com/user-attachments/files/17054674/LastTest.log)
[LastTestsFailed.log](https://github.com/user-attachments/files/17054680/LastTestsFailed.log)
 - Flags of compile and link 
[flags.make.txt](https://github.com/user-attachments/files/17054693/flags.make.txt)
[link.txt](https://github.com/user-attachments/files/17054696/link.txt)

**Comment by caic99** [comment]
> hangs at test 154 `HSolver_bpcg`

Hi @yizeyi18 ,
I suggest submitting a new issue on this. It would be better if you can locate the codes that hangs.

**Comment by yizeyi18** [comment]
@caic99 Till now, all HSolver tests timeout(in 1500 seconds), fail, or segfault, with a big memory comsumption(40-70GiB). I suppose it's from low compiler optimization level, I did not observe these timeout with `-DCMAKE_CXX_FLAGS="-O3 -g"`.

**Comment by caic99** [comment]
@yizeyi18 I considered it to be a bug, and let's discuss it in a new issue.
