### ISSUE TITLE
Improving CMake performance on finding ELPA and LibXC

### ISSUE THREAD

**Issue by yizeyi18** [deepmodeling/abacus-develop#3252]
### Describe the Code Quality Issue

ABACUS now finds ELPA headers by find_path subroutine in CMake, which makes it difficult to switch between versions; using pkg-config based pkg_search_module would soften this issue by reading $ELPA_ROOT/lib/pkg-config/elpa_openmp.pc and get header infomation from this. LibXC finding could also get improved since the two packages both install a pkgconfig file but not always with .cmake files. 

### Additional Context

(And, how to open a new branch for abacus? I wrote some new files but found nowhere to submit them.

### Task list for Issue attackers (only for developers)

- [X] Identify the specific code file or section with the code quality issue.
- [X] Investigate the issue and determine the root cause.
- [X] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by caic99** [comment]
> (And, how to open a new branch for abacus? I wrote some new files but found nowhere to submit them.

Hi @yizeyi18 ,
Thank you for your effort testing abacus. Please refer to [the contribution guide](https://abacus.deepmodeling.com/en/stable/CONTRIBUTING.html#submitting-a-pull-request).
