### ISSUE TITLE
Inconsistent stress result between QE and ABACUS pw

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3253]
### Describe the bug

ABACUS:
```
----------------------------------------------------------------
TOTAL-STRESS (KBAR)
----------------------------------------------------------------
      -11.1517226043        -0.0398599266        -0.0379270247
       -0.0398599266       -11.1984051526        -0.0849172119
       -0.0379270247        -0.0849172119       -11.2474104304
----------------------------------------------------------------
```
ABACUS with `symmetry 0`:
```
----------------------------------------------------------------
TOTAL-STRESS (KBAR)
----------------------------------------------------------------
      -10.6406978429         0.0000001927         0.0000024773
        0.0000001927       -10.6406922429        -0.0000006441
        0.0000024773        -0.0000006441       -10.6406901023
----------------------------------------------------------------
```
QE:
```
     Computing stress (Cartesian axis) and pressure

          total   stress  (Ry/bohr**3)                   (kbar)     P=        3.06
   0.00002034  -0.00000000  -0.00000000            2.99       -0.00       -0.00
  -0.00000000   0.00002034   0.00000000           -0.00        2.99        0.00
  -0.00000000   0.00000000   0.00002168           -0.00        0.00        3.19
```
Further perform cell-relax:
ABACUS:
```
 LATTICE VECTORS: (CARTESIAN COORDINATE: IN UNIT OF A0)
            +3.494360           +0.000000           +0.000000
            +1.747180           +3.026206           +0.000000
            +1.747181           +1.008735           +2.853134
```
QE:
```
CELL_PARAMETERS (angstrom)
   3.510218860  -0.000000000  -0.000000001
   1.755109485   3.039939504  -0.000000000
   1.755110115   1.013312995   2.866135114
```

### Expected behavior

stress tensor should be more consistent

### To Reproduce

[Er.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13447157/Er.tar.gz)

### Task list for Issue attackers (only for developers)

- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [x] Steps to reproduce.
- [x] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by YuLiu98** [comment]
Note that input parameters are updated in order to align with those of QE, which can be seen in the attached [Er_liuyu.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13473167/Er_liuyu.tar.gz).
I tested the example you provided, results are shown in the following: 

ABACUS with `symmetry` =0
```
----------------------------------------------------------------
TOTAL-STRESS (KBAR)                                           
----------------------------------------------------------------
      -11.3025854690         0.0145129260        -0.0574074228
        0.0145129260       -11.4006668695         0.0101072125
       -0.0574074228         0.0101072125       -11.3029541760
----------------------------------------------------------------
```

QE with `symmetry` =0
```
          total   stress  (Ry/bohr**3)                   (kbar)     P=      -11.31
  -0.00007700   0.00000033   0.00000021          -11.33        0.05        0.03
   0.00000033  -0.00007686  -0.00000001            0.05      -11.31       -0.00
   0.00000021  -0.00000001  -0.00007671            0.03       -0.00      -11.28
```

I think that the stress is consistent between ABACUS and QE.

**Comment by kirk0830** [comment]
> Note that input parameters are updated in order to align with those of QE, which can be seen in the attached [Er_liuyu.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13473167/Er_liuyu.tar.gz). I tested the example you provided, results are shown in the following:
> 
> ABACUS with `symmetry` =0
> 
> ```
> ----------------------------------------------------------------
> TOTAL-STRESS (KBAR)                                           
> ----------------------------------------------------------------
>       -11.3025854690         0.0145129260        -0.0574074228
>         0.0145129260       -11.4006668695         0.0101072125
>        -0.0574074228         0.0101072125       -11.3029541760
> ----------------------------------------------------------------
> ```
> 
> QE with `symmetry` =0
> 
> ```
>           total   stress  (Ry/bohr**3)                   (kbar)     P=      -11.31
>   -0.00007700   0.00000033   0.00000021          -11.33        0.05        0.03
>    0.00000033  -0.00007686  -0.00000001            0.05      -11.31       -0.00
>    0.00000021  -0.00000001  -0.00007671            0.03       -0.00      -11.28
> ```
> 
> I think that the stress is consistent between ABACUS and QE.

thanks~

**Comment by hongriTianqi** [comment]
One need to add these two lines to reproduce results in QE:
pseudo_mesh 1
pseudo_rcut 10

**Comment by hongriTianqi** [comment]
This is a good practice as it can share experience on how to compare results with ABACUS and QE.
