### ISSUE TITLE
AOCC Fails at constexpr check for MPI type

### ISSUE THREAD

**Issue by yizeyi18** [deepmodeling/abacus-develop#3254]
### Describe the bug

When compiling ABACUS using AOCC-4.1, error below occurs:
```
In file included from /home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/transfer.cpp:1:
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:157:35: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
    static constexpr MPI_Datatype datatype()
                                  ^
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:159:16: note: cast from 'void *' is not allowed in a constant expression
        return MPI_INT;
               ^
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/aocc-4.0.0/openmpi-4.1.5-tbilqgadlyp2c7z2zjeycbmascep3xfy/include/mpi.h:1188:17: note: expanded from macro 'MPI_INT'
#define MPI_INT OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_int)
                ^
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/aocc-4.0.0/openmpi-4.1.5-tbilqgadlyp2c7z2zjeycbmascep3xfy/include/mpi.h:400:47: note: expanded from macro 'OMPI_PREDEFINED_GLOBAL'
#define OMPI_PREDEFINED_GLOBAL(type, global) (static_cast<type> (static_cast<void *> (&(global))))
                                              ^
In file included from /home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/transfer.cpp:1:
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:166:35: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
    static constexpr MPI_Datatype datatype()
                                  ^
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:168:16: note: cast from 'void *' is not allowed in a constant expression
        return MPI_DOUBLE;
               ^
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/aocc-4.0.0/openmpi-4.1.5-tbilqgadlyp2c7z2zjeycbmascep3xfy/include/mpi.h:1191:20: note: expanded from macro 'MPI_DOUBLE'
#define MPI_DOUBLE OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_double)
                   ^
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/aocc-4.0.0/openmpi-4.1.5-tbilqgadlyp2c7z2zjeycbmascep3xfy/include/mpi.h:400:47: note: expanded from macro 'OMPI_PREDEFINED_GLOBAL'
#define OMPI_PREDEFINED_GLOBAL(type, global) (static_cast<type> (static_cast<void *> (&(global))))
                                              ^
In file included from /home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/transfer.cpp:1:
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:175:35: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
    static constexpr MPI_Datatype datatype()
                                  ^
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:177:16: note: cast from 'void *' is not allowed in a constant expression
        return MPI_DOUBLE_COMPLEX;
               ^
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/aocc-4.0.0/openmpi-4.1.5-tbilqgadlyp2c7z2zjeycbmascep3xfy/include/mpi.h:1266:28: note: expanded from macro 'MPI_DOUBLE_COMPLEX'
#define MPI_DOUBLE_COMPLEX OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_dblcplex)
                           ^
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/aocc-4.0.0/openmpi-4.1.5-tbilqgadlyp2c7z2zjeycbmascep3xfy/include/mpi.h:400:47: note: expanded from macro 'OMPI_PREDEFINED_GLOBAL'
#define OMPI_PREDEFINED_GLOBAL(type, global) (static_cast<type> (static_cast<void *> (&(global))))
                                              ^
[ 13%] Building CXX object source/module_base/CMakeFiles/base.dir/formatter_contextfmt.cpp.o
In file included from /home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/func_transfer.cpp:2:
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:157:35: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
    static constexpr MPI_Datatype datatype()
                                  ^
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:159:16: note: cast from 'void *' is not allowed in a constant expression
        return MPI_INT;
               ^
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/aocc-4.0.0/openmpi-4.1.5-tbilqgadlyp2c7z2zjeycbmascep3xfy/include/mpi.h:1188:17: note: expanded from macro 'MPI_INT'
#define MPI_INT OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_int)
                ^
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/aocc-4.0.0/openmpi-4.1.5-tbilqgadlyp2c7z2zjeycbmascep3xfy/include/mpi.h:400:47: note: expanded from macro 'OMPI_PREDEFINED_GLOBAL'
#define OMPI_PREDEFINED_GLOBAL(type, global) (static_cast<type> (static_cast<void *> (&(global))))
                                              ^
In file included from /home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/func_transfer.cpp:2:
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:166:35: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
    static constexpr MPI_Datatype datatype()
                                  ^
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:168:16: note: cast from 'void *' is not allowed in a constant expression
        return MPI_DOUBLE;
               ^
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/aocc-4.0.0/openmpi-4.1.5-tbilqgadlyp2c7z2zjeycbmascep3xfy/include/mpi.h:1191:20: note: expanded from macro 'MPI_DOUBLE'
#define MPI_DOUBLE OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_double)
                   ^
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/aocc-4.0.0/openmpi-4.1.5-tbilqgadlyp2c7z2zjeycbmascep3xfy/include/mpi.h:400:47: note: expanded from macro 'OMPI_PREDEFINED_GLOBAL'
#define OMPI_PREDEFINED_GLOBAL(type, global) (static_cast<type> (static_cast<void *> (&(global))))
                                              ^
In file included from /home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/func_transfer.cpp:2:
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:175:35: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
    static constexpr MPI_Datatype datatype()
                                  ^
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:177:16: note: cast from 'void *' is not allowed in a constant expression
        return MPI_DOUBLE_COMPLEX;
               ^
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/aocc-4.0.0/openmpi-4.1.5-tbilqgadlyp2c7z2zjeycbmascep3xfy/include/mpi.h:1266:28: note: expanded from macro 'MPI_DOUBLE_COMPLEX'
#define MPI_DOUBLE_COMPLEX OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_dblcplex)
                           ^
/home/yizeyi18/soft/spack/opt/spack/linux-ubuntu22.04-zen3/aocc-4.0.0/openmpi-4.1.5-tbilqgadlyp2c7z2zjeycbmascep3xfy/include/mpi.h:400:47: note: expanded from macro 'OMPI_PREDEFINED_GLOBAL'
#define OMPI_PREDEFINED_GLOBAL(type, global) (static_cast<type> (static_cast<void *> (&(global))))
                                              ^
3 errors generated.
make[2]: *** [source/module_hamilt_lcao/module_hcontainer/CMakeFiles/hcontainer.dir/build.make:146：source/module_hamilt_lcao/module_hcontainer/CMakeFiles/hcontainer.dir/transfer.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
```
### Expected behavior

The code should pass compile. 

### To Reproduce

Build use AOCC-4.0 or 4.1.

### Additional Context

This patch may fix, though breaks some safety check performed by the compiler:
[aocc-mpi.patch](https://github.com/deepmodeling/abacus-develop/files/13447221/aocc-mpi.patch)

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [X] Steps to reproduce.
- [X] Expected behavior.
- [X] Error message.
- [X] Environment details.
- [X] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [X] Fix the bug.
- [X] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by yizeyi18** [comment]
UPDATE：Clang-17.0.4 fails so.

**Comment by dyzheng** [comment]
Sorry, I don't have the background knowledge of this Issue, maybe other developers can help for this.

**Comment by yizeyi18** [comment]
Some further tests got done and it seems a little strange:
According to [https://clang.llvm.org/cxx_status.html](url) , clang should implemented constexpr cast from void* as part of c++2c standard in clang 17; the reality is, while enabling -DCMAKE_CXX_STANDARD=26(which adds -std=gnu++26 flag to clang), similar error still occurs:
<details><summary>Error message</summary>

```
In file included from /home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/transfer.cpp:1:
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:157:35: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
  157 |     static constexpr MPI_Datatype datatype()
      |                                   ^
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:159:16: note: cast from 'void *' is not allowed in a constant expression in C++ standards before C++2c
  159 |         return MPI_INT;
      |                ^
/opt/openmpi-4.1.5/include/mpi.h:1188:17: note: expanded from macro 'MPI_INT'
 1188 | #define MPI_INT OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_int)
      |                 ^
/opt/openmpi-4.1.5/include/mpi.h:400:47: note: expanded from macro 'OMPI_PREDEFINED_GLOBAL'
  400 | #define OMPI_PREDEFINED_GLOBAL(type, global) (static_cast<type> (static_cast<void *> (&(global))))
      |                                               ^
In file included from /home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/transfer.cpp:1:
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:166:35: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
  166 |     static constexpr MPI_Datatype datatype()
      |                                   ^
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:168:16: note: cast from 'void *' is not allowed in a constant expression in C++ standards before C++2c
  168 |         return MPI_DOUBLE;
      |                ^
/opt/openmpi-4.1.5/include/mpi.h:1191:20: note: expanded from macro 'MPI_DOUBLE'
 1191 | #define MPI_DOUBLE OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_double)
      |                    ^
/opt/openmpi-4.1.5/include/mpi.h:400:47: note: expanded from macro 'OMPI_PREDEFINED_GLOBAL'
  400 | #define OMPI_PREDEFINED_GLOBAL(type, global) (static_cast<type> (static_cast<void *> (&(global))))
      |                                               ^
In file included from /home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/transfer.cpp:1:
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:175:35: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
  175 |     static constexpr MPI_Datatype datatype()
      |                                   ^
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:177:16: note: cast from 'void *' is not allowed in a constant expression in C++ standards before C++2c
  177 |         return MPI_DOUBLE_COMPLEX;
      |                ^
/opt/openmpi-4.1.5/include/mpi.h:1266:28: note: expanded from macro 'MPI_DOUBLE_COMPLEX'
 1266 | #define MPI_DOUBLE_COMPLEX OMPI_PREDEFINED_GLOBAL(MPI_Datatype, ompi_mpi_dblcplex)
      |                            ^
/opt/openmpi-4.1.5/include/mpi.h:400:47: note: expanded from macro 'OMPI_PREDEFINED_GLOBAL'
  400 | #define OMPI_PREDEFINED_GLOBAL(type, global) (static_cast<type> (static_cast<void *> (&(global))))
      |                                               ^
```
</details>
I had little idea why clang fails here.  

EDIT: 
Removing CMAKE_CXX_STANDARD in CMakeList.txt makes some difference, that clang gives some error message never seen before:
```
/home/yizeyi18/soft/abacus-develop-3.4.3/source/module_hamilt_lcao/module_hcontainer/./transfer.h:159:16: note: cast from 'void *' is not allowed in a constant expression because the pointed object type 'ompi_predefined_datatype_t' is not similar to the target type 'struct ompi_datatype_t'
  159 |         return MPI_INT;
      |                ^
```
That maybe hints the clang compiler really considers this cast as not good, though ompi_predefined_datatype_t contains only one ompi_datatype_t object and an array of char, and would fail here for this reason.

**Comment by denghuilu** [comment]
@yizeyi18, could you please verify the latest code in the development branch? Pull Request #3286 is expected to resolve this issue, particularly since the ROCm environment defaults to using the clang compiler. Check [this](https://github.com/deepmodeling/abacus-develop/pull/3286/files#diff-ef1e90aa1649cdc3c9f208f23e5f23766afd8b0d0b0602afcdcaba94734f1845).

**Comment by yizeyi18** [comment]
> @yizeyi18, could you please verify the latest code in the development branch? Pull Request #3286 is expected to resolve this issue, particularly since the ROCm environment defaults to using the clang compiler. Check [this](https://github.com/deepmodeling/abacus-develop/pull/3286/files#diff-ef1e90aa1649cdc3c9f208f23e5f23766afd8b0d0b0602afcdcaba94734f1845).

constexpr totally removed...This solves. May we close this issue?
