### ISSUE TITLE
Rename output files to let their names more user-friendly

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3262]
### Background

Present files output:
```
running_*.scf // log of job
OLD1_SPIN_CHG.cube // not very clear
NOW_SPIN_CHG.cube // seems the spin distribution of the latest state
STRU_READIN_ADJUST.cif // seems the structure read -in
STRU_SIMPLE.cif // not very clear
STRU_ION_D // not very clear about the letter "D" and why emphasize "ion"
```
### Describe the solution you'd like

Quantum ESPRESSO outputs structure in stdout, CP2K outputs structure in appending way to *-pos-1.xyz.

### Task list only for developers

- [X] Notice possible changes of behavior
- [X] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by QuantumMisaka** [comment]
I think structure and properties (with atom information like constraints, mulliken charge and magnetic moments projected to each atom) should all be print-out or have a copy in running*.log, which is much easier for third software to interface with abacus. Now, ASE cannot read any constraints, charge and magnetic moments from ABACUS output results.

**Comment by hongriTianqi** [comment]
@pxlxingliang Could you please comment?

**Comment by pxlxingliang** [comment]
It is best not to modify the name of some commonly used file, like: running_scf.log and STRU_ION_D. Most of the post process soft will use them.
