### ISSUE TITLE
Wavefunction files get much larger during calculation

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#3265]
### Details

In newest ABACUS, wavefunction files will be written in an append but not overwriting way, which will cause wavefunction file getting much larger when keep using wavefunction file for SCF output and read-in, which will be done in ASE-ABACUS calculation.

An example: using MgO bulk:
```bash
ATOMIC_SPECIES
Mg 24.305 Mg_ONCV_PBE-1.0.upf
O  15.999 O_ONCV_PBE-1.0.upf

NUMERICAL_ORBITAL
Mg_gga_8au_100Ry_4s2p1d.orb
O_gga_8au_100Ry_2s2p1d.orb

LATTICE_CONSTANT
1.8897259886    # 1.8897259886 Bohr = 1.0 Angstrom

LATTICE_VECTORS
4.35 0.00000 0.00000
0.00000 4.35 0.00000
0.00000 0.00000 4.35

ATOMIC_POSITIONS
Direct 
Mg 
0.0 
4 
0.0 0.0 0.0 1 1 1 
0.0 0.47 0.5 1 1 1
0.6 0.0 0.60 1 1 1
0.6 0.5 0.10 1 1 1

O
0.0 
4 
0.4 0.0 0.05 1 1 1
0.5 0.5 0.5 1 1 1 
0.1 0.0 0.46 1 1 1 
0.0 0.5 0.1 1 1 1
```
and INPUT setting
```bash
INPUT_PARAMETERS RUNNING ABACUS-DFT

#Parameters (1.General)
suffix                  ABACUS  # suffix of OUTPUT DIR
nspin                   2   #  1/2/4 4 for SOC
symmetry                1   #  0/1  1 for open, default
esolver_type            ksdft  # ksdft, ofdft, sdft, tddft, lj, dp
ks_solver             genelpa  # default for ksdft-lcao

#Parameters (2.Iteration)
calculation             scf # scf relax cell-relax md
ecutwfc                 100
scf_thr                 1e-12
scf_nmax                300

#Parameters (3.Basis)
basis_type              lcao  # lcao or pw

#Parameters (4.Smearing)
smearing_method         gau   # mp/gaussian/fixed
smearing_sigma          0.001  # Rydberg

#Parameters (5.Mixing)
#mixing_type             broyden

#Parameters (6.Calculation)
cal_force          1
cal_stress         1
out_stru           1  # print STRU in OUT
out_chg            1  # print CHG or not
out_wfc_lcao       1
```
KPT set to `4 4 4`

When first SCF calculation is done, one can detect the size of wavefunction files and charge files
```bash
(base) [2201110432@wm2-login01 wfc]$ ll -h OUT.wfc1/*
(base) [2201110432@wm2-login01 wfc]$ ll -h OUT.wfc1/
total 26M
-rw-rw-r-- 1 2201110432 2201110432  25K Nov 25 11:09 INPUT
-rw-rw-r-- 1 2201110432 2201110432 168K Nov 25 11:09 istate.info
-rw-rw-r-- 1 2201110432 2201110432  13K Nov 25 11:09 kpoints
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_10.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_11.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_12.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_13.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_14.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_15.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_16.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_17.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_18.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_19.txt
-rw-rw-r-- 1 2201110432 2201110432 309K Nov 25 11:09 LOWF_K_1.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_20.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_21.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_22.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_23.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_24.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_25.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_26.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_27.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_28.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_29.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_2.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_30.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_31.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_32.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_33.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_34.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_35.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_36.txt
-rw-rw-r-- 1 2201110432 2201110432 309K Nov 25 11:09 LOWF_K_37.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_38.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_39.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_3.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_40.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_41.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_42.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_43.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_44.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_45.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_46.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_47.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_48.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_49.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_4.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_50.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_51.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_52.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_53.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_54.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_55.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_56.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_57.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_58.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_59.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_5.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_60.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_61.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_62.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_63.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_64.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_65.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_66.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_67.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_68.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_69.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_6.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_70.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_71.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_72.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_7.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_8.txt
-rw-rw-r-- 1 2201110432 2201110432 311K Nov 25 11:09 LOWF_K_9.txt
-rw-rw-r-- 1 2201110432 2201110432 189K Nov 25 11:09 running_scf.log
-rw-rw-r-- 1 2201110432 2201110432 1.6M Nov 25 11:09 SPIN1_CHG.cube
-rw-rw-r-- 1 2201110432 2201110432 1.6M Nov 25 11:09 SPIN2_CHG.cube
-rw-rw-r-- 1 2201110432 2201110432  361 Nov 25 11:09 STRU_READIN_ADJUST.cif
-rw-rw-r-- 1 2201110432 2201110432  196 Nov 25 11:09 STRU_SIMPLE.cif
-rw-rw-r-- 1 2201110432 2201110432 3.4K Nov 25 11:09 warning.log
```
Then, just do the same calculation with the OUT directory. when calculation is done,  one can detect the size of wavefunction files and charge files in the same way
```bash
(base) [2201110432@wm2-login01 wfc]$ ll -h OUT.ABACUS/
total 48M
-rw-rw-r-- 1 2201110432 2201110432  25K Nov 25 11:11 INPUT
-rw-rw-r-- 1 2201110432 2201110432 168K Nov 25 11:12 istate.info
-rw-rw-r-- 1 2201110432 2201110432  13K Nov 25 11:11 kpoints
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_10.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_11.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_12.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_13.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_14.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_15.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_16.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_17.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_18.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_19.txt
-rw-rw-r-- 1 2201110432 2201110432 617K Nov 25 11:12 LOWF_K_1.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_20.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_21.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_22.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_23.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_24.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_25.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_26.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_27.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_28.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_29.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_2.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_30.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_31.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_32.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_33.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_34.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_35.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_36.txt
-rw-rw-r-- 1 2201110432 2201110432 617K Nov 25 11:12 LOWF_K_37.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_38.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_39.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_3.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_40.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_41.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_42.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_43.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_44.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_45.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_46.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_47.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_48.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_49.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_4.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_50.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_51.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_52.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_53.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_54.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_55.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_56.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_57.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_58.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_59.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_5.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_60.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_61.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_62.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_63.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_64.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_65.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_66.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_67.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_68.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_69.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_6.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_70.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_71.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_72.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_7.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_8.txt
-rw-rw-r-- 1 2201110432 2201110432 622K Nov 25 11:12 LOWF_K_9.txt
-rw-rw-r-- 1 2201110432 2201110432 189K Nov 25 11:12 running_scf.log
-rw-rw-r-- 1 2201110432 2201110432 1.6M Nov 25 11:12 SPIN1_CHG.cube
-rw-rw-r-- 1 2201110432 2201110432 1.6M Nov 25 11:12 SPIN2_CHG.cube
-rw-rw-r-- 1 2201110432 2201110432  361 Nov 25 11:11 STRU_READIN_ADJUST.cif
-rw-rw-r-- 1 2201110432 2201110432  196 Nov 25 11:11 STRU_SIMPLE.cif
-rw-rw-r-- 1 2201110432 2201110432 3.4K Nov 25 11:12 warning.log
```
We can find that ONLY the wavefunction file grow larger to 2 times of the original.

It is surely not good because the wavefunction files will grow larger and larger, due to when using ASE-ABACUS calculation like optimization, NEB or Dimer, the wavefunction files output and read-in will be done at every Ion step.

The problem seems to be in the output way of `out_wfc_lcao 1`, which seems to lay in the line 327 -> 368 in `source/module_hamilt_lcao/hamilt_lcaodft/local_orbital_wfc.cpp`. 
```cpp
    if (out_wfc_lcao && myid == 0)
    {
        std::stringstream ss;
        if (GlobalV::out_app_flag)
        {
            if (out_wfc_lcao == 1)
            {
                ss << GlobalV::global_out_dir << "LOWF_K_" << ik + 1 << ".txt";
            }
            else if (out_wfc_lcao == 2)
            {
                ss << GlobalV::global_out_dir << "LOWF_K_" << ik + 1 << ".dat";
            }
        }
        else
        {
            if (out_wfc_lcao == 1)
            {
                ss << GlobalV::global_out_dir << istep << "_"
                   << "LOWF_K_" << ik + 1 << ".txt";
            }
            else if (out_wfc_lcao == 2)
            {
                ss << GlobalV::global_out_dir << istep << "_"
                   << "LOWF_K_" << ik + 1 << ".dat";
                   std::cout << __LINE__ << " " << ss.str() << std::endl;
            }
        }
        if (out_wfc_lcao == 1)
        {
            ModuleIO::write_wfc_nao_complex(ss.str(), ctot, ik, kvec_c[ik], ekb, wg);
        }
        else if (out_wfc_lcao == 2)
        {
            ModuleIO::write_wfc_nao_complex(ss.str(), ctot, ik, kvec_c[ik], ekb, wg, true);
        }
        for (int i = 0; i < GlobalV::NBANDS; i++)
        {
            delete[] ctot[i];
        }
        delete[] ctot;
    }
```

So can this problem be fixed? It seems not a hard work

### Task list for Issue attackers (only for developers)

- [X] Reproduce the performance issue on a similar system or environment.
- [X] Identify the specific section of the code causing the performance issue.
- [X] Investigate the issue and determine the root cause.
- [X] Research best practices and potential solutions for the identified performance issue.
- [x] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by QuantumMisaka** [comment]
Will be fixed by #3264

**Comment by QuantumMisaka** [comment]
Fixed
