### ISSUE TITLE
Energy derivative with respect to spherical Bessel coefficients

### ISSUE THREAD

**Issue by jinzx10** [deepmodeling/abacus-develop#3267]
### Background

As a systematic way to improve numerical atomic orbitals, it was proposed that energy might be used as an alternative to spillage in the generation. For optimization efficiency, energy derivatives with respect to orbital parameters are required. 

### Describe the solution you'd like

Given that radial functions remain superpotitions of truncated (and smoothed) spherical Bessel functions, the following functionalities will be implemented:
1. a new option to read numerical atomic orbitals from a "spherical Bessel coefficients file";
2. energy derivative with respect to spherical Bessel coefficients;
3. (optional) relaxation with respect to spherical Bessel coefficients.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [X] Review and understand the proposed feature and its importance.
- [X] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by hongriTianqi** [comment]
#2243

**Comment by hongriTianqi** [comment]
#1795
