### ISSUE TITLE
in scan begin, cannot find LATTICE_PARAMETERS block in any correct INPUT&STRU&KPT for MD simulation

### ISSUE THREAD

**Issue by gradencapaldi** [deepmodeling/abacus-develop#3290]
### Describe the bug

When I ran the same set of INPUT&STRU&KPT case in the morning,  it succeeded in 100 steps calculations. but when I tried this afternoon, it stuck at two positions:
Position 1:
MAKE THE DIR         : OUT.C_nve_2/
MAKE THE STRU DIR    : OUT.C_nve_2/STRU/
Position 2:
 -------------------------------------------
 STEP OF MOLECULAR DYNAMICS : 0
 -------------------------------------------
 START CHARGE      : atomic
 DONE(28.0408    SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    

And the warning information was given as below:
In SCAN_BEGIN, can't find: LATTICE_PARAMETERS block.
 AUTO_SET NBANDS to 70
      Processor           Atom
              1             24
              2             24
              3             24
              4             24
                            startmag_type = 2
                       charge from rho_at = 3.99303
                         charge should be = 4
 Warning: negative or imaginary starting charge :  neg = -0.000329686 ima = 1.95167e-08 SPIN = 0

 SETUP ATOMIC RHO FOR SPIN 1
                 Electron number from rho = 64
           total electron number from rho = 64
                                should be = 64
                 charge before normalized = 64.0000000000001
                 charge after normalized = 64

### Expected behavior

It should have run as successfully as it did this morning.
And it should have no warning of "In SCAN_BEGIN, can't find: LATTICE_PARAMETERS block." in any circumstances when the STRU file is correctly formated.

### To Reproduce

The case documents are uploaded as below:
[C_md.zip](https://github.com/deepmodeling/abacus-develop/files/13538394/C_md.zip)

### Environment

the abacus was installed in the Linux via conda:
CentOS Linux release 7.9.2009 (Core)
gcc (GCC) 12.2.0

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [X] Label the issue with relevant tags.
- [X] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [X] Fix the bug.
- [X] Test the fix.
- [X] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment]
@gradencapaldi I downloaded the append files and find the two parameters in `INPUT`:
```
pseudo_dir             ../SG15_ONCV_v1.0_upf
orbital_dir            ../SG15-Version1p0__StandardOrbitals-Version2p0
```
You should delete them or set to:
```
pseudo_dir             ./
orbital_dir            ./
```
As you have provided orb and psp files in the current directory.

**Comment by hongriTianqi** [comment]
It is running with the latest code:
```
 ----------------------------------- INIT VEL ---------------------------------------
 RANDOM VEL ACCORDING TO INITIAL TEMPERATURE: 300 K
 ------------------------------------- DONE -----------------------------------------
 -------------------------------------------
 STEP OF MOLECULAR DYNAMICS : 0
 -------------------------------------------
 START CHARGE      : atomic
 DONE(4.60028    SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GE1    -2.479369e+03  0.000000e+00   1.711e-01  7.926e+00  
 GE2    -2.481188e+03  -1.818987e+00  2.838e-02  6.167e+00  
 GE3    -2.481163e+03  2.502787e-02   1.059e-02  6.174e+00  
 GE4    -2.481148e+03  1.464648e-02   4.853e-03  6.178e+00  
```
May you update abacus and try again?

**Comment by gradencapaldi** [comment]
> @gradencapaldi I downloaded the append files and find the two parameters in `INPUT`:
> 
> ```
> pseudo_dir             ../SG15_ONCV_v1.0_upf
> orbital_dir            ../SG15-Version1p0__StandardOrbitals-Version2p0
> ```
> 
> You should delete them or set to:
> 
> ```
> pseudo_dir             ./
> orbital_dir            ./
> ```
> 
> As you have provided orb and psp files in the current directory.

Actually, I did not put the pseudopotential and orbital files at the same directory as the INPUT&STRU&KPT files in my local environment. I packed them in the same folder and uploaded here only for the sake of easily handling for the visitors.

**Comment by gradencapaldi** [comment]
> It is running with the latest code:
> 
> ```
>  ----------------------------------- INIT VEL ---------------------------------------
>  RANDOM VEL ACCORDING TO INITIAL TEMPERATURE: 300 K
>  ------------------------------------- DONE -----------------------------------------
>  -------------------------------------------
>  STEP OF MOLECULAR DYNAMICS : 0
>  -------------------------------------------
>  START CHARGE      : atomic
>  DONE(4.60028    SEC) : INIT SCF
>  ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
>  GE1    -2.479369e+03  0.000000e+00   1.711e-01  7.926e+00  
>  GE2    -2.481188e+03  -1.818987e+00  2.838e-02  6.167e+00  
>  GE3    -2.481163e+03  2.502787e-02   1.059e-02  6.174e+00  
>  GE4    -2.481148e+03  1.464648e-02   4.853e-03  6.178e+00  
> ```
> 
> May you update abacus and try again?

Yes. After updating abacus to the latest version, the calculation was successfully completed. There might be a bug in a certain previous abacus version and it had been highly possibly fixed already. Thanks for your attention anyway!

**Comment by sunliang98** [comment]
The warning "In SCAN_BEGIN, can't find: LATTICE_PARAMETERS block." should be removed in the right case.
