### ISSUE TITLE
A standard format for orbital parameter file

### ISSUE THREAD

**Issue by jinzx10** [deepmodeling/abacus-develop#3315]
### Background

For the sake of https://github.com/deepmodeling/abacus-develop/issues/3267 (energy derivative with respect to spherical Bessel coefficients of NAO), it is required to read orbital parameters (like spherical Bessel coefficients) as an alternative to numerical atomic orbitals from file.  So far, such coefficients are available from the orbital-generation programs SIAB & PTG(+dpsi) as ORBITAL_RESULTS.txt, yet their content & format has a few things that need to be addressed:

1. Assuming that we stick to
 -- linear combinations of spherical Bessel functions with fixed node, and
 -- gaussian smoothing at the cutoff, 
apart from the weight of each spherical Bessel function, we still need the cutoff radius as well as the smoothing parameter to determine the radial function. Currently, neither program writes the smoothing parameter to ORBITAL_RESULTS.txt, and only SIAB's output involves rcut. Ideally, such file should include such information to completely determine the orbital.
2. Currently, spherical Bessel coefficients of the second/third/... zeta-orbital do not agree with the numerical atomic orbital files generated by the programs. This is probably due to the extra orthogonalization procedure between optimization and file generation, where ONLY the numerial radial functions are orthonormalized; spherical Bessel coefficients are not updated accordingly. Even though orbitals eventually span the same space, such discrepancy could still lead to confusion.

### Describe the solution you'd like

I hope the orbital parameter file could address the two issues above. In particular, I hope there could be a standard format which 
- contains all information needed to determine the orbital;
- has spherical Bessel coefficients that are consistent with the numerical orbital orbital file.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [X] Review and understand the proposed feature and its importance.
- [X] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.
