### ISSUE TITLE
Feature:  Pythonization of math_sphbes in Module Base

### ISSUE THREAD

**Issue by jieli-matrix** [deepmodeling/abacus-develop#3361]
### Background

In reference to Issue #3207, our progress with the pyabacus project involves propagating it from the inception of the two-center integral module. While attempting to bind [math_sphbes](https://github.com/deepmodeling/abacus-develop/blob/develop/source/module_base/math_sphbes.h), it appears that there exist multiple implementations for the same mathematical operation.

```code
/**
     * @brief spherical bessel jl(qr)
     * 
     * @param msh [in] number of grid points
     * @param r [in] radial grid
     * @param q [in] k_radial
     * @param l [in] angular momentum
     * @param jl [out] jl spherical bessel function
     */
    static void Spherical_Bessel
    (
        const int &msh,
        const double *r,
        const double &q,
        const int &l,
        double *jl
    );

```

and

```code
//! computes the values of l-th order spherical Bessel function at q*r[ir]
    static void sphbesj(const int n,           //!< [in] number of r grid points
                        const double* const r, //!< [in] r grid
                        const double q,        //!< [in] wave vector
                        const int l,           //!< [in] order of the spherical Bessel function
                        double* const jl       //!< [out] results
    );

```

Both of these implementations actually perform the same operation. As I conducted a numerical precision test of both functions in #2958, the results suggest that the `sphbesj` implemented by @jinzx10  should be prioritized. Furthermore, relocating redundant code will streamline the development process of pyabacus.

I've raised this issue to investigate the potential risks associated with removing redundant code in `math_sphbes`. If developers are still utilizing the old implementation in the current codebase, please consider replacing it with the newer implementation.

### Describe the solution you'd like

Related developers give their feedback about modification of `math_sphbes`.

### Task list only for developers

- [X] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [X] Review and understand the proposed feature and its importance.
- [X] Research on the existing solutions and relevant research articles/resources.
- [X] Discuss with the team to evaluate the feasibility of implementing the feature.
- [X] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by jieli-matrix** [comment]
Precision test reports can be seen in [test workflow](https://deepmodeling-activity.github.io/abacus-test.github.io/index.html?pname=mathlib/mathlib), where the precision error bound can achieve **1e-2** in the old implementation.

**Comment by jinzx10** [comment]
Hi @jieli-matrix , I have a few comments:
1. math_sphbes.h not only contains functions to compute spherical Bessel functions, but also its derivative and zeros. Could you also make numerical benchmark tests on those functions?
2. As far as I know, there are two other independent implementations of spherical Bessel function in ABACUS:
     - module_base/sph_bessel_recursive.h (d1 & d2)
     - module_cell/module_paw/paw_sphbes.cpp
   
    These two implementations are not designed to be standalone functions to get j_l(x) alone: the first one has an internal cache to save previously computed values in order to optimize Simpson-based spherical Bessel transform, and the second one combines j_l and its derivative into one function. Such functionalities are not readily available from sphbesj. Moreover, paw_sphbes might contain a specific implementation that mimicks ABINIT for numerical reproducibility, which we'd better not change. Nevertheless, I think it is still good if we can have some numerical benchmark tests to verify the robustness of these two implementations.
3. Is it possible to add some performance test? (e.g. the time spent to make 10^7 evaluations)

**Comment by jieli-matrix** [comment]
OK, I will add some numerical benchmark & performance tests on derivative and zeros of Spherical Bessel functions. I was wondering is there any best practice of performance tests in ABACUS for mathematical functions? cc: @jinzx10

**Comment by jinzx10** [comment]
@jieli-matrix Not yet for performance tests. So far performance tests do not have a high priority (at least lower than pythonization) so there's plenty of time to plan & design.

Numerical tests for zeros can be done by evaluating the tested sphbesj at those computed zeros. I think the new sphbes_zeros already has such unit test; the original Spherical_Bessel_Roots does not. 

There are several ways to evaluate the derivatives, some rely on the evaluation of sphbesj, some do not. I have no idea which one would be the best - or maybe either would be fine - hence some test might be helpful. 

I think there's no need to worry about these extra tests too much at this stage; None of these is as important as pythonization unless some code is considered highly suspicious and shall be replaced immediately. Functions to evaluate derivatives or zeros are more or less simple procedures built upon the basic spherical Bessel functions.

**Comment by jieli-matrix** [comment]
I have added some precision tests in `math_sphbes`. Maybe we can replace the old implementation with the new one in `math_sphbes` with such test results and  push the propagation of pythonization of `math_sphbes` first? We can leave two other independent implementations for future.

**Comment by jieli-matrix** [comment]
Besides, I think it is important to add performance tests and set some good practice for ABACUS. Maybe [Google Test Benchmark](https://github.com/google/benchmark) is a good start. Is there any comment for technical routes? cc: @jinzx10 @dyzheng @caic99

**Comment by jieli-matrix** [comment]
Closed as #3475 merged.
