### ISSUE TITLE
Precision control of output files is needed to be carefully treated

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3373]
### Background

I find the output Hamiltonian and overlap matrix only have 6 effective digits, it is totally unacceptable if one wants to take those output to do further calculations.
For example:
```
18 (-1.50326,0) (4.46914,0) (-3.28481e-16,0) (1.95059e-16,0) (-7.98403e-17,0) (2.88036e-16,0) (1.86356e-16,0) (-4.61516e-17,0) (-4.32783e-16,0) (1.46984e-16,0) (-1.62144e-16,0) (-2.03556e-15,0) (-1.27209e-17,0) (5.02742e-16,0) (-4.38881e-17,0) (-1.51387e-16,0) (1.11222e-15,0) (1.38894e-17,0)
 (-3.05509,0) (2.11989e-17,0) (4.61383e-17,0) (6.19135e-17,0) (2.59249e-18,0) (-2.3117e-16,0) (1.16641e-16,0) (6.78698e-16,0) (2.00255e-16,0) (5.85197e-16,0) (1.47233e-15,0) (3.88638e-16,0) (-7.64126e-16,0) (-8.26202e-17,0) (-2.80536e-16,0) (-2.43889e-15,0) (-1.68655e-16,0)
 (0.126354,0) (4.95724e-17,0) (-6.12906e-17,0) (-0.030999,0) (6.31155e-17,0) (3.23631e-16,0) (2.97596e-16,0) (3.12531e-16,0) (-1.81261e-16,0) (-5.17598e-16,0) (4.24933e-16,0) (-1.12707e-17,0) (1.8761e-16,0) (1.59436e-16,0) (2.22748e-16,0) (1.28586e-16,0)
 (0.126354,0) (-8.4471e-17,0) (1.71536e-16,0) (-0.030999,0) (7.37519e-17,0) (-6.90566e-17,0) (1.77442e-16,0) (5.5707e-16,0) (-2.02445e-17,0) (3.52812e-16,0) (-5.24806e-17,0) (9.19677e-17,0) (8.32667e-17,0) (9.98433e-18,0) (-5.62118e-17,0)
 (0.126354,0) (1.69023e-16,0) (-2.40431e-17,0) (-0.030999,0) (6.66211e-17,0) (1.7722e-16,0) (3.77183e-16,0) (-1.81969e-16,0) (1.39157e-17,0) (-7.0912e-17,0) (-3.94649e-17,0) (-1.56358e-17,0) (1.25812e-16,0) (-1.48904e-16,0)
 (0.292143,0) (-1.58866e-16,0) (3.6083e-16,0) (-1.9818e-16,0) (-1.12369e-16,0) (-4.31837e-16,0) (-6.18798e-16,0) (-3.6646e-16,0) (1.93884e-16,0) (2.33634e-16,0) (2.68179e-16,0) (-1.10602e-16,0) (-2.48499e-16,0)
 (0.292143,0) (3.82129e-16,0) (-6.37514e-18,0) (1.95913e-16,0) (-4.83554e-17,0) (-3.36811e-16,0) (-1.32841e-16,0) (-3.71358e-17,0) (-2.21787e-16,0) (1.56125e-16,0) (-6.91302e-17,0) (5.23671e-16,0)
 (0.292143,0) (-9.25624e-17,0) (6.09864e-17,0) (-8.19894e-17,0) (-6.66265e-16,0) (2.77104e-16,0) (1.90547e-16,0) (-1.03216e-16,0) (1.11037e-16,0) (-4.4115e-16,0) (3.44398e-16,0)
 (-2.16763,0) (8.01739e-17,0) (-4.73681e-16,0) (-3.22428e-16,0) (3.7494e-16,0) (0.0437756,0) (-2.56411e-17,0) (-3.71429e-16,0) (-4.09808e-16,0) (-2.61663e-16,0)
 (-2.19337,0) (-4.91858e-16,0) (-2.85104e-16,0) (1.13744e-15,0) (3.31034e-16,0) (-0.0818216,0) (5.66545e-16,0) (6.19362e-17,0) (-7.94207e-17,0)
 (-2.19337,0) (3.46064e-17,0) (1.24518e-16,0) (-5.54657e-17,0) (5.61971e-16,0) (-0.0818216,0) (5.29612e-17,0) (-3.86442e-16,0)
 (-2.16763,0) (5.42604e-16,0) (-1.07113e-16,0) (-6.42633e-16,0) (3.33959e-16,0) (0.0437756,0) (-2.92626e-16,0)
 (-2.19337,0) (-1.70645e-16,0) (4.0538e-16,0) (-3.4748e-18,0) (-3.91397e-16,0) (-0.0818216,0)
 (0.529637,0) (2.49776e-16,0) (1.06774e-16,0) (2.09379e-16,0) (5.0555e-17,0)
 (0.407278,0) (1.91305e-16,0) (7.12858e-17,0) (7.07766e-16,0)
 (0.407278,0) (-2.18958e-17,0) (8.063e-16,0)
 (0.529637,0) (-1.22081e-16,0)
 (0.407278,0)
```

### Describe the solution you'd like

Formatter library will be used to solve this issue, also formatter will try to support complex number output and corresponding real and imag part formatting.

### Task list only for developers

- [x] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [x] Review and understand the proposed feature and its importance.
- [x] Research on the existing solutions and relevant research articles/resources.
- [x] Discuss with the team to evaluate the feasibility of implementing the feature.
- [x] Create a design document outlining the proposed solution and implementation details.
- [x] Get feedback from the team on the design document.
- [x] Develop the feature following the agreed design.
- [x] Write unit tests and integration tests for the feature.
- [x] Update the documentation to include the new feature.
- [x] Perform code review and address any issues.
- [x] Merge the feature into the main branch.
- [x] Monitor for any issues or bugs reported by users after the feature is released.
- [x] Address any issues or bugs reported by users and continuously improve the feature.
