### ISSUE TITLE
CompareFile.py as a component of integrated test result analysis is not programmed in a way general enough

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3385]
### Describe the bug

Especially for function IsComplex, it can parse complex (0.123456,0.123456) but cannot parse properly if there is any whitespace in parenthsis. This barriers the alignment between columns by formatter library.

### Expected behavior

I will fix it later.

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [X] Steps to reproduce.
- [X] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment]
Do you have any comment? @pxlxingliang

**Comment by pxlxingliang** [comment]
Script ompareFile.py is used to compare two files, and check if they are same or not, in the integrate test.
For current tests, it is already applicable enough, and if there is any demand in future, we can improve this script.

**Comment by WHUweiqingzhou** [comment]
> Script ompareFile.py is used to compare two files, and check if they are same or not, in the integrate test. For current tests, it is already applicable enough, and if there is any demand in future, we can improve this script.

@kirk0830

**Comment by kirk0830** [comment]
> Script ompareFile.py is used to compare two files, and check if they are same or not, in the integrate test. For current tests, it is already applicable enough, and if there is any demand in future, we can improve this script.

Yes I have plan to improve it a little bit if it block something. Temporarily close, open when needed explicitly
