### ISSUE TITLE
Feature: pack-up QO python packages to `abacus2qo` for user easy use

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3462]
### Background

Presently QO Python-end implements as a collection of codes, which is not easy to use.

### Describe the solution you'd like

pack up QO codes into one package, so that user can use
```bash
python3 setup.py install
```
to import QO Python codes elsewhere without copying them everytime

### Task list only for developers

- [x] Notice possible changes of behavior
- [x] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [x] Review and understand the proposed feature and its importance.
- [x] Research on the existing solutions and relevant research articles/resources.
- [x] Discuss with the team to evaluate the feasibility of implementing the feature.
- [x] Create a design document outlining the proposed solution and implementation details.
- [x] Get feedback from the team on the design document.
- [x] Develop the feature following the agreed design.
- [x] Write unit tests and integration tests for the feature.
- [x] Update the documentation to include the new feature.
- [x] Perform code review and address any issues.
- [x] Merge the feature into the main branch.
- [x] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.
