### ISSUE TITLE
abacus should have the ability to calculate electronic conductivity of solid materials as accurately as possible

### ISSUE THREAD

**Issue by gradencapaldi** [deepmodeling/abacus-develop#3469]
### Background

At present, abacus have the choive of "cal_cond" to calculate the electronic conductivity of disordered materials (warm dense metal, for example), which is based on Kubo-Greenwood formula. However, this method is not suitable for the conductivity calculation of ordered materials (crystals at room temperature, for example), and phonon-electron scattering calculation would be more accurate as to have been adapted in EPW. To date, abacus has not been conneted to EPW or released other methods. So,  we hope the abacus team consider the promotion of eletronic conductivity calculation of ordered solid materials at room temperature in the near future.

### Describe the solution you'd like

The new released version of abacus will enable the eletronic conductivity calculation of ordered solid materials at room temperature.

### Task list only for developers

- [X] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [X] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [X] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [X] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [X] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [X] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [X] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
Thanks for your feedback. We will consider about it.

**Comment by WHUweiqingzhou** [comment]
@gradencapaldi ,
Since the calculations of electron-electron conductivity with constant relaxation time approximation (CRTA) only requires the information of band structure. From my opinion, there are one practical way if you want to calculate electronic conductivity, namely:
1. calculate electronic ground state from ABACUS
2. use the interface between ABACUS and Wannier90 to interpolate the band structure with a dense enough k-grid.
3. use Boltztrap2 to read the output from Wannir90 to get electronic conductivity.

If you want to include not only electron-electron interaction, but also electron-phonon interaction. It is a totally different story, which require electron-phonon interaction matrix $g(m,n,k)$.

**Comment by WHUweiqingzhou** [comment]
You can try to calculate electron-electron conductivity with constant relaxation time approximation (CRTA) by using PYATB, which has good interface with ABACUS. see more in [PYATB](https://abacus.ustc.edu.cn/2023/0403/c28297a597399/page.htm).
