### ISSUE TITLE
error in GPU calculation

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#3531]
### Describe the bug

In below testing, some of examples suffer the error in GPU calculation:
```
-------------------------------------------
 SELF-CONSISTENT : 
 -------------------------------------------
 START CHARGE      : atomic
 DONE(20.9218    SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
WARNING: Total thread number on this node mismatches with hardware availability. This may cause poor performance.
Info: Local MPI proc number: 1,OpenMP thread number: 1,Total thread number: 1,Local thread limit: 48
cuBLAS Assert: CUBLAS_STATUS_INVALID_VALUE /abacus-develop/source/module_hsolver/kernels/cuda/math_kernel_op.cu 719
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
```

https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.90-33aeb7

[gpu.zip](https://github.com/deepmodeling/abacus-develop/files/14003499/gpu.zip)

Another problem is the efficiency. The GPU did not have a significant acceleration.
<img width="381" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/91927439/d3654110-d27a-4ce2-9b7c-b0d2ec511bd2">
where, DCU means calculation on Sugon 4DCU+32CPU, CPU means calculated by bohrium c32_m128_cpu (2.56 yuan/hour), and the GPU means calculated by BOHRIUM "c6_m60_1 * NVIDIA 4090" (5.5 yuan/hour). 

  | DCU | CPU | GPU
-- | -- | -- | --
BNC | 327 | 483 | 481
CuS | 1387 | 2544 | 1529
HClO | 831 | 466 | 1038
LiLaH1 | 310 | 302 | 421
LiLaH2 | 319 | 280 | 543
MgAl1 | 587 | 1038 | 694
MgAl2 | 681 | 1294 | 805
MgLi | 337 | 606 | 456
NB | 346 | 527 | 457
Na | 849 | 1674 |  
PtAuAg | 2521 | 5975 |  
Si | 239 | 289 | 330
WRe | 3581 | 8098 |  
YTiO | 1032 | 1907 | 1286
Zn | 1290 | 2949 |  
Zr | 1054 | 2327 | 1511

The price of GPU is double of CPU, but the total time is longer than half, and even longer for some case.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [x] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by denghuilu** [comment]
Same as #3548 .
