### ISSUE TITLE
Json array support is needed.

### ISSUE THREAD

**Issue by grysgreat** [deepmodeling/abacus-develop#3583]
### Background

At present, the json feature in abacus only supports object and numbers and strings, and lacks support for arrays

### Describe the solution you'd like

The array in rapidjson is encapsulated in a way that makes it easy to call in abacus.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [x] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [x] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
