### ISSUE TITLE
Multiple Compilation Warnings in Clang Compiler

### ISSUE THREAD

**Issue by denghuilu** [deepmodeling/abacus-develop#3592]
### Describe the Code Quality Issue

Such as: 
```
[ 91%] Building CXX object source/CMakeFiles/device.dir/module_hamilt_pw/hamilt_pwdft/kernels/wf_op.cpp.o
/workspaces/abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/wavefunc_in_pw.cpp:327:13: warning: taking the absolute value of unsigned type 'bool' has no effect [-Wabsolute-value]
                                                                        if(fabs(j-L+0.5<1e-4)) continue;
                                                                           ^
/workspaces/abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/wavefunc_in_pw.cpp:327:13: note: remove the call to 'fabs' since unsigned values cannot be negative
                                                                        if(fabs(j-L+0.5<1e-4)) continue;
                                                                           ^~~~
/workspaces/abacus-develop/source/module_hamilt_lcao/hamilt_lcaodft/wavefunc_in_pw.cpp:327:13: warning: implicit conversion turns floating-point number into bool: 'double' to 'bool' [-Wimplicit-conversion-floating-point-to-bool]
                                                                        if(fabs(j-L+0.5<1e-4)) continue;
```

### Task list for Issue attackers (only for developers)

- [X] Identify the specific code file or section with the code quality issue.
- [X] Investigate the issue and determine the root cause.
- [X] Research best practices and potential solutions for the identified issue.
- [X] Refactor the code to improve code quality, following the suggested solution.
- [X] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.
