### ISSUE TITLE
Unsatisfactory precision of spherical Bessel basis overlap matrix <jY|jY>

### ISSUE THREAD

**Issue by jinzx10** [deepmodeling/abacus-develop#3618]
### Details

In spherical-Bessel-based orbital generation, an important quantity is the overlap matrix between pseudo-atomic orbitals of the form

$$
\phi_{lmq}(\mathbf{r}) = j_l(\theta_q^lr/r_{cut})  Y_{lm}(\hat{r})
$$

where $j_l$ is the $l$-th order spherical Bessel function, $\theta_q^l$ is the $q$-th zero of $j_l$ and $r_{cut}$ is the cutoff radius. Given the above form, pseudo-atomic orbitals centered on the same atom should be orthogonal to each other. In particular, orbitals with the same $(l, m)$ but different $q$ are mutually orthogonal due to (see, e.g., Arfken et al, Mathematical Methods for Physicists, 7ed, p.704)

$$
\int_{0}^{r_{cut}} j_l(\theta_p^l/r_{cut}) j_l(\theta_q^l/r_{cut}) r^2 \textrm{d}r = \frac{r_{cut}^3}{2}[j_{l+1}(\theta_p^l)]^2 \delta_{pq}
$$

When generating orbitals, ABACUS computes the above overlap integral in a plane wave basis (see module_io/numerical_basis.cpp and module_io/bessel_basis.cpp). It was found that the overlaps computed this way are merely accurate up to 2-3 digits. Take $r_{cut}=6$, $l=0$ as an example, here's what I find for the diagonal elements ($p=q$ in the above formula):

```
abacus =  [11.2286333   2.76279049  1.21788338  0.68794165  0.43991652  0.30545505
  0.22389927  0.17117827  0.13542846  0.10935793  0.09027062  0.07595007
  0.0645185   0.05555011  0.04834646  0.04229492  0.0371663   0.0324635
  0.01803246]

exact =  [10.94268783  2.73567196  1.2158542   0.68391799  0.43770751  0.30396355
  0.22332016  0.1709795   0.13509491  0.10942688  0.09043544  0.07599089
  0.06474963  0.05583004  0.04863417  0.04274487  0.03786397  0.03377373
  0.03031215]
```

Relative errors are usually larger for those with large wave numbers and/or higher angular momentum. For $l=2$,

```
abacus =  [2.99362726e+00 1.26277216e+00 7.01621082e-01 4.45421465e-01
 3.08077783e-01 2.25262960e-01 1.72001003e-01 1.35937846e-01
 1.09673248e-01 9.05111864e-02 7.60977649e-02 6.46332924e-02
 5.56446757e-02 4.84185160e-02 4.23436108e-02 3.72098421e-02
 3.24975816e-02 1.84669827e-02 1.48580134e-03]

exact =  [2.95984447 1.25833013 0.69716037 0.44309456 0.30655182 0.22471412
 0.17179542 0.13560378 0.10976051 0.09066319 0.07615163 0.0648663
 0.05591676 0.04869996 0.04279569 0.03790384 0.03380544 0.0303377
 0.02737752]
```
As shown above, the relative error of the last element is huge.

Orthogonality isn't well preserved either. For instance, the overlap between $l=0, p=0$ and $l=0, p=0, 1, ...18$ is found to be

```
[ 1.12286333e+01 -1.89601178e-02  6.16002275e-03 -2.81478429e-03
   2.08540528e-03 -1.42883893e-03  1.09471966e-03 -7.79775262e-04
   6.00822362e-04 -4.47178256e-04  3.19165797e-04 -2.41705073e-04
   1.60822425e-04 -9.85552866e-05  2.98149927e-05  2.63160566e-05
  -9.46393546e-05  1.97200773e-04 -5.76675434e-04]
```

which should be all zero except the first element.

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [X] Identify the specific section of the code causing the performance issue.
- [X] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by WHUweiqingzhou** [comment]
@jinzx10,
do you have plan to fix it by yourself?

**Comment by kirk0830** [comment]
> @jinzx10, do you have plan to fix it by yourself?

@WHUweiqingzhou This finding may indicate the class `Numerical Basis` and its auxiliary class `Bessel Basis` need kind of serious refactor, might be scheduled by us two, I think.

**Comment by jinzx10** [comment]
@kirk0830 and I just identified a bug in the present code when gradients are involved. Given $\phi(\mathbf{r})=j_l(\theta_q^lr/r_{cut}) Y_{lm}(\hat{r})$, we have the following analytical expression

$$
\int \nabla \phi(\mathbf{r}) \cdot \nabla\phi(\mathbf{r}) \mathrm{d}\mathbf{r} = -\int \phi(\mathbf{r}) \nabla^2\phi(\mathbf{r}) \mathrm{d}\mathbf{r} = (\theta_q^l/r_{cut})^2 \int \phi^2(\mathbf{r}) \mathrm{d}\mathbf{r} = \frac{r_{cut}}{2}[\theta_q^l j_{l+1}(\theta_q^l)]^2  
$$

However, we find that the output by ABACUS is off some constant factor, e.g. ($l=0$)

```
abacus =  [31.261222  30.6673419 30.3009588 30.3821705 30.3524474 30.3468881
 30.268335  30.2093757 30.2381669 30.1304069 30.0733397 30.0957342
 29.9850919 29.916493  29.8621116 29.6869    29.3939643 28.6837382
 17.178798 ]

exact (deriv) =  [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
```

After digging into the code, we find that the problem might results from cal_gpow in module_io/numerical_basis.cpp. When calculating the inner product between orbital gradients in plane wave basis, the |G|^2 factor calculated by cal_gpow misses its unit ($2\pi/a$). In the above case the lattice constant is 20, which leads to a missing factor of $(10/\pi)^2\approx 10.13$. We believe this is very likely to be the root of the discrepancy above.
