### ISSUE TITLE
Question: can present numerical atomic orbital always reproduce band gap of PW calculation in theoretical aspect?

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3624]
### Details

Recently I realize the released version of numerical atomic orbital for ABACUS lcao calculation only use occupied bands as reference, by either explicitly specifying number of bands to refer, or set to `auto`.
However, I am concerned about whether this generation strategy is correct theoretically. If not always true, an alternative way to define the keyword `auto` for determing number of bands to refer might be 50-50, say set number of bands to refer to double of the number of occupied bands, I guess.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [x] Understand the problem or question described by the user.
- [x] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [x] Identify the root cause or provide clarification on the user's question.
- [x] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
no matter what answer will be here, I plan to add band structure reproduction test in ABACUS-Pseudopot-Nao-Square

**Comment by kirk0830** [comment]
Seems this question has no certain answer, just empirically the band gap estimation seems not go wrong.
However, it is better to generate orbitals including empty states.

**Comment by kirk0830** [comment]
Seems this question has no certain answer, just empirically the band gap estimation seems not go wrong.
However, it is better to generate orbitals including empty states.

**Comment by hongriTianqi** [comment]
There is some clue that including unoccupied bands in orbital generation might increase convergence and correctness of systems with excited magnetic moments.
LiCoO test using orbitals without unoccupied bands:
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.113-7142e5

This result shows 1 Co4+ with large spin, 206 scf steps to converge.

LiCoO test using orbitals including 3 unoccupied bands in dimer and 11 unoccupied bands in trimer.
https://app.bohrium.dp.tech/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.113-59ee47

This result shows 3 Co4+ with large spin, 137 scf steps to converge.
