### ISSUE TITLE
Notes: projected orbital selection in QO calculated from LCAO may be highly nontrivial 

### ISSUE THREAD

**Issue by kirk0830** [deepmodeling/abacus-develop#3640]
### Describe the Code Quality Issue

# Related issues
Connected with reported problem of Quaisatomic Orbital (QO) implementation: #3632 #3484
# Theoretical background
QO method is for finding subspace from a space spanned by states calculated from DFT which is relatively large. It is expected that QO can extract subspace composed of bands of interest. However, the projection from the large space to the subspace might be a non-trivial task.
### General
- $H_{\mu\nu}(\mathbf{k})$: element of Hamiltonian matrix in representation of ABACUS numerical atomic orbitals (NAOs) at $\mathbf{k}$-point: $H_{\mu\nu}(\mathbf{k}) =\langle\phi_{\mu}(\mathbf{k}) |\hat{H} |\phi_{\nu}(\mathbf{k})\rangle$
- $\phi_{\mu}(\mathbf{k})$: numerical atomic orbital (NAO) at $\mathbf{k}$-point
- $\mu,\nu$: indices of NAOs
- $\mathbf{k}$: wave vector, $\mathbf{k} = (k_x, k_y, k_z)$, representing one certain kind of translational symmetry
- $\hat{H}$: Hamiltonian operator
- $\hat{P}$: projection operator
- $\hat{P} =\sum_{\mu\nu} |\phi_{\mu}\rangle\langle\phi_{\nu} |$  
Similarly the overlap matrix $S_{\mu\nu}(\mathbf{k}) =\langle\phi_{\mu}(\mathbf{k}) |\phi_{\nu}(\mathbf{k})\rangle$ is defined.  
- $|\psi_n(\mathbf{k})\rangle$: Bloch state at $\mathbf{k}$-point
- $n$: band index
- $E_n(\mathbf{k})$: energy of Bloch state $|\psi_n(\mathbf{k})\rangle$

### QO-specific
Also should define things related to the subspace.  
- $|A_\mu\rangle$: Atom-centered orbital that should be constructed manually.
More specifically, the atom-centered orbital in real space in cell $\mathbf{R}$ is $|A_{\mu}(\mathbf{R})\rangle$, and the corresponding reciprocal space representation is $|A_{\mu}(\mathbf{k})\rangle =\frac{1}{\sqrt{N_\text{cell}}}\sum_{\mathbf{R}} e^{i\mathbf{k}\cdot\mathbf{R}} |A_{\mu}(\mathbf{R})\rangle$.
- $|Q_{\mu}\rangle$: Quasiatomic orbital (QO) constructed from atom-centered orbitals. Correspondingly, $|Q_{\mu}(\mathbf{k})\rangle =\frac{1}{\sqrt{N_\text{cell}}}\sum_{\mathbf{R}} e^{i\mathbf{k}\cdot\mathbf{R}} |Q_{\mu}(\mathbf{R})\rangle$
- $\hat{P}_{\text{QO}}$: projection operator to the subspace spanned by QOs
Can also define Hamiltonian and overlap matrix in QO representation, in k-space and R counterparts.
- $H_{\mu\nu}^{\text{QO}}(\mathbf{k}) =\langle Q_{\mu}(\mathbf{k}) |\hat{H} | Q_{\nu}(\mathbf{k})\rangle$
- $S_{\mu\nu}^{\text{QO}}(\mathbf{k}) =\langle Q_{\mu}(\mathbf{k}) | Q_{\nu}(\mathbf{k})\rangle$  
Additionally the overlap between NAO and atom-centered orbital is,
- $S_{\mu\nu}^{\phi A}(\mathbf{k}) =\langle\phi_{\mu}(\mathbf{k}) | A_{\nu}(\mathbf{k})\rangle$  

In ABACUS, the Hamiltonian and overlap matrix in NAO representation is calculated and output to file, along with the NAO-atom-centered orbital overlap matrix. In Python code, QOs are constructed and Hamilontian, overlap matrices are calculated.

## Derivation
QO is defined to be calculated in the following way:  
$|Q_{\mu}(\mathbf{R})\rangle=\sum_{\mathbf{k}}{\sum_{n}{|\varphi_{n}(\mathbf{k})\rangle\langle\varphi_{n}(\mathbf{k})|A_{\mu}(\mathbf{R})\rangle}}$
where $|A_{\mu}(\mathbf{R})\rangle$ is atom-centered orbital in real space. The overlap between QO in realspace is obviously to be:
$S_{\mu\nu}^{\mathrm{QO}}(\mathbf{R})=\sum_{\mathbf{k}}{\sum_n{\langle A_{\mu}(\mathbf{0})|\varphi_n(\mathbf{k})\rangle\langle\varphi_n(\mathbf{k})|A_{\nu}(\mathbf{R})\rangle}}$
, of which the physical meaning is clear: the overlap between QOs in real space is the that of atom-centered orbital represented in space of $\{\varphi_n(\mathbf{k})\}$. It is the same for Hamiltonian matrix in QO representation but this time write in matrix form:  
$\mathbf{H}^{QO}\left(\mathbf{R}\right)=\left[\mathbf{D}\left(\mathbf{k}\right)\mathbf{S}^{\phi A}\left(\mathbf{k}\right)\right]^{\dagger}\mathbf{H}\left(\mathbf{k}\right)\left[\mathbf{D}\left(\mathbf{k}\right)\mathbf{S}^{\phi A}\left(\mathbf{k}\right)\right]$
where $\mathbf{D}\left(\mathbf{k}\right)$ is density matrix in $\{\varphi_n(\mathbf{k})\}$ space, and $\mathbf{S}^{\phi A}\left(\mathbf{k}\right)$ is overlap matrix between NAO and atom-centered orbital.  
However $\{\varphi_n(\mathbf{k})\}$ and $\{\psi_n(\mathbf{k})\}$ are not the same. The latter is subspace of the former, the rest of the former is constructed from atom-centered orbitals, which more specifically speaking are those cannot be represented by $\{\psi_n(\mathbf{k})\}$, and treated as empty states introduced. Keep in mind there must be orthogonality between solved occupied states and introduced empty states, thus to get the correct set of empty states, from atom-centered orbitals, one should remove the occupied states from the set of atom-centered orbitals:
$|A_{\mu}^{\text{empty}}\rangle = |A_{\mu}\rangle-\sum_{n}{|\varphi_{n}\rangle\langle\varphi_{n} | A_{\mu}\rangle}$
Orthogonality should also be kept between introduced empty states, this is guranateed by explicit diagonalization of overlap matrix between empty states.  
Remember the dimension of QO (or say the subspace) is the same as the number of atom-centered orbitals, therefore the number of empty states ($Nc$) plus dimension of manually selected subspace spanned by $\{\psi_n(\mathbf{k})\}$ ($Nb$) should be the same as the number of atom-centered orbitals ($Nq$), thus only $Nq-Nb=Nc$ empty states are needed to be introduced, which in actual implementation only the $Nc$ eigenvectors with largest eigenvalues are kept.  
Combining $\{\psi_n(\mathbf{k})\}$ with empty states, the set of $\{\varphi_n(\mathbf{k})\}$ is complete, and the density matrix $\mathbf{D}\left(\mathbf{k}\right)$ can be constructed.

### Basic
In ABACUS, two different ways to construct atomic orbitals are implemented: `pswfc` and `hydrogen`. The former use pseudo-wavefunction from pseudopotential file, while the latter directly construct hydrogen-like (single-electron) raidal function with Laguerre Polynomials.  The band reproduction result is poor (blue circles are eigenvalues solved from eigenequation in rep. of QO, lines are result of LCAO):  
(`pswfc`, use all pswfcs for projection)  
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/aac4dde3-5ee6-4be4-bf52-cf916e7aaff7)
At all other kpoints, diagonalization fails due to non-positive-definite of QO overlap.  
Change kpoint mesh from 9*9*9 to 5*5*5 or 7*7*7:  
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/53ff1e21-4ccf-40fb-b917-67a5ad6fa7c6)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/08169c07-4ca2-428a-a18e-e7ca4a54f429)
Change `pswfc` to `hydrogen`, the strategy for generating orbitals set to `minimal-nodeless`, for Si will produce 1s, 2p and 3d orbitals (nodeless radial functions, generate to nmax the principle quantum number):  
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/b37c8282-99f3-49f7-947c-433a7f8a44b6)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/d1fc65a6-4310-47f9-9432-5319ebda3551)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/47001a95-8b94-4bf4-917d-2905153367e7)
Change to `minimal-valence`, for Si generate 3s, 3p and 3d orbitals:  
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/897921a9-2735-4c7d-8a16-87713855add7)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/fefb1585-312a-4651-9439-e3b0933f3252)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/2b038f8d-96c7-440b-b91e-bc06c075fd17)
Change to `energy-valence`, for Si generate 3s and 3p orbitals:  
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/a3b047bd-6c30-45a0-aefc-78a25e626af5)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/09a74669-8f77-43d4-80d2-e0f8c1749003)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/15acf5d1-5c99-4e05-a94a-8dbb6f3a4f3c)
### Update
- change the method for finding eigenvals and eigenvecs of overlap between empty states to SVD  
- reduce the dimension of matrices in QO rep. according to one manually set threshold (canonical diagonalization)  
For `pswfc`:  
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/029cd156-48a3-4c4e-8460-6507d73297f0)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/7bfc8e4f-4829-4c71-be01-7fc53d6928a4)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/b49b0951-0729-4251-b79b-1ebf71434341)
For `hydrogen` with `minimal-nodeless`:  
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/a5fed33c-2cd8-4a01-8fd6-cc9bd2f99af0)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/c0e72fea-d345-49d9-a368-89862ad8a5a3)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/ebb7dae7-033f-40f7-866f-20c49664d9bc)
For `hydrogen` with `minimal-valence`:  
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/f5a92e81-2cf9-4381-97f8-f2e0ee193672)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/f8ab2f53-73dc-4ff9-8041-168cde423e9d)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/96c50c56-6de0-4a14-9e00-45d469768aa5)
For `hydrogen` with `energy-valence`:  
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/65db5525-0f07-4065-a1be-ab6e1466bc3d)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/02c15b77-76a4-4f99-89b6-2757b414347a)
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/bcefbf47-cd33-412d-8abc-ebb578bc4d61)

### Task list for Issue attackers (only for developers)

- [X] Identify the specific code file or section with the code quality issue.
- [X] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by kirk0830** [comment]
With single zeta orbitals, I get this result:
![img_v3_028i_e2f32a4a-20c3-4543-a1ad-537c5b5ed70g](https://github.com/deepmodeling/abacus-develop/assets/67682086/13947077-2c6c-45ab-aefb-fb665b4ea976)
Seems the space spanned by numerical atomic orbital is small and any other constructed orbital would have significant part of space spanned outside the space of numerical atomic orbitals.

**Comment by kirk0830** [comment]
I will submit a pull request to update ABACUS QO module and close this issue temporarily. cc. @QG-phys
