### ISSUE TITLE
Request: La and Ce pseudopotential and orbital (here to download La and Ce numerical atomic orbitals)

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#3762]
### Background

We need pseudopotential and orbital for Lanthanum elements, especially for La and Ce, which is not in the package of official website

### Describe the solution you'd like

 pseudopotential and related orbital for La and Ce

### Task list only for developers

- [X] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [x] Review and understand the proposed feature and its importance.
- [x] Research on the existing solutions and relevant research articles/resources.
- [x] Discuss with the team to evaluate the feasibility of implementing the feature.
- [x] Create a design document outlining the proposed solution and implementation details.
- [x] Get feedback from the team on the design document.
- [x] Develop the feature following the agreed design.
- [x] Write unit tests and integration tests for the feature.
- [x] Update the documentation to include the new feature.
- [x] Perform code review and address any issues.
- [x] Merge the feature into the main branch.
- [x] Monitor for any issues or bugs reported by users after the feature is released.
- [x] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by QuantumMisaka** [comment]
@kirk0830 I consider that this is a part of APNS project

**Comment by kirk0830** [comment]
> @kirk0830 I consider that this is a part of APNS project

@QuantumMisaka sure, yes, I will generate pseudopotential-orbital bundle for element La and Ce.

**Comment by kirk0830** [comment]
[La_SG15-v1.0_pseudopot-nao bundle.zip](https://github.com/deepmodeling/abacus-develop/files/14721421/La_SG15-v1.0_pseudopot-nao.bundle.zip)

**Comment by kirk0830** [comment]
[Ce_PD04.3+_f--core_pseudopot-nao_bundle.zip](https://github.com/deepmodeling/abacus-develop/files/14730807/Ce_PD04.3%2B_f--core_pseudopot-nao_bundle.zip)
(f electrons excluded)

**Comment by kirk0830** [comment]
[Ce_PD04.3+_f--core-icmod1_pseudopot-nao_bundle.zip](https://github.com/deepmodeling/abacus-develop/files/14732836/Ce_PD04.3%2B_f--core-icmod1_pseudopot-nao_bundle.zip)
(f electrons excluded)

**Comment by kirk0830** [comment]
[Ce_PD04.sp_pseudopot-nao_bundle.zip](https://github.com/deepmodeling/abacus-develop/files/14751835/Ce_PD04.sp_pseudopot-nao_bundle.zip)
(f electrons included)

**Comment by QuantumMisaka** [comment]
Good!

**Comment by zealrobot** [comment]
> > [@kirk0830](https://github.com/kirk0830) I consider that this is a part of APNS project
> 
> [@QuantumMisaka](https://github.com/QuantumMisaka) sure, yes, I will generate pseudopotential-orbital bundle for element La and Ce.

May I ask if there are pseudopotentials available for NAO that include all lanthanide elements with 4f electrons?

**Comment by kirk0830** [comment]
Hi, @zealrobot 

The full set of lanthanide orbitals for 4f-electrons included pseudopotentials is still under testing, we will publish them in near future.

Regards,
Yike
