### ISSUE TITLE
Reconstruct GPU Grid Integration

### ISSUE THREAD

**Issue by A-006** [deepmodeling/abacus-develop#3812]
### Describe the Code Quality Issue

the code in source/module_hamilt_lcao/module_gint/kernel/cuda doesn't follow the standards of software engineering,it should be designed to be more smlpilfy.It can be considered in the below aspects。
1. Short but clear varibales name should be used,the length of characterss are under 15
2. Functional Programming should be used,A function aim to implement only one functionality.
3. Consideration of programming standards requires clear, understandable, and tidy code.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [X] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [X] Update any relevant documentation, if necessary.
- [X] Submit a pull request with the refactored code and a description of the changes made.

**Comment by mohanchen** [comment]
Close this issue since it has been replaced by new ones.
