### ISSUE TITLE
Startup Timeout when HSE SCF used in large Fe5C2 surface system

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#3868]
### Details

When I was doing HSE SCF calculation in Fe5C2-510 surface, the SCF initialization process will time-out and throw an error within 7 min.

```
                              ABACUS v3.6.0

               Atomic-orbital Based Ab-initio Computation at UStc                    

                     Website: http://abacus.ustc.edu.cn/                             
               Documentation: https://abacus.deepmodeling.com/                       
                  Repository: https://github.com/abacusmodeling/abacus-develop       
                              https://github.com/deepmodeling/abacus-develop         
                      Commit: 5b263cbff (Wed Mar 27 18:42:03 2024 +0800)

 Mon Apr  1 14:53:54 2024
 MAKE THE DIR         : OUT.Fe5C2-510-HSE/
 RUNNING WITH DEVICE  : CPU / Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
 dft_functional readin is: hse
 dft_functional in pseudopot file is: PBE
 Please make sure this is what you need
 dft_functional readin is: hse
 dft_functional in pseudopot file is: PBE
 Please make sure this is what you need

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 Warning: the number of valence electrons in pseudopotential > 8 for Fe: [Ar] 3d6 4s2
 Pseudopotentials with additional electrons can yield (more) accurate outcomes, but may be less efficient.
 If you're confident that your chosen pseudopotential is appropriate, you can safely ignore this warning.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

 UNIFORM GRID DIM        : 125 * 160 * 240
 UNIFORM GRID DIM(BIG)   : 25 * 32 * 80
 DONE(0.302253   SEC) : SETUP UNITCELL
 DONE(0.312746   SEC) : INIT K-POINTS
 ---------------------------------------------------------
 Self-consistent calculations for electrons
 ---------------------------------------------------------
 SPIN    KPOINTS         PROCESSORS  NBASE       
 2       8               16          2628        
 ---------------------------------------------------------
 Use Systematically Improvable Atomic bases
 ---------------------------------------------------------
 ELEMENT ORBITALS        NBASE       NATOM       XC          
 C       2s2p1d-7au      13          36          
 Fe      4s2p2d1f-8au    27          80          
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 DONE(0.346184   SEC) : INIT PLANEWAVE
 -------------------------------------------
 SELF-CONSISTENT : 
 -------------------------------------------

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 8 PID 99132 RUNNING AT l02c12n1
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 9 PID 99133 RUNNING AT l02c12n1
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================
I_MPI_JOB_TIMEOUT = -1 second(s): job ending due to startup timeout
```

Is this time setting default in ABACUS? for HSE and other resource-requested calculation, how this threshold be change?

[Fe5C2_510_HSE_timeout.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14820653/Fe5C2_510_HSE_timeout.tar.gz)

ABACUS version: 3.6.0
Dependence: Intel OneAPI 2023.0 by intel toolchain
Hardware: Intel 8358 4nodes 64cpu/node 256mem/node
Running setting: OMP_NUM_THREADS=32 mpirun -np 8 abacus
LibRI: the latest version in gitee (loop3 branch)

### Task list for Issue attackers (only for developers)

- [X] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by QuantumMisaka** [comment]
@PeizeLin @WHUweiqingzhou Any comments ?

**Comment by WHUweiqingzhou** [comment]
@QuantumMisaka It looks like a Out-Of-Memory Issue. Could you try latest version again?

**Comment by QuantumMisaka** [comment]
@WHUweiqingzhou It's truly an OOM problem
```
srun: error: l05c35n1: task 2: Out Of Memory
srun: Terminating StepId=3040824.1
slurmstepd: error: *** STEP 3040824.1 ON l05c34n3 CANCELLED AT 2024-04-11T14:14:42 ***
slurmstepd: error: Detected 1 oom_kill event in StepId=3040824.1. Some of the step tasks have been OOM Killed.
```
which is originated by HSE, the newest abacus will have same OOM kill under the same computation resources, use more OMP threads can help.
