### ISSUE TITLE
Useful information: converging scf of lanthanides oxides surface with DFT+U (DFT+U SCF CANNOT converge in CeO2 surface)

### ISSUE THREAD

**Issue by QuantumMisaka** [deepmodeling/abacus-develop#3875]
### Details

We are trying to use DFT+U method in ABACUS 3.6.0 to do SCF in a CeO2 (110) surface 

<img width="297" alt="image" src="https://github.com/deepmodeling/abacus-develop/assets/43902832/5f0808a6-81b3-4638-8577-480e372abdef">

And the SCF cannot converge

Input and output files:

[CeO2-dft-u.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14823748/CeO2-dft-u.tar.gz)

ABACUS: 3.6.0
Dependencies: Intel-OneAPI 2023.2 by Intel-toolchain
Hardware: AMD EPYC 7b12
Pseudopotential and orbital : #3762 

### Task list for Issue attackers (only for developers)

- [X] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by kirk0830** [comment]
I have noted you used PD04.sp series pseudopotential, in which f-electron is explicitly treated. For other users previously have similar experience on ErO2 system, I would suggest you try 3+_f--core or 3+_f--core-icmod1 series counterpart, but convergence failure is indeed a problem.
If you are interested, let's take a look at the test result posted on APNS:
https://[kirk0830.github.io/ABACUS-Pseudopot-Nao-Square/pseudopotential/results/2024-03-27/Ce.html](https://kirk0830.github.io/ABACUS-Pseudopot-Nao-Square/pseudopotential/results/2024-03-27/Ce.html)
![Ce](https://github.com/deepmodeling/abacus-develop/assets/67682086/b91340e1-600f-4aa3-9564-d2ebb730c093)
What is first noted that GTH-LnPP1 can not get its converged value within range [0, 300] Ry of ecutwfc, but it might be okay because CP2K always uses a cutoff for planewave like 550 Ry or higher. In the log-plot, you can see convergence tendency of three properties, respectively:
![Ce_logplot](https://github.com/deepmodeling/abacus-develop/assets/67682086/f138165d-113b-43d5-ba01-67bea70b3ac3)
The pseudopotential you use corresponds to the yellow dashed line, the ecutwfc value for description of wavefunction (or charge density with 4*ecutwfc) getting consistent is higher than those of the other two PD04 series pseudopotentials, and the description seems to be unconvincing if ecutwfc lower than 50 Ry, since the tendency seems really unphysical.
What cannot obtained from the test result is the correctness of results with pseudopotentials. Presently I would suggest you perform cell-relax test with the same O pseudopot-nao bundle but different Ce pseudopot-nao bundle, then compare with experimental results. Then both precision and efficiency you will have a rough idea about them, on pseudopot-nao bundles you use.
**Please note that even for lcao calculation, the ecutwfc still have impact on accurancy of estimation (resolution) of charge density, if I remember correctly.**

**Comment by QuantumMisaka** [comment]
I'll try to spare some time to try this example with the newest PP-ORB

**Comment by QuantumMisaka** [comment]
The SCF of this example covnerged with this INPUT  and newest APNS
```
INPUT_PARAMETERS RUNNING ABACUS-DFT

#Parameters (1.General)
suffix                  ABACUS  # suffix of OUTPUT DIR
nspin                   2   #  1/2/4 4 for SOC
symmetry                1   #  0/1  1 for open, default
esolver_type            ksdft  # ksdft, ofdft, sdft, tddft, lj, dp
dft_functional          pbe  # same as upf file, can be lda/pbe/scan/hf/pbe0/hse
ks_solver             genelpa  # default for ksdft-lcao
vdw_method              none  # d3_bj
pseudo_dir              ../../
orbital_dir             ../../

#Parameters (2.Iteration)
calculation             scf # scf relax cell-relax md
ecutwfc                 150
scf_thr                 1e-7
scf_nmax                500
relax_nmax              400
relax_method            bfgs_trad  # cg, bfgs, cg_bfgs, sd, "fire"
force_thr_ev            0.02  # ev
stress_thr              1

#Parameters (3.Basis)
basis_type              lcao  # lcao or pw
kspacing              0.11 # replace KPT
# gamma_only            1  # 0/1, replace KPT

#Parameters (4.Smearing)
smearing_method         cold    # mp/gaussian/fixed mp-ISMAER=1 gau-ISMAER=0
smearing_sigma          0.01  # Rydberg, 0.008 for mp and 0.001-0.002 for gau

#Parameters (5.Mixing)
mixing_type             broyden  # pulay/broyden
mixing_beta             0.4  # for metal: 0.05-0.4
mixing_gg0              1.0  # only for metal
mixing_ndim             20

#Parameters (6.Calculation)
cal_force          1
cal_stress         1
out_stru           1  # print STRU in OUT
out_chg            0  # print CHG or not
out_bandgap        1
# out_mul            1  # print Mulliken charge and mag of atom in mulliken.txt

#Parameters (7. +U)
dft_plus_u    1
onsite_radius   3.0
orbital_corr    3   -1
hubbard_u    4.5  0.0
mixing_restart   1e-3
mixing_dmr     1
```
