### ISSUE TITLE
Need to collect the time consumption of each inner Lambda Loop in the DeltaSpin module.

### ISSUE THREAD

**Issue by RenguangLiu** [deepmodeling/abacus-develop#3979]
### Background

We need to know the time of each inner loop of Lambda in DeltaSpin printed to push forward further efficiency tests of this module.

### *Goals*
In today's screen print, the RMS would be printed for each inner loop. If we could know how many times the h-solve used or how much time it consumed in each Inner loop, then we could know the efficiency of the Deltaspin in this DFT case.

### *Example of the Screen Print*
```
===============================================================================
 GE3    -6.438892e+03  -1.511538e-01  9.959e-03  3.738e+00  
===============================================================================
Inner optimization for lambda begins ...
Covergence criterion for the iteration: 1.000e-09
initial lambda: 
ATOM 1         0.0000000000e+00    0.0000000000e+00    5.4474932560e-04
ATOM 2         0.0000000000e+00    0.0000000000e+00    5.4474932560e-04
initial spin: 
ATOM 1         0.0000000000e+00    0.0000000000e+00    2.0250319456e+00
ATOM 2         0.0000000000e+00    0.0000000000e+00    2.0250319456e+00
target spin: 
ATOM 1         0.0000000000e+00    0.0000000000e+00    2.6000000000e+00
ATOM 2         0.0000000000e+00    0.0000000000e+00    2.6000000000e+00
Step (Outer -- Inner) =  3 -- 1           RMS = 5.750e-01
Reach limitation of current step ( maximum gradient < 9.000e-01 in atom type 0 ), exit.
Step (Outer -- Inner) =  3 -- 2           RMS = 5.058e-01
alpha after restrict = -5.932e+00
boundary after = 3.000e+00
Reach limitation of current step ( maximum gradient < 9.000e-01 in atom type 0 ), exit.
after-optimization spin: (print in the inner loop): 
ATOM 1         0.0000000000e+00    0.0000000000e+00    3.4844981355e+00
ATOM 2         0.0000000000e+00    0.0000000000e+00    3.4844981352e+00
after-optimization lambda: (print in the inner loop): 
ATOM 1         0.0000000000e+00    0.0000000000e+00    1.4658737333e-02
ATOM 2         0.0000000000e+00    0.0000000000e+00    1.4658737333e-02
Inner optimization for lambda ends.
===============================================================================
 GE4    -6.438880e+03  1.237603e-02   5.144e-03  3.750e+00  
===============================================================================
Inner optimization for lambda begins ...
Covergence criterion for the iteration: 1.000e-09
initial lambda: 
ATOM 1         0.0000000000e+00    0.0000000000e+00    1.4658737333e-02
ATOM 2         0.0000000000e+00    0.0000000000e+00    1.4658737333e-02
initial spin: 
ATOM 1         0.0000000000e+00    0.0000000000e+00    2.0942352149e+00
ATOM 2         0.0000000000e+00    0.0000000000e+00    2.0942352150e+00
target spin: 
ATOM 1         0.0000000000e+00    0.0000000000e+00    2.6000000000e+00
ATOM 2         0.0000000000e+00    0.0000000000e+00    2.6000000000e+00
Step (Outer -- Inner) =  4 -- 1           RMS = 5.058e-01
Step (Outer -- Inner) =  4 -- 2           RMS = 2.686e+00
Step (Outer -- Inner) =  4 -- 3           RMS = 7.929e-01
Reach limitation of current step ( maximum gradient < 9.000e-01 in atom type 0 ), exit.
after-optimization spin: (print in the inner loop): 
ATOM 1         0.0000000000e+00    0.0000000000e+00    2.1077944879e+00
ATOM 2         0.0000000000e+00    0.0000000000e+00    2.1077944896e+00
after-optimization lambda: (print in the inner loop): 
ATOM 1         0.0000000000e+00    0.0000000000e+00   -1.8133779734e-02
ATOM 2         0.0000000000e+00    0.0000000000e+00   -1.8133779738e-02
Inner optimization for lambda ends.
```

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [X] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [X] Create a design document outlining the proposed solution and implementation details.
- [X] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by WHUweiqingzhou** [comment]
@hongriTianqi could you have a look?
