### ISSUE TITLE
Error when calculating DFT+U

### ISSUE THREAD

**Issue by lyonworton** [deepmodeling/abacus-develop#3987]
### Describe the bug

[FeO.zip](https://github.com/deepmodeling/abacus-develop/files/14978567/FeO.zip)
When I calculated the ground state of FeO using DFT+U on abacus, I wanted to get the result by calculating at symmetry=0 and expected to get a reasonable bandgap (about 1.9eV),but now after calculating the bandgap obtained is very unreasonable.

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [X] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment]
Hi @lyonworton, can you upload your results?

We have tested FeO previous, and the band gap is about 2.1 eV. You can check the results in https://bohrium.dp.tech/notebooks/52882361357

**Comment by lyonworton** [comment]
> Hi @lyonworton, can you upload your results?
> 
> We have tested FeO previous, and the band gap is about 2.1 eV. You can check the results in https://bohrium.dp.tech/notebooks/52882361357
Hi @pxlxingliang ,Can you help me see what's wrong with the document I'm typing, I've looked at the site you sent me and it doesn't match up!
[FeOresult.zip](https://github.com/deepmodeling/abacus-develop/files/14986364/FeOresult.zip)

**Comment by pxlxingliang** [comment]
Same issue with #4028

**Comment by WHUweiqingzhou** [comment]
Close this issue, and move related discussion to Issue #4028.
