### ISSUE TITLE
 Compilation fails when `USE_CUDA=ON` && `BUILD_TESTING=ON`

### ISSUE THREAD

**Issue by haozhihan** [deepmodeling/abacus-develop#4043]
### Describe the Testing Issue

When the `USE_CUDA` compilation option and the `BUILD_TEST` compilation option are turned on together, compilation will fail.

### Task list for Issue attackers (only for developers)

- [X] Understand the testing issue described by the developer.
- [X] Review the specific test case, expected and actual results, and any error messages.
- [X] Identify the root cause of the test failure or issue.
- [X] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [X] Implement a fix for the test failure or issue, or create a new test case if needed.
- [X] Verify that the fix resolves the testing issue and the test case passes.
- [X] Review and update any relevant documentation, such as test plans or user guides.
- [X] Ensure the testing issue is resolved and close the ticket.
- [X] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by haozhihan** [comment]
```
/usr/bin/ld: collect2: error: ld returned 1 exit status
make[2]: *** [source/module_hamilt_lcao/module_tddft/test/CMakeFiles/tddft_propagator_test.dir/build.make:328：source/module_hamilt_lcao/module_tddft/test/tddft_propagator_test] 错误 1
make[1]: *** [CMakeFiles/Makefile2:6438：source/module_hamilt_lcao/module_tddft/test/CMakeFiles/tddft_propagator_test.dir/all] 错误 2
libtddft_test_lib.a(tddft_test.cpp.o): in function `MPIInit()':
/home/haozhihan/abacus-develop/source/module_hamilt_lcao/module_tddft/test/tddft_test.cpp:29: undefined reference to `Cblacs_pinfo'
/usr/bin/ld: /home/haozhihan/abacus-develop/source/module_hamilt_lcao/module_tddft/test/tddft_test.cpp:30: undefined reference to `Cblacs_get'
/usr/bin/ld: /home/haozhihan/abacus-develop/source/module_hamilt_lcao/module_tddft/test/tddft_test.cpp:32: undefined reference to `Cblacs_gridinit'
/usr/bin/ld: libtddft_test_lib.a(tddft_test.cpp.o): in function `main':
/home/haozhihan/abacus-develop/source/module_hamilt_lcao/module_tddft/test/tddft_test.cpp:47: undefined reference to `Cblacs_exit'
/usr/bin/ld: libtddft_test_lib.a(tddft_test.cpp.o): in function `MPIInit()':
/home/haozhihan/abacus-develop/source/module_hamilt_lcao/module_tddft/test/tddft_test.cpp:29: undefined reference to `Cblacs_pinfo'
/usr/bin/ld: /home/haozhihan/abacus-develop/source/module_hamilt_lcao/module_tddft/test/tddft_test.cpp:30: undefined reference to `Cblacs_get'
/usr/bin/ld: /home/haozhihan/abacus-develop/source/module_hamilt_lcao/module_tddft/test/tddft_test.cpp:32: undefined reference to `Cblacs_gridinit'
/usr/bin/ld: libtddft_test_lib.a(tddft_test.cpp.o): in function `main':
/home/haozhihan/abacus-develop/source/module_hamilt_lcao/module_tddft/test/tddft_test.cpp:47: undefined reference to `Cblacs_exit'
collect2: error: ld returned 1 exit status
make[2]: *** [source/module_hamilt_lcao/module_tddft/test/CMakeFiles/tddft_norm_psi_test.dir/build.make:296：source/module_hamilt_lcao/module_tddft/test/tddft_norm_psi_test] 错误 1
make[1]: *** [CMakeFiles/Makefile2:6382：source/module_hamilt_lcao/module_tddft/test/CMakeFiles/tddft_norm_psi_test.dir/all] 错误 2
/usr/bin/ld: libtddft_test_lib.a(tddft_test.cpp.o): in function `MPIInit()':
/home/haozhihan/abacus-develop/source/module_hamilt_lcao/module_tddft/test/tddft_test.cpp:29: undefined reference to `Cblacs_pinfo'
/usr/bin/ld: /home/haozhihan/abacus-develop/source/module_hamilt_lcao/module_tddft/test/tddft_test.cpp:30: undefined reference to `Cblacs_get'
/usr/bin/ld: /home/haozhihan/abacus-develop/source/module_hamilt_lcao/module_tddft/test/tddft_test.cpp:32: undefined reference to `Cblacs_gridinit'
/usr/bin/ld: libtddft_test_lib.a(tddft_test.cpp.o): in function `main':
/home/haozhihan/abacus-develop/source/module_hamilt_lcao/module_tddft/test/tddft_test.cpp:47: undefined reference to `Cblacs_exit'
[ 93%] Linking CXX executable read_wfc_pw_test
collect2: error: ld returned 1 exit status
make[2]: *** [source/module_hamilt_lcao/module_tddft/test/CMakeFiles/tddft_bandenergy_test.dir/build.make:296：source/module_hamilt_lcao/module_tddft/test/tddft_bandenergy_test] 错误 1
make[1]: *** [CMakeFiles/Makefile2:6354：source/module_hamilt_lcao/module_tddft/test/CMakeFiles/tddft_bandenergy_test.dir/all] 错误 2
collect2: error: ld returned 1 exit status
make[2]: *** [source/module_hamilt_lcao/module_tddft/test/CMakeFiles/tddft_upsi_test.dir/build.make:328：source/module_hamilt_lcao/module_tddft/test/tddft_upsi_test] 错误 1
make[1]: *** [CMakeFiles/Makefile2:6410：source/module_hamilt_lcao/module_tddft/test/CMakeFiles/tddft_upsi_test.dir/all] 错误 2
[ 93%] Linking CXX executable esolver_dp_test
[ 93%] Linking CXX executable io_output_log_test
[ 93%] Linking CXX executable orbital_equal_test
[ 93%] Built target basis_pw_k_serial
```

**Comment by WHUweiqingzhou** [comment]
@caic99 could you have a look?

**Comment by caic99** [comment]
> @caic99 could you have a look?

I have had this issue viewed but no ideas 😢

**Comment by WHUweiqingzhou** [comment]
@haozhihan, 
I notice this issue is self-assigned.
do you plan to fix it by yourself, or need more help?

**Comment by haozhihan** [comment]
I discovered this issue when I was planning to add GPU integration testing (#4033) with @dzzz2001. It is expected to be resolved together with @dzzz2001.

But I am currently fixing the convergence problem of `dav-subspace`, and this issue will be resolved in a few days. So, no help needed yet, thank you very much.

**Comment by haozhihan** [comment]
I found that this is due to an issue with my server environment, which has now been resolved. 

Thank you all !

**Comment by caic99** [comment]
@haozhihan maybe should be `BUILD_TESTING` 🤣

**Comment by haozhihan** [comment]
> @haozhihan maybe should be `BUILD_TESTING` 🤣

Sorry, I wrote the wrong title of this issue. It was correct when compiling. 🤣
