### ISSUE TITLE
Replace “lm->paraV” with “paraV” to simpifier parameters. 

### ISSUE THREAD

**Issue by A-006** [deepmodeling/abacus-develop#4101]
### Describe the Code Quality Issue

In moudle gint,the parameter lm->paraV can be repalce with ParaV。This way, the module lcaodft can be considered as an independent module.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Submit a pull request with the refactored code and a description of the changes made.
