### ISSUE TITLE
Total energy difference between ABACUS and VASP

### ISSUE THREAD

**Issue by Youhaojen** [deepmodeling/abacus-develop#4260]
### Details

Dear developers,

Thanks for the excellent work. I found the total energy difference between [ABACUS](https://github.com/deepmodeling/dpdata/blob/master/tests/abacus.scf/OUT.ch4/running_scf.log) and [VASP](https://github.com/deepmodeling/dpdata/blob/master/tests/poscars/OUTCAR.ch4.1step) from the dpdata example. As I understand it, the total energy in the ABACUS calculation is listed as `final etot` in `running_scf.log`, and dpdata retrieves the total energy from there. In the VASP calculation, dpdata gets the total energy with the tag `free energy TOTEN` from `OUTCAR`. Here, we can see that the total energy of CH4 calculated by VASP is 18.25453698 eV, while the total energy calculated by ABACUS is -219.649914042766 eV. I have no idea why both methods show such a significant difference in total energy.

Best,
Hao-Jen You

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [X] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
total energy depends on both basis set and pseudopotentials used, energy cannot be compared across these two fields.

**Comment by WHUweiqingzhou** [comment]
@Youhaojen,
Comparing the total energies from pseudopotential density functional calculations is not meaningful, whereas differences in energy have physical significance.
