### ISSUE TITLE
Questions about the default setting for md_pfirst

### ISSUE THREAD

**Issue by yiyangfu888** [deepmodeling/abacus-develop#4287]
### Details

The documentation mentioned that the default value for md_pfirst is -1. What does minus zero and above zero respectively stand for?

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [X] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [X] Test the updated documentation to ensure it is clear and accurate.
- [X] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

**Comment by YuLiu98** [comment]
Hi @yiyangfu888, a positive md_pfirst means that the cell tends to produce inward compression strain, while the negative value means the opposite.
