### ISSUE TITLE
Not using the standard CUDA syntax

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#4360]
### Describe the Code Quality Issue

[The standard syntax of using CUDA kernels](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#kernels) is `<<<...>>>`
But the following code in ABACUS does not use the standard CUDA <<< >>> syntax, which sometimes leads to compilation errors,
![image](https://github.com/deepmodeling/abacus-develop/assets/25027983/c10685d6-7e23-4621-963f-5ddfbcf9c9b8)

https://github.com/deepmodeling/abacus-develop/blob/10c52815ba01e0bd1b96bca4ac5eeefc4b247135/source/module_hsolver/kernels/cuda/math_kernel_op.cu#L523
https://github.com/deepmodeling/abacus-develop/blob/10c52815ba01e0bd1b96bca4ac5eeefc4b247135/source/module_hsolver/kernels/cuda/math_kernel_op.cu#L542
https://github.com/deepmodeling/abacus-develop/blob/10c52815ba01e0bd1b96bca4ac5eeefc4b247135/source/module_hsolver/kernels/cuda/math_kernel_op.cu#L576
https://github.com/deepmodeling/abacus-develop/blob/10c52815ba01e0bd1b96bca4ac5eeefc4b247135/source/module_hsolver/kernels/cuda/math_kernel_op.cu#L593
https://github.com/deepmodeling/abacus-develop/blob/10c52815ba01e0bd1b96bca4ac5eeefc4b247135/source/module_hsolver/kernels/cuda/math_kernel_op.cu#L628
https://github.com/deepmodeling/abacus-develop/blob/10c52815ba01e0bd1b96bca4ac5eeefc4b247135/source/module_hsolver/kernels/cuda/math_kernel_op.cu#L645
https://github.com/deepmodeling/abacus-develop/blob/10c52815ba01e0bd1b96bca4ac5eeefc4b247135/source/module_hsolver/kernels/cuda/math_kernel_op.cu#L992
https://github.com/deepmodeling/abacus-develop/blob/10c52815ba01e0bd1b96bca4ac5eeefc4b247135/source/module_hsolver/kernels/cuda/math_kernel_op.cu#L1034
https://github.com/deepmodeling/abacus-develop/blob/10c52815ba01e0bd1b96bca4ac5eeefc4b247135/source/module_hsolver/kernels/cuda/math_kernel_op.cu#L1078
https://github.com/deepmodeling/abacus-develop/blob/10c52815ba01e0bd1b96bca4ac5eeefc4b247135/source/module_hsolver/kernels/cuda/math_kernel_op.cu#L1078
https://github.com/deepmodeling/abacus-develop/blob/10c52815ba01e0bd1b96bca4ac5eeefc4b247135/source/module_hsolver/kernels/cuda/math_kernel_op.cu#L1131
https://github.com/deepmodeling/abacus-develop/blob/10c52815ba01e0bd1b96bca4ac5eeefc4b247135/source/module_hsolver/kernels/cuda/math_kernel_op.cu#L1131

### Task list for Issue attackers (only for developers)

- [X] Identify the specific code file or section with the code quality issue.
- [X] Investigate the issue and determine the root cause.
- [X] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.
