### ISSUE TITLE
Using the memset() function without the <cstring> header file

### ISSUE THREAD

**Issue by LiuXiaohui123321** [deepmodeling/abacus-develop#4366]
### Describe the Code Quality Issue

Some code in ABACUS uses the `memset()` function, but does not include the `<cstring>` header file, which sometimes leads to compilation errors,
![image](https://github.com/deepmodeling/abacus-develop/assets/25027983/4e7e90a5-f070-4ef7-8f83-f5eab3e52bf5)

https://github.com/LiuXiaohui123321/abacus-develop/blob/e4b6cebeec6d5498d78170785d5a3ff3616d50cc/source/module_hamilt_lcao/module_gint/kernels/cuda/cuda_tools.cu#L87

### Task list for Issue attackers (only for developers)

- [X] Identify the specific code file or section with the code quality issue.
- [X] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.
