### ISSUE TITLE
Installation docs need to be updated for new OneAPI Toolkits

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#4653]
### Details

Intel® C++ Compiler Classic (icc) is deprecated and was discontinued in the oneAPI 2024.0 release. (See [Intel® C++ Compiler Classic Release Notes](https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-c-compiler-release-notes.html) )
Also, there are [slight differences in Directory Layout](https://www.intel.com/content/www/us/en/docs/oneapi/programming-guide/2024-2/use-the-setvars-and-oneapi-vars-scripts-with-linux.html) from 2024.0, which leads to changes in the way environment variables are set.
Current docs are no longer suitable to build with latest OneAPI Toolkits.  We need to update our installation documentation to reflect the recent changes in the Intel OneAPI 2024.x release.

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [X] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [X] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [X] Update the documentation to address the issue, following the suggested improvement.
- [X] Ensure the updated documentation adheres to the project's documentation standards.
- [X] Test the updated documentation to ensure it is clear and accurate.
- [X] Review and incorporate any relevant feedback from users or developers.
- [X] Publish the updated documentation and notify the issue reporter.

**Comment by QuantumMisaka** [comment]
@caic99 Do you have any comments?

Current toolchain is compatible with `icc` and `icx`, but `icx` will have problem in some platforms. 

For compile dependency and abacus from scratch by CMake, I also consider that the docs need to update for various environment (not only the latest one-API but also some lower version)

**Comment by mohanchen** [comment]
https://mcresearch.github.io/abacus-user-guide/abacus-oneapi.html
