### ISSUE TITLE
This error message indicates that the process with PID 237937 running on node g0408.para.bscc was forcibly terminated by signal 9 (Killed).

### ISSUE THREAD

**Issue by duousername1** [deepmodeling/abacus-develop#4703]
### Details

Running the initial dataset with the command `nohup dpgen init_bulk init.json machine.json 1>log 2>err&` currently encounters the following error. How can I resolve it?

1. The error message is: 
```
* * * * * *

 << Start SCF iteration.
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 237937 RUNNING AT g0408.para.bscc
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

3. The following are the input files:
STRU
ATOMIC_SPECIES
Ce  140.116  Ce-sp.PD04.PBE.UPF
Al   26.982  Al_ONCV_PBE-1.0.upf

NUMERICAL_ORBITAL
Ce_gga_150Ry_6au_6s3p3d3f2g.orb
Al_gga_7au_100Ry_4s4p1d.orb

LATTICE_CONSTANT
1.889726

LATTICE_VECTORS
7.953500000000  0.000000000000  0.000000000000
0.000000000000  7.953500000000  0.000000000000
0.000000000000  0.000000000000  7.953500000000

ATOMIC_POSITIONS
Direct

Ce
0.000
8
0.500000000000  0.000000000000  0.500000000000  1  1  1  mag  0.0
0.250000000000  0.250000000000  0.250000000000  1  1  1  mag  0.0
0.500000000000  0.500000000000  0.000000000000  1  1  1  mag  0.0
0.250000000000  0.750000000000  0.750000000000  1  1  1  mag  0.0
0.000000000000  0.000000000000  0.000000000000  1  1  1  mag  0.0
0.750000000000  0.250000000000  0.750000000000  1  1  1  mag  0.0
0.000000000000  0.500000000000  0.500000000000  1  1  1  mag  0.0
0.750000000000  0.750000000000  0.250000000000  1  1  1  mag  0.0

Al
0.000
16
0.125000000000  0.625000000000  0.125000000000  1  1  1  mag  0.0
0.125000000000  0.875000000000  0.375000000000  1  1  1  mag  0.0
0.375000000000  0.625000000000  0.375000000000  1  1  1  mag  0.0
0.375000000000  0.875000000000  0.125000000000  1  1  1  mag  0.0
0.125000000000  0.125000000000  0.625000000000  1  1  1  mag  0.0
0.125000000000  0.375000000000  0.875000000000  1  1  1  mag  0.0
0.375000000000  0.125000000000  0.875000000000  1  1  1  mag  0.0
0.375000000000  0.375000000000  0.625000000000  1  1  1  mag  0.0
0.625000000000  0.625000000000  0.625000000000  1  1  1  mag  0.0
0.625000000000  0.875000000000  0.875000000000  1  1  1  mag  0.0
0.875000000000  0.625000000000  0.875000000000  1  1  1  mag  0.0
0.875000000000  0.875000000000  0.625000000000  1  1  1  mag  0.0
0.625000000000  0.125000000000  0.125000000000  1  1  1  mag  0.0
0.625000000000  0.375000000000  0.375000000000  1  1  1  mag  0.0
0.875000000000  0.125000000000  0.375000000000  1  1  1  mag  0.0
0.875000000000  0.375000000000  0.125000000000  1  1  1  mag  0.0

INPUT.rlx
INPUT_PARAMETERS
calculation 	relax
ntype 		2
nbands 		200

ecutwfc                 100
scf_thr                 1e-7
scf_nmax                120

basis_type 	lcao
dft_functional 	PBE 
#gamma_only 	1
kspacing       0.11

mixing_type 	pulay
mixing_beta 	0.400000
smearing_method gaussian
smearing_sigma 	0.020000

relax_nmax	100
force_thr_ev	0.02
stress_thr	0.5

INPUT.md
INPUT_PARAMETERS
calculation 	md
ntype 		2
nbands 		200

ecutwfc                 100
scf_thr                 1e-7
scf_nmax                120

basis_type 	lcao
dft_functional 	PBE
gamma_only 	1

mixing_type 	pulay
mixing_beta 	0.400000
smearing_method gaussian
smearing_sigma 	0.020000

cal_force 	1
cal_stress	1

md_type		npt 
md_nstep	20
md_tfirst	10
md_dt	        1
chg_extrap	second-order

init.json
{
    "init_fp_style":    "ABACUS",
    "stages":           [1,2,3,4],
    "elements":		["Ce","Al"],
    "super_cell":   [1,1,1],
    "from_poscar":true,
    "from_poscar_path":	"./STRU",    
    "atom_masses":	[140.116,26.982],
    "potcars": 		["Ce-sp.PD04.PBE.UPF","Al_ONCV_PBE-1.0.upf"],
    "orb_files":	["Ce_gga_150Ry_6au_6s3p3d3f2g.orb","Al_gga_7au_100Ry_4s4p1d.orb"],
    "relax_incar": 	"./INPUT.rlx",
    "_relax_kpt":  	"./KPT",
    "md_incar":		"./INPUT.md",
    "_md_kpt":     	"./KPT",
    "md_nstep":		20,
    "scale":		[0.98,1.00],
    "skip_relax":	false,
    "pert_numb":	5,
    "pert_box":		0.03,
    "pert_atom":	0.005,
    "coll_ndata":	5000,
    "_comment":		"that's all"
}

machine.json
{
  "api_version": "1.0",
  "deepmd_version": "2.1.0",
  "train" :[
    {
      "command": "dp",
      "machine": {
        "batch_type": "DpCloudServer",
        "context_type": "DpCloudServerContext",
        "local_root" : "./",
        "remote_profile":{
          "email": "PRIVACYPROTECTION",
          "password": "PRIVACYPROTECTION",
          "program_id": *****,
            "input_data":{
                "api_version":2,
                "job_type": "container",
                "log_file": "00*/train.log",
                "grouped":true,
                "job_name": "train",
                "disk_size": 100,
                "scass_type":"c16_m62_1 * NVIDIA T4",
                "platform": "ali",
                "image_name":"registry.dp.tech/dptech/dpmd:2.2.8-cuda12.0",
                "on_demand":0
            }
        }
      },
      "resources": {
        "number_node":1,
        "local_root":"./",
        "cpu_per_node": 4,
        "gpu_per_node": 1,
        "queue_name": "GPU",
        "group_size": 1
      }
    }],
  "model_devi":
    [{
      "command": "lmp -i input.lammps -v restart 0",
      "machine": {
        "batch_type": "DpCloudServer",
        "context_type": "DpCloudServerContext",
        "local_root" : "./",
        "remote_profile":{
    	  "email": "PRIVACYPROTECTION",
          "password": "PRIVACYPROTECTION",
          "program_id": *****,
            "input_data":{
              "api_version":2,
              "job_type": "container",
              "log_file": "*/model_devi.log",
              "grouped":true,
              "job_name": "model_devi",
              "disk_size": 200,
              "scass_type":"c16_m62_1 * NVIDIA T4",
              "platform": "ali",
              "image_name":"registry.dp.tech/dptech/dpmd:2.2.8-cuda12.0",
              "on_demand":0
            }
        }
      },
      "resources": {
        "number_node": 1,
        "local_root":"./",
        "cpu_per_node": 4,
        "gpu_per_node": 1,
        "queue_name": "GPU",
        "group_size": 100
      }
    }],
  "fp":
    [{
      "command": "OMP_NUM_THREADS=8 mpirun -n 32 abacus",
      "machine": {
        "batch_type": "Lebesgue",
        "context_type": "LebesgueContext",
        "local_root" : "./",
        "remote_profile":{		
	    "email": "PRIVACYPROTECTION",
          "password": "PRIVACYPROTECTION",
          "program_id": *****,
            "keep_backup":true,
            "input_data":{
              "job_type": "container",
              "log_file": "task*/fp.log",
              "grouped":true,
              "job_name": "abacus",
              "disk_size": 200,
              "checkpoint_files": "sync_files",
              "checkpoint_time":30,
              "scass_type":"c128_m512_cpu",
              "platform": "ali",
              "image_name":"registry.dp.tech/dptech/abacus:3.7.0",
              "on_demand":0}
        }
      },
      "resources": {
        "group_size": 4,
        "local_root":"./",
        "source_list": ["/opt/intel/oneapi/setvars.sh"]
      }
    }
  ]
}
```

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [X] Understand the problem or question described by the user.
- [X] Check if the issue is a known problem or has been addressed in the documentation.
- [X] Test the issue or problem on a similar system or environment, if possible.
- [X] Identify the root cause or provide clarification on the user's question.
- [X] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [X] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [X] If the issue is related to code, consider implementing a fix or improvement (optional).
- [X] Review and incorporate any relevant feedback from users or developers.
- [X] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
I did not reproduce the crash, no matter serial or MPI/OMP parallel.
For other developers, please directly try with the following:
[issue4703.zip](https://github.com/user-attachments/files/16232560/issue4703.zip)

**Comment by kirk0830** [comment]
User feedbacks it is because the accidentally crash of Bohrium machine. Simply changing the machine the job runs on, the expected job can proceed smoothly.
