### ISSUE TITLE
Refactoring: Remove the non-functional 'pdiagh' Pointer in hsolver

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#4741]
### Description
Original design use pointer `pdiagh` in base class `HSolver` to manage different iteration solvers. Now that we migrate to object instance of iterative solvers, which is clearer and reduces risk of memory insecurity, `pdiagh` will be redundant and has no practical effect on the functionality of the class.
### Proposed Changes
Remove the 'pdiagh' pointer to clean up the code and prevent potential confusion for future maintainers.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [X] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by Cstandardlib** [comment]
C

**Comment by Cstandardlib** [comment]
Closed by #4875
