### ISSUE TITLE
Inconsistent interface of BLAS gemm

### ISSUE THREAD

**Issue by Cstandardlib** [deepmodeling/abacus-develop#4747]
### Describe the Code Quality Issue

The order of arguments of gemm_op(**m, n**, k) is not consistent with standard blas gemm(**n, m**, k)
```cpp
// source/module_hsolver/kernels/math_kernel_op.cpp
struct gemm_op<T, base_device::DEVICE_CPU>
{
    void operator()(const base_device::DEVICE_CPU* /*ctx*/,
                    const char& transa,
                    const char& transb,
                    const int& m,
                    const int& n,
                    const int& k,
                    const T* alpha,
                    const T* a,
                    const int& lda,
                    const T* b,
                    const int& ldb,
                    const T* beta,
                    T* c,
                    const int& ldc)
    {
        BlasConnector::gemm(transb, transa, n, m, k, *alpha, b, ldb, a, lda, *beta, c, ldc);
    }
};
```
```cpp
//source/module_base/blas_connector.h
// BlasConnector
static inline
	void gemm(const char transa, const char transb, const int m, const int n, const int k,
		const std::complex<double> alpha, const std::complex<double> *a, const int lda, const std::complex<double> *b, const int ldb,
		const std::complex<double> beta, std::complex<double> *c, const int ldc)
	{
		zgemm_(&transb, &transa, &n, &m, &k,
			&alpha, b, &ldb, a, &lda,
			&beta, c, &ldc);
    }
```

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [X] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by Cstandardlib** [comment]
The order of calling routine
```cpp
dgemm_(&transb, &transa, &n, &m, &k,
			&alpha, b, &ldb, a, &lda,
			&beta, c, &ldc);
```
is also strange.
The std lapack dgemm should be called as follows

[dgemm](https://netlib.org/lapack/explore-html/dd/d09/group__gemm_ga1e899f8453bcbfde78e91a86a2dab984.html#ga1e899f8453bcbfde78e91a86a2dab984) (transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)

**Comment by maki49** [comment]
This is the row-major version, the wrapper to multiply row-major matrices with a similar interface as multiplying col-major matrices.

The col-major version consistent with the standard fortran order can be found in `module_base/module_container/base/third_party/blas.h`.

**Comment by Cstandardlib** [comment]
> This is the row-major version, the wrapper to multiply row-major matrices with a similar interface as multiplying col-major matrices.
> 
> The col-major version consistent with the standard fortran order can be found in `module_base/module_container/base/third_party/blas.h`.

Get it, thanks!
