### ISSUE TITLE
!! CONVERGENCE HAS NOT BEEN ACHIEVED !! 

### ISSUE THREAD

**Issue by duousername1** [deepmodeling/abacus-develop#4821]
### Describe the bug

When running ABACUS with the following input parameters, the program encountered an error during the SCF calculation. The error messages are:

"!! CONVERGENCE HAS NOT BEEN ACHIEVED !!"
"2024-07-25 17:19:53,475 - INFO: job: b131ef03975b49cc0e0af19b716b0ebefcb0fbc3 13911562:job_group_id:12998244 terminated; fail_count is 1; resubmitting job"
"2024-07-25 17:19:53,828 - INFO: job: b131ef03975b49cc0e0af19b716b0ebefcb0fbc3 re-submit after terminated; new job_id is 13947468:job_group_id:12998244"
The input files are in the following compressed package.
[init_2.47CeAl2_NH4ClO4_c64_m512.zip](https://github.com/user-attachments/files/16407827/init_2.47CeAl2_NH4ClO4_c64_m512.zip)

### Expected behavior

ABACUS should complete the SCF calculation with errors.谢谢！！

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [X] Steps to reproduce.
- [X] Expected behavior.
- [X] Error message.
- [X] Environment details.
- [X] Additional context.
- [X] Assign a priority level (low, medium, high, urgent).
- [X] Assign the issue to a team member.
- [X] Label the issue with relevant tags.
- [X] Identify possible related issues.
- [X] Create a unit test or automated test to reproduce the bug (if applicable).
- [X] Fix the bug.
- [X] Test the fix.
- [X] Update documentation (if necessary).
- [X] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment]
@duousername1 there is no key word of "CONVERGENCE HAS NOT BEEN ACHIEVED" in your files, can you upload your result files?

**Comment by duousername1** [comment]
> @duousername1 there is no key word of "CONVERGENCE HAS NOT BEEN ACHIEVED" in your files, can you upload your result files?

[Uploading fp.log…]()

**Comment by dyzheng** [comment]
> > @duousername1 there is no key word of "CONVERGENCE HAS NOT BEEN ACHIEVED" in your files, can you upload your result files?
> 
> Uploading fp.log…

Hello, your link is this Issue, not your result file.

**Comment by duousername1** [comment]
> > > @duousername1 there is no key word of "CONVERGENCE HAS NOT BEEN ACHIEVED" in your files, can you upload your result files?
> > 
> > 
> > Uploading fp.log…
> 
> Hello, your link is this Issue, not your result file.

sorry。
[fp.log.zip](https://github.com/user-attachments/files/16409215/fp.log.zip)

**Comment by caic99** [comment]
> sorry。 [fp.log.zip](https://github.com/user-attachments/files/16409215/fp.log.zip)

@duousername1 There is a warning message at the very beginning:
WARNING: Total thread number(256) is larger than hardware availability(64).
The results may be INCORRECT. Please set the environment variable OMP_NUM_THREADS to a proper value.
Please make sure your setup is correct.

**Comment by caic99** [comment]
> [init_2.47CeAl2_NH4ClO4_c64_m512.zip](https://github.com/user-attachments/files/16407827/init_2.47CeAl2_NH4ClO4_c64_m512.zip)

In your `machine.json`:
```
      "command": "OMP_NUM_THREADS=8 mpirun -n 64 abacus",
              "scass_type":"c64_m512_cpu",
```
@duousername1 Maybe what you expect is `OMP_NUM_THREADS=8 mpirun -n 8 abacus`. [ref](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#run)

**Comment by kirk0830** [comment]
@QuantumMisaka do you have some suggestions on her input? 
```
INPUT_PARAMETERS
calculation 	relax
ntype 		6
nbands 		400

ecutwfc                 100
scf_thr                 1e-7
scf_nmax                120

basis_type 	lcao
dft_functional 	PBE 
#gamma_only 	1
kspacing       0.11

mixing_type 	pulay
mixing_beta 	0.400000
smearing_method gaussian
smearing_sigma 	0.020000

relax_nmax	100
force_thr_ev	0.02
stress_thr	0.5
```

**Comment by dyzheng** [comment]
Larger radius-cutoff (6au -> 8au) of Ce maybe improve the convergence.

`mixing_beta` is large and `smearing_sigma` is large, you can try other settings.

**Comment by duousername1** [comment]
Thank you for your response. I would like to confirm that

1、You mean that replacing the atomic orbital file Ce_gga_150Ry_6au_6s3p3d3f2g.orb with the corresponding atomic orbital file with an 8 cutoff radius will be beneficial for convergence.
2、Additionally, should the values of mixing_beta and smearing_sigma be slightly reduced?

mixing_type: pulay
mixing_beta: 0.400000
smearing_method: gaussian
smearing_sigma: 0.020000

I look forward to hearing from you.

**Comment by duousername1** [comment]
> Larger radius-cutoff (6au -> 8au) of Ce maybe improve the convergence.
> 
> `mixing_beta` is large and `smearing_sigma` is large, you can try other settings.
Thank you for your response. I would like to confirm that

1、You mean that replacing the atomic orbital file Ce_gga_150Ry_6au_6s3p3d3f2g.orb with the corresponding atomic orbital file with an 8 cutoff radius will be beneficial for convergence.
2、Additionally, should the values of mixing_beta and smearing_sigma be slightly reduced?

mixing_type: pulay
mixing_beta: 0.400000
smearing_method: gaussian
smearing_sigma: 0.020000

I look forward to hearing from you.

**Comment by caic99** [comment]
> @duousername1 Maybe what you expect is `OMP_NUM_THREADS=8 mpirun -n 8 abacus`. [ref](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#run)

@duousername1 I'm pretty confident that your setup of multithreading would lead to unconvergence. Would you correct them first, and test if there are further problems?

**Comment by duousername1** [comment]
> > @duousername1 Maybe what you expect is `OMP_NUM_THREADS=8 mpirun -n 8 abacus`. [ref](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#run)
> 
> @duousername1 I'm pretty confident that your setup of multithreading would lead to unconvergence. Would you correct them first, and test if there are further problems?

okay。thanks！I will test it immediately.

**Comment by duousername1** [comment]
> > > @duousername1 Maybe what you expect is `OMP_NUM_THREADS=8 mpirun -n 8 abacus`. [ref](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#run)
> > 
> > 
> > @duousername1 I'm pretty confident that your setup of multithreading would lead to unconvergence. Would you correct them first, and test if there are further problems?
> 
> okay。thanks！I will test it immediately.
With the settings OMP_NUM_THREADS=8 mpirun -n 8 abacus, it still did not converge. The compressed file contains the output。
[fp-2.log.zip](https://github.com/user-attachments/files/16421083/fp-2.log.zip)

**Comment by duousername1** [comment]
> Quote reply

With the settings OMP_NUM_THREADS=8 mpirun -n 8 abacus, it still did not converge. The compressed file contains the output。
[fp-2.log.zip](https://github.com/user-attachments/files/16421166/fp-2.log.zip)

Could you please take another look for me?    thanks @caic99

**Comment by duousername1** [comment]
> > @duousername1 Maybe what you expect is `OMP_NUM_THREADS=8 mpirun -n 8 abacus`. [ref](https://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html#run)
> 
> @duousername1 I'm pretty confident that your setup of multithreading would lead to unconvergence. Would you correct them first, and test if there are further problems?

"By the way, could you provide me with a Ce atomic orbital with a cutoff radius of 8 au?" thanks

**Comment by caic99** [comment]
> With the settings OMP_NUM_THREADS=8 mpirun -n 8 abacus, it still did not converge.

🤔 Seems this does not help... Sorry for that

**Comment by duousername1** [comment]
> > With the settings OMP_NUM_THREADS=8 mpirun -n 8 abacus, it still did not converge.
> 
> 🤔 Seems this does not help... Sorry for that

thank you very much！

**Comment by duousername1** [comment]
> Larger radius-cutoff (6au -> 8au) of Ce maybe improve the convergence.
> 
> `mixing_beta` is large and `smearing_sigma` is large, you can try other settings.

The atomic orbitals for Ce have not been changed. I adjusted the cutoff energy from 100 to 150, the mixing_beta from 0.4 to 0.3, and the smearing_sigma from 0.2 to 0.01. However, the system still has not converged. Could you help me with how to make further adjustments? @dyzheng  thanks
[fp-3.log.zip](https://github.com/user-attachments/files/16422032/fp-3.log.zip)



INPUT_PARAMETERS
calculation 	relax
ntype 		6
nbands 		400

ecutwfc                 150
scf_thr                 1e-7
scf_nmax                120

basis_type 	lcao
dft_functional 	PBE 
#gamma_only 	1
kspacing       0.11

mixing_type 	pulay
mixing_beta 	0.300000
smearing_method gaussian
smearing_sigma 	0.010000

relax_nmax	100
force_thr_ev	0.02
stress_thr	0.5

**Comment by duousername1** [comment]
[fp-4.log.zip](https://github.com/user-attachments/files/16423347/fp-4.log.zip)
Despite several parameter adjustments, the system still has not converged. The parameters from the most recent adjustment that did not converge are as follows:

INPUT_PARAMETERS
calculation 	relax
ntype 		6
nbands 		400

ecutwfc                 150
scf_thr                 1e-7
scf_nmax                120

basis_type 	lcao
dft_functional 	PBE 
#gamma_only 	1
kspacing       0.11

mixing_type 	pulay
mixing_beta 	0.0500000
smearing_method gaussian
smearing_sigma 	0.010000

relax_nmax	100
force_thr_ev	0.02
stress_thr	0.5

Please take another look at this. I would greatly appreciate  @dyzheng

**Comment by duousername1** [comment]
I tried the atomic orbitals corresponding to 8au and 10au yesterday and also modified the input files. 
INPUT_PARAMETERS
calculation 	relax
ntype 		6
nbands 		400

ecutwfc                 150
scf_thr                 1e-7
scf_nmax                120

basis_type 	lcao
dft_functional 	PBE 
#gamma_only 	1
kspacing       0.11

mixing_type 	pulay
mixing_beta 	0.0500000
smearing_method gaussian
smearing_sigma 	0.010000

relax_nmax	100
force_thr_ev	0.02
stress_thr	0.5

Unfortunately, it still did not converge. I would like to ask again if there are any other solutions. @dyzheng @kirk0830 @caic99 Once again, I express my sincerest gratitude.

**Comment by QuantumMisaka** [comment]
@duousername1 @dyzheng 
I tried this example for changing mixing_type, smearing_method and nspin, the convergence still cannot be reached. 
Also, by using `nspin 2`, the magmom will oscillate 
Is `nspin 1` correct for this calculation job ?

**Comment by duousername1** [comment]
> @duousername1 @dyzheng I tried this example for changing mixing_type, smearing_method and nspin, the convergence still cannot be reached. Also, by using `nspin 2`, the magmom will oscillate Is `nspin 1` correct for this calculation job ?

Thank you for your response. Based on the current situation, it is indeed necessary to consider the issue of spin polarization. You have been a great help. I will proceed to try calculating this system with spin=2. Thank you.

**Comment by duousername1** [comment]
> @duousername1 @dyzheng I tried this example for changing mixing_type, smearing_method and nspin, the convergence still cannot be reached. Also, by using `nspin 2`, the magmom will oscillate Is `nspin 1` correct for this calculation job ?

Can you send me your input file and output file for me to take a look at? Thank you @QuantumMisaka

**Comment by QuantumMisaka** [comment]
@duousername1 My INPUT:
```
INPUT_PARAMETERS
calculation     scf
ntype           6
nspin          2
nbands          400

ecutwfc                 200
scf_thr                 1e-7
scf_nmax                200

basis_type      lcao
dft_functional  pbe 
#gamma_only     1
kspacing       0.11

mixing_type     broyden
#mixing_beta    0.400000
smearing_method mp
smearing_sigma  0.010
mixing_ndim   20

relax_nmax      100
force_thr_ev    0.02
stress_thr      0.5
```
And my output:

[result.tar.gz](https://github.com/user-attachments/files/16468887/result.tar.gz)

Even the magnetic moments cannot reach to a stationary point, but the magnetic moments seems to be existed.

**Comment by WHUweiqingzhou** [comment]
I close this issue due to no further update from @duousername1. Please feel free to reopen it.
