### ISSUE TITLE
The unittests for DeePKS are not being compiled.

### ISSUE THREAD

**Issue by A-006** [deepmodeling/abacus-develop#5113]
### Describe the Testing Issue

When `BUILD_TESTING=ON` and `ENABLE_DEEPKS=ON` are used, the deepks unit tests should be compiled and executed. However, the current unit tests are commented out. Are there still any deepks unit tests? Will this affect the code quality?
![图片](https://github.com/user-attachments/assets/c38dd815-243f-48fa-87d5-9743e297d59e)

### Task list for Issue attackers (only for developers)

- [X] Understand the testing issue described by the developer.
- [X] Review the specific test case, expected and actual results, and any error messages.
- [X] Implement a fix for the test failure or issue, or create a new test case if needed.
- [X] Review and update any relevant documentation, such as test plans or user guides.

**Comment by xuan112358** [comment]
Now there is no deepks unit test being compiled. And many of the functions in the unit test are not consistent with the current code. 
I will try to update them and reopen the unit test for deepks.
