### ISSUE TITLE
The `CMakeLists.txt` for `module_device` has been commented out.

### ISSUE THREAD

**Issue by A-006** [deepmodeling/abacus-develop#5114]
### Describe the Code Quality Issue

The `CMakeLists.txt` for module_device in module_base is now commented out. It is written in the `CMakeLists.txt` in source, so there should be a module_device under the source folder, right?
![图片](https://github.com/user-attachments/assets/7bf9b694-457c-47ea-a11e-f802dfc4f20a)
The CMakeLists.txt in module_device is commented out, so it does not actually generate a linked library.
![图片](https://github.com/user-attachments/assets/66d10f6f-5673-419b-9aa7-e95273d8b9be)
The actual location of the device library.

### Task list for Issue attackers (only for developers)

- [X] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [X] Refactor the code to improve code quality, following the suggested solution.
- [X] Ensure the refactored code adheres to the project's coding standards.
- [X] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by WHUweiqingzhou** [comment]
@haozhihan could you have a look?

**Comment by haozhihan** [comment]
Yes, you are right. Currently `module-device` cannot generate a linkable library. When I wrote it, there was no need to generate a library. So I didn't write the corresponding cmake code. @A-006

**Comment by haozhihan** [comment]
But the location of `module-device` is in `module-base`. If you want `module-device` to generate a linkable library, you can write a cmakelist for it. @A-006
