### ISSUE TITLE
Feature: Should we change the default choice of `ks_solver` from `CG` to `DAV`

### ISSUE THREAD

**Issue by WHUweiqingzhou** [deepmodeling/abacus-develop#5407]
### Background

CG is less efficient than DAV.

### Describe the solution you'd like

Please discuss it,

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by Cstandardlib** [comment]
Now DAV(dav_subspace) seems to suffer from numerical instability (#5376) in some cases

**Comment by haozhihan** [comment]
Currently our PW basis set supports four iteration methods: `CG`, `BPCG`, `Davidson`, and `Dav_subspace`.

Currently the default iteration method of ABACUS is the `CG` method.

However, with the improvement of stability and computational efficiency of other methods, should we change the default iteration method to a method better than CG?

**Comment by haozhihan** [comment]
I think we should discuss the following questions.

- [ ] Comparison of the stability and efficiency of these four iteration methods (CG/BPCG/DAV/Dav_subspace) in different hardware (CPU/GPU/DCU) after a large number of test cases

- [ ] What is the default iteration method for other PW basis set DFT software in the world?

**Comment by mohanchen** [comment]
I would suggest using CG as default since it is more reliable. For example, the mixing usage of NLCC and USPP lead to the failure of Davidson diago method. If someone wants to run ABACUS faster, we could use multiple ways to let him/her konw that Davidson may be a better/more efficient option.
