### ISSUE TITLE
As the ecutwfc value increases, ETOT increases instead with basis type of lcao

### ISSUE THREAD

**Issue by braveSXG** [deepmodeling/abacus-develop#5598]
### Details

I used the list of ecutwfc to test for appropriate energy cutoff values: ecutwfc_values = [4, 6, 8, 10, 15, 20, 30, 40, 50, 60, 70, 80, 90, 100, 150]. The material is Ga. However, when the SCF tests are done, the result is just like this: as the ecutwfc values increase, ETOTs increase instead. In my opinion, the ETOEs usually decrease with the increment of ecutwfc. So can anyone help answer my questions? Thank you very much.

This is the results:

energy cutoff/Ry | ETOT/eV
4 | error
6 | -14444.68726
8 | -14389.93657
10 | -14334.65434
15 | -14295.94161
20 | -14301.49073
30 | -14295.68946
40 | -14293.07567
50 | -14292.97417
60 | -14293.02038
70 | -14293.01999
80 | -14293.02344
90 | -14293.02134
100 | -14293.02197
150 | -14293.01939

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [x] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [x] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by kirk0830** [comment]
in ABACUS LCAO implementations, the ecutwfc indirectly controls the precision of grid integration. Mainly there are three energy terms rely on grid integration technique, which are, Hartree, XC and local part of pseudopotential:

$\int {d\mathbf{r} V(\mathbf{r}) \rho(\mathbf{r})}$, 

which is approximated as:

$\sum_{i}{\Delta\mathbf{r}V(\mathbf{r}_i)\rho(\mathbf{r}_i)}$

. $\rho$ and $V$ will be evaluated on real space grid by interpolation, 

$\rho(\mathbf{r}) = \sum_{\mathbf{R}}{\sum_{\mu\nu}{D_{\mu\nu}(\mathbf{R})\phi^\dagger_{\mu, \mathbf{0}}(\mathbf{r})\phi_{\nu, \mathbf{R}}(\mathbf{r})}}$

and $V$ is either directly a functional of $\rho(\mathbf{r})$, or like $V_\text{local}$ in pseudopotential that involving both the Fourier transformation on atom-centered potential, and a structural factor, then do reverse Fourier transform. So in Hamiltonian they are actually defined on the grid that is evenly distributed 3D, which is directly controled by ecutrho, which by default is, 4 times of ecutwfc.

So ecutwfc is really confusing for you that I fully understand, that it ought to be the parameter determining the number of planewaves to expand the wavefunction, and the total energy should be variational respect to the number of PW. If you try with larger basis, such as switching from DZP to TZDP, you will find the energy is lower.

Hope that helps.

**Comment by braveSXG** [comment]
Thanks for your answer. When I used pw as the basis type, the trend seemed normal in that the ETOT reduced with the increasing ecutwfc values.
