### ISSUE TITLE
Support mix precision for ABACUS

### ISSUE THREAD

**Issue by Qianruipku** [deepmodeling/abacus-develop#933]
## Background
We want ABACUS to treat both float and double data.
However, for fftw lib, when treating float data, functions are changed. (from fftw to fftwf)
e.g.
```cpp
FFTW\<double\>::FFTW(const int norder2_in)
{
    ccoef = (fftw_complex *) fftw_malloc(sizeof(fftw_complex) * norder2_in);
    dcoef = (double *) fftw_malloc(sizeof(double) * norder2_in);
    coef_plan = fftw_plan_dft_r2c_1d(norder2_in, dcoef, ccoef, FFTW_ESTIMATE);
}
FFTW\<double\>::~FFTW()
{
    fftw_destroy_plan(coef_plan);
	fftw_free(ccoef);
	fftw_free(dcoef);
}
void FFTW\<double\>::execute_fftw()
{
    fftw_execute(this->coef_plan);
}

#ifdef __MIX_PRECISION
FFTW\<float\>::FFTW(const int norder2_in)
{
    ccoef = (fftwf_complex *) fftw_malloc(sizeof(fftwf_complex) * norder2_in);
    dcoef = (float *) fftw_malloc(sizeof(float) * norder2_in);
    coef_plan = fftwf_plan_dft_r2c_1d(norder2_in, dcoef, ccoef, FFTW_ESTIMATE);
}
FFTW\<float\>::~FFTW()
{
    fftwf_destroy_plan(coef_plan);
	fftw_free(ccoef);
	fftw_free(dcoef);
}
void FFTW\<float\>::execute_fftw()
{
    fftwf_execute(this->coef_plan);
}
#endif
```
## Describe the solution you'd like
So we want an option to choose if we want use fftwf lib. (compile fftw with --enable-float)
When "USE_FLOAT" is on, we need add_definitions(-D__MIX_PRECISION) and compile fftwf lib at the same time.
Note: if we do not use MKL lib, then fftw and fftwf lib should be compiled,
          if we use MKL lib, we do not need compile another lib.

**Comment by denghuilu** [comment]
In order to implement single precision as well as mix precision routine in ABACUS. We need to solve the following TODO list:

- [x] Add single precision support for multi-device ops, #1729 
- [x] Add single precision support for template classes within modules: `module_psi`, `src_pw`, `module_hamilt`, `module_hsolver` and `module_pw` ... #1763 
- [x] Add single precision support for other related part of ABACUS #1763 
- [x] Add single precision support for ROCm implementations #1767 
- [ ] Add the precision flag into the INPUT file: `single`, `double` and `mix`, `double` by default.

**Comment by mohanchen** [comment]
this issue has been fixed by qianrui
